fvm/src/gas/mod.rs

(there's no reason to sum it twice)

simplify gas charging logic

---

fvm/src/lib.rs
fvm/src/machine/default.rs
fvm/src/machine/engine.rs
fvm/src/machine/mod.rs
testing/conformance/src/vm.rs
testing/conformance/tests/runner.rs

At the moment, the cache is pretty dumb and doesn't let us "precompile". But it's a place to start and it solves the core performance problem.

feat: caching wasmtime engine

---

README.md
testing/conformance/Cargo.toml
testing/conformance/README.md
testing/conformance/benches/bench_conformance.rs
testing/conformance/benches/bench_conformance_overhead.rs
testing/conformance/benches/bench_drivers.rs
testing/conformance/src/bin/perf-conformance.rs
testing/conformance/src/driver.rs
testing/conformance/src/lib.rs
testing/conformance/src/vector.rs
testing/conformance/src/vm.rs
testing/conformance/tests/runner.rs
testing/conformance/wasm-testing-config-uncompressed-cache.toml

Adding benchmarking, removing duplicated code from conformance tester, documenting benchmarking/testing in README, and adding ability to generate a perf flamegraph.

Benchmarking via test vectors

---

fvm/src/gas/mod.rs
fvm/src/kernel/default.rs
fvm/src/lib.rs
fvm/src/machine/default.rs
fvm/src/machine/mod.rs
fvm/src/reward_actor.rs
fvm/src/syscalls/bind.rs
shared/src/version/mod.rs

Lotus integration isn't quite bug-free, but there's no reason to keep these fixes in a separate branch while we continue working on that.

FVM fixes for lotus integration

---

fvm/src/kernel/default.rs

But don't charge when looking up the "origin" key, to be consistent with lotus.
partially addresses #319

fix: charge gas for state access when resolving a key address

---

README.md
rust-toolchain

chore: switch to stable rust

---

fvm/src/gas/price_list.rs
fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/machine/default.rs
fvm/src/machine/mod.rs
fvm/src/syscalls/crypto.rs
fvm/src/syscalls/mod.rs
sdk/src/crypto.rs
sdk/src/sys/crypto.rs
shared/src/sector/registered_proof.rs
shared/src/sector/seal.rs
shared/src/version/mod.rs
testing/conformance/Cargo.toml
testing/conformance/src/vm.rs

Rebased for builtin-actors extraction.
Closes https://github.com/filecoin-project/ref-fvm/issues/335.

Support nv15

---

.github/workflows/main.yml

chore:add action to add new issue to the project board

---

testing/conformance/Cargo.toml
testing/conformance/src/vm.rs

Fixes https://github.com/filecoin-project/ref-fvm/issues/370.

feat: add nv15 support to conformance test framework

---

testing/conformance/Cargo.toml
testing/conformance/src/vector.rs

This adds the nv15 test vectors.

chore: update test vectors

---

ipld/amt/fuzz/Cargo.toml
ipld/amt/fuzz/fuzz_targets/amt_fuzz.rs

We need to setup CI for the future.

Fix AMT fuzzing

---

fvm/src/lib.rs
fvm/src/machine/default.rs
fvm/src/system_actor.rs
shared/src/actor/builtin.rs
testing/conformance/src/vm.rs

for https://github.com/filecoin-project/builtin-actors/issues/122
companion to https://github.com/filecoin-project/builtin-actors/pull/132

builtin actor registry in system actor

---

.gitmodules
ipld/amt/fuzz/.gitignore
ipld/amt/fuzz/corpus
ipld/hamt/fuzz/.gitignore
ipld/hamt/fuzz/corpus

Add fuzzing corpus as submodule

Add fuzzing corpus

---

.clusterfuzzlite/Dockerfile
.clusterfuzzlite/build.sh
.clusterfuzzlite/project.yaml
.github/workflows/README.md
.github/workflows/cflite_batch.yml
.github/workflows/cflite_build.yml
.github/workflows/cflite_cron.yml
.github/workflows/cflite_pr.yml
ipld/amt/fuzz/.gitignore
ipld/amt/fuzz/corpus
ipld/amt/fuzz/corpus/equivalence
ipld/amt/fuzz/corpus/simple
ipld/hamt/fuzz/.gitignore
ipld/hamt/fuzz/corpus
ipld/hamt/fuzz/corpus/simple

It will fuzz on PR (if relevant code is changed), batch fuzz in the background,
produce fuzzing coverage reports and prune the corpus.
The aim of ClusterfuzzLite is to detect newly introduced regressions caused by code changes.

Add clusterfuzzlite integration

---

fvm/Cargo.toml
ipld/amt/Cargo.toml
ipld/bitfield/Cargo.toml
ipld/car/Cargo.toml
ipld/hamt/Cargo.toml
sdk/Cargo.toml
testing/conformance/Cargo.toml

Otherwise we have two different versions.

chore: release everything

---

fvm/Cargo.toml
ipld/amt/Cargo.toml
ipld/bitfield/Cargo.toml
ipld/car/Cargo.toml
ipld/hamt/Cargo.toml
sdk/Cargo.toml
shared/Cargo.toml
testing/conformance/Cargo.toml

This time, we're returning the right errors.

chore: release fvm_shared

---

fvm/Cargo.toml

I'm hoping this will fix builds on linux/arm64.

chore: update wasmtime

---

fvm/src/executor/default.rs

Fixed #438.
Please review each mapping and consider whether it makes sense. Recall that the context is errors that take place during top-level dispatch.
FYI @dignifiedquire

Map all executor errors to exit codes.

---

fvm/Cargo.toml
sdk/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml
testing/conformance/Cargo.toml

This is a very small release to define USR_ASSERTION_FAILED.

chore: release fvm_shared v0.5.1

---

fvm/src/gas/price_list.rs

Unneeded since Calico, I think.

Remove unused verify_post_discount

---

sdk/src/debug.rs

Just noticed a typo in the docs...

Spelling fix

---

fvm/src/kernel/default.rs

(found by @wadeAlexC)
Also validate hash function & length, just in case.

fix: avoid clobbering IPLD errors in syscalls

---

fvm/CHANGELOG.md
fvm/Cargo.toml
ipld/bitfield/CHANGELOG.md
ipld/bitfield/Cargo.toml
ipld/blockstore/CHANGELOG.md
ipld/blockstore/Cargo.toml
sdk/CHANGELOG.md
sdk/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/integration/tests/fil-hello-world-actor/Cargo.toml
testing/integration/tests/fil-stack-overflow-actor/Cargo.toml

fvm 0.8.0
bitfield 0.5.2
blockstore 0.1.2
sdk 0.7.0
shared 0.7.0

chore: release (almost) everything

---

.github/workflows/audit.yml

ci: run cargo-audit

---

fvm/CHANGELOG.md
fvm/src/syscalls/mod.rs
sdk/src/lib.rs

See [thread](https://github.com/filecoin-project/ref-fvm/pull/555/commits/ec3086d38601426e9cb219ad4301ac3b6cb6248d#r872509685).

revert MAX_CID_LEN to 100.

---

fvm/CHANGELOG.md
fvm/Cargo.toml
ipld/encoding/CHANGELOG.md
ipld/encoding/Cargo.toml
sdk/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/integration/tests/fil-hello-world-actor/Cargo.toml
testing/integration/tests/fil-stack-overflow-actor/Cargo.toml

release fvm@1.0.0-rc.1, fvm_sdk@1.0.0-rc.1, fvm_ipld_encoding@0.2.1.

---

fvm/src/syscalls/context.rs
fvm/src/syscalls/mod.rs
sdk/src/actor.rs
sdk/src/crypto.rs
sdk/src/ipld.rs
sdk/src/lib.rs
sdk/src/sself.rs
shared/src/lib.rs

Seems like an improvement to me, suggested by @WadeAlexC

Unify MAX_CID_LEN

---

testing/integration/tests/lib.rs

Make sure we turn them into the correct exit code.

test: check unreachable & divide by zero

---

fvm/src/machine/engine.rs

This works around #602, until patches get merged upstream.

fix: fixup wasm sections after instrumentation

---

fvm/tests/default_kernel/mod.rs
fvm/tests/default_kernel/ops.rs

adds tests for testing that errors returned by a failed operation are what is expected.

Asserts for Unit Test Errors

---

fvm/CHANGELOG.md
fvm/Cargo.toml
ipld/amt/CHANGELOG.md
ipld/amt/Cargo.toml
ipld/encoding/CHANGELOG.md
ipld/encoding/Cargo.toml
sdk/CHANGELOG.md
sdk/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/integration/tests/fil-hello-world-actor/Cargo.toml
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-stack-overflow-actor/Cargo.toml

Also release:
- fvm_shared 0.8.0
- fvm_ipld_amt 0.4.2
- fvm_ipld_encoding 0.2.2

chore: release fvm & sdk 1.0.0-rc3

---

fvm/CHANGELOG.md
fvm/Cargo.toml
sdk/CHANGELOG.md
sdk/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/integration/tests/fil-hello-world-actor/Cargo.toml
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-stack-overflow-actor/Cargo.toml

Release FVM 1.0

---

fvm/CHANGELOG.md
fvm/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml

Release FVM 1.1, with dual execution support.

Release FVM 1.1

---

fvm/src/syscalls/context.rs
fvm/tests/default_kernel/mod.rs
fvm/tests/dummy.rs
sdk/src/actor.rs
sdk/src/sys/actor.rs
testing/conformance/src/vm.rs

Also replaces `!` with `Result<Infaliable>`

Fix more compiler warnings

---

ipld/car/src/lib.rs
ipld/car/src/util.rs
testing/conformance/src/vm.rs
testing/integration/src/builtin.rs

These aren't really critical as we only use CARs for distributing bundles, but they're still good fixes to have.

fix three bugs in our car implementation

---

fvm/Cargo.toml
sdk/Cargo.toml
shared/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/integration/tests/fil-hello-world-actor/Cargo.toml
testing/integration/tests/fil-integer-overflow-actor/Cargo.toml
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-malformed-syscall-actor/Cargo.toml
testing/integration/tests/fil-stack-overflow-actor/Cargo.toml

I'm doing this on master first so we can release an fvm_shared here, then I'll backport.

chore: update proofs

---

fvm/Cargo.toml
sdk/Cargo.toml
shared/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/integration/tests/fil-hello-world-actor/Cargo.toml
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-stack-overflow-actor/Cargo.toml

Note: this _updates_ shared _here_, because path dependencies... but we're cutting the release on master.
Yeah, all this kind of sucks. But multi-crate workspaces are... yeah.

backport: update to proofs 12

---

fvm/src/call_manager/default.rs
fvm/src/call_manager/mod.rs
fvm/src/executor/default.rs
fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/syscalls/vm.rs
fvm/tests/dummy.rs
sdk/src/message.rs
shared/src/sys/out.rs
testing/conformance/src/vm.rs

Return message origin in `vm::context()` syscall

---

shared/src/crypto/hash.rs

closes https://github.com/filecoin-project/ref-fvm/issues/794

add blake2b512

---

fvm/src/account_actor.rs
fvm/src/call_manager/default.rs
fvm/src/executor/default.rs
fvm/src/executor/mod.rs
fvm/src/gas/outputs.rs
fvm/src/kernel/default.rs
fvm/src/machine/default.rs
fvm/src/machine/mod.rs
fvm/src/state_tree.rs
fvm/src/syscalls/send.rs
fvm/tests/default_kernel/mod.rs
shared/src/econ/mod.rs
shared/src/lib.rs
shared/src/message.rs
shared/src/sys/mod.rs
testing/conformance/benches/bench_conformance_overhead.rs
testing/conformance/src/vm.rs
testing/integration/examples/integration.rs
testing/integration/src/tester.rs
testing/integration/tests/fil-stack-overflow-actor/src/lib.rs
testing/integration/tests/fil_integer_overflow.rs
testing/integration/tests/fil_syscall.rs
testing/integration/tests/lib.rs

This came out pretty cleanly, without much churn in code elsewhere. Please review carefully. Suggestions for better method names are welcome.
I have implemented display in human units (i.e. with decimal point). I've not implemented parsing from string but that would make a nice follow-up for someone.
Closes #704

Change TokenAmount from a type alias to a struct type wrapping BigInt

---

fvm/src/kernel/default.rs
fvm/src/kernel/hash.rs
fvm/src/kernel/mod.rs
sdk/src/crypto.rs
shared/src/crypto/hash.rs
testing/integration/tests/fil-syscall-actor/src/lib.rs

continuation of #799 because github hates forks

move multihash table to fvm and replace with simple enum

---

fvm/Cargo.toml
sdk/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/integration/tests/fil-hello-world-actor/Cargo.toml
testing/integration/tests/fil-integer-overflow-actor/Cargo.toml
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-malformed-syscall-actor/Cargo.toml
testing/integration/tests/fil-stack-overflow-actor/Cargo.toml
testing/integration/tests/fil-syscall-actor/Cargo.toml

This will let us release a v1 release/v1 for nv17.

feat: release fvm_shared v2 alpha

---

shared/src/econ/mod.rs

- multiply by all scalars (especially other bigints)
- div_ceil/div_floor

feat: implement additional TokenAmount ops

---

fvm/CHANGELOG.md
fvm/Cargo.toml
sdk/CHANGELOG.md
sdk/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/integration/tests/fil-hello-world-actor/Cargo.toml
testing/integration/tests/fil-integer-overflow-actor/Cargo.toml
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-malformed-syscall-actor/Cargo.toml
testing/integration/tests/fil-stack-overflow-actor/Cargo.toml
testing/integration/tests/fil-syscall-actor/Cargo.toml

Bumps fvm, fvm_shared, and fvm_sdk to 3-alpha.1.

chore: bump to v3

---

testing/integration/Cargo.toml

chore: add integration test crate metadata

---

shared/src/version/mod.rs

NetworkVersion: add nv17

---

fvm/src/machine/default.rs

Add nv17 to supported network versions

---

fvm/Cargo.toml
fvm/src/machine/engine.rs
testing/conformance/Cargo.toml
testing/integration/Cargo.toml

Update to wasmtime 0.40.1

---

shared/src/address/errors.rs
shared/src/address/mod.rs
shared/src/address/payload.rs
shared/src/address/protocol.rs
shared/tests/address_test.rs

We still need to decide on a final length, but this lets us represent f4 addresses.
I also took the opportunity to optimize things a bit.

feat: add f4 address support

---

shared/src/address/mod.rs
shared/tests/address_test.rs

- limit: 54 byte subaddress.
- checksum: 4 byte blake2b

feat: implement max limit and checksum from f4 fip

---

fvm/src/executor/default.rs
fvm/src/init_actor.rs
fvm/src/machine/mod.rs
fvm/src/state_tree.rs
fvm/src/system_actor.rs
shared/CHANGELOG.md
shared/src/address/mod.rs
shared/src/address/network.rs
testing/conformance/benches/bench_conformance_overhead.rs
testing/integration/src/builtin.rs

Alternative in https://github.com/filecoin-project/ref-fvm/pull/931, but we need to revert this for now so we can move forward.

revert: network ID address changes

---

fvm/src/lib.rs
fvm/src/machine/default.rs
fvm/tests/default_kernel/ops.rs
fvm/tests/dummy.rs
shared/src/version/mod.rs
testing/conformance/Cargo.toml
testing/conformance/src/vm.rs
testing/conformance/tests/runner.rs
testing/integration/examples/integration.rs
testing/integration/tests/bundles/mod.rs
testing/integration/tests/fil_integer_overflow.rs
testing/integration/tests/fil_syscall.rs
testing/integration/tests/main.rs

- And use it everywhere.
- And remove the test vectors until we get new ones.

feat: add network version 18

---

fvm/CHANGELOG.md
fvm/Cargo.toml
sdk/CHANGELOG.md
sdk/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/integration/tests/fil-address-actor/Cargo.toml
testing/integration/tests/fil-hello-world-actor/Cargo.toml
testing/integration/tests/fil-integer-overflow-actor/Cargo.toml
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-malformed-syscall-actor/Cargo.toml
testing/integration/tests/fil-stack-overflow-actor/Cargo.toml
testing/integration/tests/fil-syscall-actor/Cargo.toml

* fvm: 3.0.0-alpha.4
* fvm_shared: 3.0.0-alpha.7
* fvm_sdk: 3.0.0-alpha.7

release fvm, fvm_shared, fvm_sdk

---

fvm/CHANGELOG.md
fvm/Cargo.toml
sdk/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/integration/tests/fil-address-actor/Cargo.toml
testing/integration/tests/fil-hello-world-actor/Cargo.toml
testing/integration/tests/fil-integer-overflow-actor/Cargo.toml
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-malformed-syscall-actor/Cargo.toml
testing/integration/tests/fil-stack-overflow-actor/Cargo.toml
testing/integration/tests/fil-syscall-actor/Cargo.toml

Publish fvm and fvm_shared to release #1014 (blocking Lisbon release).

prepare fvm, fvm_shared release.

---

README.md
fvm/Cargo.toml
fvm/src/call_manager/default.rs
fvm/src/machine/engine.rs
fvm/src/machine/mod.rs
testing/conformance/Cargo.toml
testing/conformance/README.md
testing/conformance/benches/bench_drivers.rs
testing/conformance/src/bin/perf-conformance.rs
testing/conformance/src/driver.rs
testing/conformance/src/vector.rs
testing/conformance/src/vm.rs
testing/conformance/tests/runner.rs
testing/integration/Cargo.toml
testing/integration/tests/main.rs

Closes https://github.com/filecoin-project/ref-fvm/issues/1008 
```
$ TEST_VECTOR_POSTCONDITION_MISSING_ACTION=ignore VECTOR=test-vectors/corpus/extracted/0006-ohsnap-01/fil_7_storageminer/ExtendSectorExpiration/SysErrOutOfGas/ext-0007-fil_7_storageminer-ExtendSectorExpiration-SysErrOutOfGas-3.json cargo test conformance -- --nocapture
...
[FAIL] vector: test-vectors/corpus/extracted/0006-ohsnap-01/fil_7_storageminer/ExtendSectorExpiration/SysErrOutOfGas/ext-0007-fil_7_storageminer-ExtendSectorExpiration-SysErrOutOfGas-3.json | variant: ohsnap
|> reason: exit code of msg 0 did not match; expected: ExitCode { value: 7 }, got ExitCode { value: 4 }. Error: message failed with backtrace:
00: f0704941 (method 8) -- wasm `unreachable` instruction executed (4)
...
```
The error is produced where …

MEM-1008: Use pooling

---

sdk/src/debug.rs

feat: set max log when init logger

---

shared/src/econ/mod.rs

fix: correctly format negative token amounts

---

fvm/CHANGELOG.md
fvm/Cargo.toml
sdk/CHANGELOG.md
sdk/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/integration/tests/fil-address-actor/Cargo.toml
testing/integration/tests/fil-events-actor/Cargo.toml
testing/integration/tests/fil-hello-world-actor/Cargo.toml
testing/integration/tests/fil-integer-overflow-actor/Cargo.toml
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-malformed-syscall-actor/Cargo.toml
testing/integration/tests/fil-stack-overflow-actor/Cargo.toml
testing/integration/tests/fil-syscall-actor/Cargo.toml

fvm => 3.0.0-alpha.8
fvm_shared => 3.0.0-alpha.11
fvm_sdk => 3.0.0-alpha.11

release fvm, fvm_shared, fvm_sdk (+)

---

fvm/src/kernel/default.rs
fvm/src/syscalls/vm.rs

We no longer support old network versions.

feat: remove dead code

---

Cargo.lock
sdk/CHANGELOG.md
sdk/Cargo.toml
testing/integration/tests/fil-address-actor/Cargo.toml
testing/integration/tests/fil-events-actor/Cargo.toml
testing/integration/tests/fil-hello-world-actor/Cargo.toml
testing/integration/tests/fil-integer-overflow-actor/Cargo.toml
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-malformed-syscall-actor/Cargo.toml
testing/integration/tests/fil-stack-overflow-actor/Cargo.toml
testing/integration/tests/fil-syscall-actor/Cargo.toml

Includes two breaking changes:
- abort -> exit
- new_actor_address -> next_actor_address

chore: release the sdk

---

Cargo.lock
fvm/src/syscalls/vm.rs
testing/integration/Cargo.toml
testing/integration/tests/fil-exit-data-actor/Cargo.toml
testing/integration/tests/fil-exit-data-actor/build.rs
testing/integration/tests/fil-exit-data-actor/src/lib.rs
testing/integration/tests/main.rs

Adds an integration test for exit with data.
Fixes a bug in the handling of exit code in the syscall.

exit data integration test and bug fixes

---

fvm/src/syscalls/vm.rs

This limits the overall size of a backtrace to ~1MiB of user data.

feat: limit the size of backtrace messages to 1k

---

fvm/src/call_manager/default.rs
fvm/src/call_manager/mod.rs
fvm/src/gas/mod.rs
fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/tests/default_kernel/ops.rs
fvm/tests/dummy.rs
testing/conformance/src/vm.rs

see https://github.com/filecoin-project/ref-fvm/pull/1140

feat: add interior mutability to the gas tracker

---

shared/src/error/mod.rs

This is now a userspace error.

fix: remove deprecated exit code

---

Cargo.lock
fvm/src/call_manager/default.rs
fvm/src/call_manager/mod.rs
fvm/src/executor/default.rs
fvm/src/gas/mod.rs
fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/syscalls/send.rs
fvm/tests/dummy.rs
sdk/src/send.rs
sdk/src/sys/send.rs
shared/src/error/mod.rs
testing/conformance/src/vm.rs
testing/integration/Cargo.toml
testing/integration/src/tester.rs
testing/integration/tests/fil-address-actor/src/actor.rs
testing/integration/tests/fil-events-actor/src/actor.rs
testing/integration/tests/fil-gaslimit-actor/Cargo.toml
testing/integration/tests/fil-gaslimit-actor/build.rs
testing/integration/tests/fil-gaslimit-actor/src/actor.rs
testing/integration/tests/fil-gaslimit-actor/src/lib.rs
testing/integration/tests/fil-stack-overflow-actor/src/actor.rs
testing/integration/tests/gaslimit_test.rs

Closes https://github.com/filecoin-project/ref-fvm/issues/966.

send syscall: take an optional gas limit.

---

Cargo.lock
fvm/CHANGELOG.md
fvm/Cargo.toml
sdk/CHANGELOG.md
sdk/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/integration/tests/fil-address-actor/Cargo.toml
testing/integration/tests/fil-events-actor/Cargo.toml
testing/integration/tests/fil-exit-data-actor/Cargo.toml
testing/integration/tests/fil-gaslimit-actor/Cargo.toml
testing/integration/tests/fil-hello-world-actor/Cargo.toml
testing/integration/tests/fil-integer-overflow-actor/Cargo.toml
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-malformed-syscall-actor/Cargo.toml
testing/integration/tests/fil-readonly-actor/Cargo.toml
testing/integration/tests/fil-stack-overflow-actor/Cargo.toml
testing/integration/tests/fil-syscall-actor/Cargo.toml

Release FVM, SDK, and shared

---

fvm/src/executor/default.rs

A non-controversial part of #987.

fix: mark "send" params as "raw"

---

Cargo.lock
fvm/Cargo.toml
fvm/src/engine.rs
fvm/src/gas/price_list.rs

We're not yet taking advantage of it, but this uses the new
instrumentation logic.

feat: update instrumentation

---

fvm/src/kernel/default.rs

fix: compile with m2-native

---

ipld/encoding/src/cbor.rs

This only reverts the portion of #804 that touched ipld::encoding. This allows us to ship patch releases off the v2 branch, while still getting the benefit of this in the v3 branch.

Revert: Remove blake2b hashing which was moved to builtin-actors

---

fvm/src/call_manager/default.rs
fvm/src/call_manager/mod.rs
fvm/src/kernel/default.rs
fvm/tests/dummy.rs
testing/conformance/src/vm.rs

fix [#1257](https://github.com/filecoin-project/ref-fvm/issues/1257)

fix the m2-native feature missing engine getter

---

Cargo.lock
fvm/Cargo.toml
fvm/src/account_actor.rs
fvm/src/call_manager/default.rs
fvm/src/eam_actor.rs
fvm/src/executor/default.rs
fvm/src/kernel/default.rs
fvm/src/lib.rs
fvm/src/machine/manifest.rs
shared/Cargo.toml
shared/src/crypto/signature.rs
testing/integration/Cargo.toml
testing/integration/tests/embryo_sender_test.rs

Description to come, FYI for @Stebalien

Implement MMVP Account Abstraction

---

fvm/src/kernel/default.rs

I moved this to the call manager then failed to remove this one.
fixes #1188
Testing issue is https://github.com/filecoin-project/ref-fvm/issues/1287. I tried writing a test for this, but failed because I can't call init actor methods from "test" actors due to the API export limits.

fix: remove duplicate "create_actor" method

---

Cargo.lock
fvm/CHANGELOG.md
fvm/Cargo.toml
ipld/encoding/CHANGELOG.md
ipld/encoding/Cargo.toml
sdk/CHANGELOG.md
sdk/Cargo.toml
testing/calibration/Cargo.toml
testing/calibration/contract/fil-gas-calibration-actor/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/integration/tests/fil-address-actor/Cargo.toml
testing/integration/tests/fil-events-actor/Cargo.toml
testing/integration/tests/fil-exit-data-actor/Cargo.toml
testing/integration/tests/fil-gaslimit-actor/Cargo.toml
testing/integration/tests/fil-hello-world-actor/Cargo.toml
testing/integration/tests/fil-integer-overflow-actor/Cargo.toml
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-malformed-syscall-actor/Cargo.toml
testing/integration/tests/fil-readonly-actor/Cargo.toml
testing/integration/tests/fil-stack-overflow-actor/Cargo.toml
testing/integration/tests/fil-syscall-actor/Cargo.toml

Release fvm 3.0.0-alpha.16, ipld_encoding 0.3.1, sdk 3.0.0-alpha.19

---

fvm/src/executor/default.rs

Executor: Always transform embryo to eth_account if executing message

---

ipld/kamt/src/ext.rs
ipld/kamt/src/hash_bits.rs
ipld/kamt/src/node.rs

This patch contains two small KAMT improvements that make it easier to understand and reason about.
(prep work for #1356)

Small KAMT improvements

---

fvm/src/gas/price_list.rs

From #1264, we've learned that the compute gas for flushing state is
approximately 171963 per block.
I've:
1. Rounded this up to 172k (our measurements aren't that accurate).
2. Added a new "100 byte" (`100 * 1300 = 130k` gas) cost to the storage fee to cover per-block metadata and overhead.
This comes out to ~52k _less_ gas/block than the current per-block fee of 353640. However, when taking all costs into account (hashing, syscall overhead, allocations, memcpy, etc.) we're about even with pre-FVM gas fees for blocks less than 1KiB.
I'm _not_ charging per-byte for compute on flush because we're already charging 1300gas/byte in storage fees. This vastly exceed the per-byte compute cost, a couple of memory copies and allocations that would work out to be < 5gas/byte.
fixes #1264

feat: finalize write costs

---

fvm/src/gas/price_list.rs

We're slowly re-pricing these syscalls so we no longer need an explicit "extern" cost.
This is a code change and doesn't affect gas values.

remove the explicit extern cost & cleanups

---

sdk/src/send.rs

More work towards #987 
`Send` now returns a `Response` comprising of an exitcode and an optional IpldBlock return.

SDK: refactor: send should only return exit code and return data

---

sdk/CHANGELOG.md
sdk/Cargo.toml
testing/integration/tests/fil-hello-world-actor/Cargo.toml
testing/integration/tests/fil-integer-overflow-actor/Cargo.toml
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-malformed-syscall-actor/Cargo.toml
testing/integration/tests/fil-stack-overflow-actor/Cargo.toml
testing/integration/tests/fil-syscall-actor/Cargo.toml

Release SDK 2.2.0

---

Cargo.lock
sdk/CHANGELOG.md
sdk/Cargo.toml
testing/calibration/contract/fil-gas-calibration-actor/Cargo.toml
testing/integration/tests/fil-address-actor/Cargo.toml
testing/integration/tests/fil-events-actor/Cargo.toml
testing/integration/tests/fil-exit-data-actor/Cargo.toml
testing/integration/tests/fil-gaslimit-actor/Cargo.toml
testing/integration/tests/fil-hello-world-actor/Cargo.toml
testing/integration/tests/fil-integer-overflow-actor/Cargo.toml
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-malformed-syscall-actor/Cargo.toml
testing/integration/tests/fil-readonly-actor/Cargo.toml
testing/integration/tests/fil-stack-overflow-actor/Cargo.toml
testing/integration/tests/fil-syscall-actor/Cargo.toml

Release SDK 3.0.0-alpha.20

---

sdk/src/vm.rs
testing/integration/tests/fil-exit-data-actor/src/lib.rs

SDK: refactor: exit takes Option<IpldBlock>

---

sdk/src/send.rs
shared/src/lib.rs

Refactor: Move Response from SDK to shared

---

fvm/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml

v2: deps: Update wasmtime to v2.0.2

---

Cargo.lock
fvm/Cargo.toml
testing/calibration/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml

release: fvm

---

fvm/CHANGELOG.md
fvm/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml

Mostly updates wasmtime to 2.0.2.

chore: release fvm v2.2.0

---

fvm/src/machine/default.rs

Fixes #1359 
I wanted to put this in a separate method (something like `put_empties_in_blockstore()`, because we'll probably want to expand this to include things like empty maps, but wasn't sure how to specify the type for the blockstore param (and didn't want to fight Rust). Happy to make that change if we think it's better (and @Stebalien shows me how to do it) :P

FVM: Machine: Put the Empty Array CID on creation, if missing

---

Cargo.lock
fvm/src/kernel/default.rs
testing/integration/Cargo.toml
testing/integration/tests/fil-create-actor/Cargo.toml
testing/integration/tests/fil-create-actor/build.rs
testing/integration/tests/fil-create-actor/rust-toolchain
testing/integration/tests/fil-create-actor/src/actor.rs
testing/integration/tests/fil-create-actor/src/lib.rs
testing/integration/tests/fil-syscall-actor/src/actor.rs
testing/integration/tests/main.rs

Closes https://github.com/filecoin-project/ref-fvm/issues/1186

Restrict create_actor to the InitActor as caller

---

Cargo.lock
fvm/Cargo.toml
testing/conformance/Cargo.toml
testing/conformance/src/vector.rs
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-syscall-actor/Cargo.toml

We don't want to update any of the others, so this should close the issue. It was faster to do it than to talk about it.
fixes #1450

chore: update & audit deps

---

Cargo.lock
fvm/CHANGELOG.md
fvm/Cargo.toml
ipld/encoding/CHANGELOG.md
ipld/encoding/Cargo.toml
testing/calibration/Cargo.toml
testing/calibration/contract/fil-gas-calibration-actor/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/integration/tests/fil-address-actor/Cargo.toml
testing/integration/tests/fil-events-actor/Cargo.toml
testing/integration/tests/fil-exit-data-actor/Cargo.toml
testing/integration/tests/fil-gaslimit-actor/Cargo.toml
testing/integration/tests/fil-integer-overflow-actor/Cargo.toml
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-readonly-actor/Cargo.toml
testing/integration/tests/fil-syscall-actor/Cargo.toml

Release ipld_encoding 0.3.3, FVM 3.0.0-alpha.21

---

fvm/src/call_manager/default.rs

This normalizes the logic between different transaction systems in the FVM.
Pre-factor for https://github.com/filecoin-project/ref-fvm/pull/1521

feat: normalize transaction signatures

---

fvm/src/call_manager/default.rs
fvm/src/gas/mod.rs

Switch from taking/restoring the gas tracker, to a smarter gas tracker that internally keeps a gas limit stack.
I asked for the implementation I'm now replacing to save some allocations and avoid some error cases. In hindsight, that was a mistake.
I'm changing this now because I'd otherwise need to create a separate "long lived" gas tracking structure.

feat: simplify gas tracking stack

---

Cargo.lock
testing/integration/Cargo.toml

We haven't updated this for a while.

chore: release integration testing framework

---

fvm/src/call_manager/default.rs
fvm/src/call_manager/mod.rs
fvm/src/call_manager/state_access_tracker.rs
fvm/src/executor/default.rs
fvm/src/gas/charge.rs
fvm/src/gas/price_list.rs
fvm/src/history_map.rs
fvm/src/kernel/default.rs
fvm/src/lib.rs
fvm/src/machine/boxed.rs
fvm/src/machine/default.rs
fvm/src/machine/mod.rs
fvm/src/state_tree.rs
fvm/tests/dummy.rs
testing/conformance/src/vm.rs
testing/integration/tests/basic_send_test.rs

Implement the state/address load/store gas charging logic described in FIP-0057.
fixes https://github.com/filecoin-project/ref-fvm/issues/1346

feat: state access/update gas

---

Cargo.lock
fvm/src/call_manager/default.rs
fvm/src/gas/price_list.rs
testing/calibration/Cargo.toml
testing/calibration/contract/fil-gas-calibration-actor/build.rs
testing/calibration/contract/fil-gas-calibration-actor/src/lib.rs
testing/calibration/src/bin/on_hashing.rs
testing/calibration/src/bin/on_recover_secp_public_key.rs
testing/calibration/src/bin/on_send.rs
testing/calibration/src/bin/on_verify_signature.rs
testing/calibration/src/lib.rs
testing/integration/tests/basic_send_test.rs

This change:
1. Introduces a way to benchmark send costs.
2. Updates the send prices.

feat: send benchmarks and updated prices

---

fvm/src/kernel/default.rs
shared/src/event/mod.rs
testing/calibration/contract/fil-gas-calibration-actor/src/lib.rs
testing/integration/tests/fil-events-actor/src/actor.rs
testing/integration/tests/fil-gaslimit-actor/src/actor.rs
testing/integration/tests/fil-readonly-actor/src/lib.rs

See https://github.com/filecoin-project/FIPs/pull/617.

Add size validation and codecs to events

---

fvm/src/gas/price_list.rs

https://github.com/filecoin-project/FIPs/pull/626
Also fix a bug in computing message inclusion costs (caught by a new test in lotus).

feat: update storage gas costs

---

Cargo.lock
testing/integration/Cargo.toml
testing/integration/tests/fil-oom-actor/Cargo.toml
testing/integration/tests/fil-oom-actor/build.rs
testing/integration/tests/fil-oom-actor/src/lib.rs
testing/integration/tests/main.rs

See https://github.com/filecoin-project/ref-fvm/issues/1115
This exercises condition 1, whereby an actor can run OOM either by allocating one big chunk or many small ones.

test actor OOM conditions

---

testing/integration/tests/fil-oom-actor/src/lib.rs
testing/integration/tests/main.rs

test actor OOM conditions, Part II

---

testing/integration/src/testkit/fevm.rs
tools/fvm-bench/src/fevm.rs
tools/solidity-tests/README.md
tools/solidity-tests/libraries/EVMUtils.sol
tools/solidity-tests/libraries/ErrLib.sol
tools/solidity-tests/libraries/FilUtils.sol
tools/solidity-tests/libraries/Test.sol
tools/solidity-tests/libraries/deployable/Dummy.sol
tools/solidity-tests/libraries/deployable/Lifecycle.sol
tools/solidity-tests/libraries/deployable/Nested.sol
tools/solidity-tests/package.json
tools/solidity-tests/script.sh
tools/solidity-tests/tests/TestEVMPrecompiles.sol
tools/solidity-tests/tests/TestFilPrecompiles.sol
tools/solidity-tests/tests/TestLifecycle.sol
tools/solidity-tests/tests/TestStaticContext.sol
tools/solidity-tests/tests/recursive/TestRecursiveCall.sol
tools/solidity-tests/tests/recursive/TestRecursiveCreate.sol
tools/solidity-tests/tests/recursive/TestRecursiveCreate2.sol

Transplanted from https://github.com/filecoin-project/fvm-bench/pull/10

Alex Wade's solidity test framework

---

Cargo.lock
fvm/CHANGELOG.md
fvm/Cargo.toml
sdk/CHANGELOG.md
sdk/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml
testing/calibration/Cargo.toml
testing/calibration/contract/fil-gas-calibration-actor/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/integration/tests/fil-address-actor/Cargo.toml
testing/integration/tests/fil-create-actor/Cargo.toml
testing/integration/tests/fil-events-actor/Cargo.toml
testing/integration/tests/fil-exit-data-actor/Cargo.toml
testing/integration/tests/fil-gaslimit-actor/Cargo.toml
testing/integration/tests/fil-hello-world-actor/Cargo.toml
testing/integration/tests/fil-integer-overflow-actor/Cargo.toml
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-malformed-syscall-actor/Cargo.toml
testing/integration/tests/fil-readonly-actor/Cargo.toml
testing/integration/tests/fil-stack-overflow-actor/Cargo.toml
testing/integration/tests/fil-syscall-actor/Cargo.toml

This is just a final release to bump version numbers.

chore: release 3.0.0

---

ipld/blockstore/src/lib.rs

An Arc implementation would make the code in Forest significantly simpler. For example, we wouldn't need as many Clone , Send and Sync trait constraints.
More info: https://github.com/ChainSafe/forest/issues/2667

Impl blockstore for Arc<BS>

---

Cargo.lock
fvm/CHANGELOG.md
fvm/Cargo.toml
sdk/CHANGELOG.md
sdk/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml
testing/calibration/shared/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/test_actors/actors/fil-address-actor/Cargo.toml
testing/test_actors/actors/fil-create-actor/Cargo.toml
testing/test_actors/actors/fil-events-actor/Cargo.toml
testing/test_actors/actors/fil-exit-data-actor/Cargo.toml
testing/test_actors/actors/fil-gas-calibration-actor/Cargo.toml
testing/test_actors/actors/fil-gaslimit-actor/Cargo.toml
testing/test_actors/actors/fil-hello-world-actor/Cargo.toml
testing/test_actors/actors/fil-integer-overflow-actor/Cargo.toml
testing/test_actors/actors/fil-ipld-actor/Cargo.toml
testing/test_actors/actors/fil-malformed-syscall-actor/Cargo.toml
testing/test_actors/actors/fil-oom-actor/Cargo.toml
testing/test_actors/actors/fil-readonly-actor/Cargo.toml
testing/test_actors/actors/fil-sself-actor/Cargo.toml
testing/test_actors/actors/fil-stack-overflow-actor/Cargo.toml
testing/test_actors/actors/fil-syscall-actor/Cargo.toml

chore: release fvm/fvm_shared/fvm_sdk 3.2

---

.github/workflows/ci.yml

This new version cleans the cache.

chore: update cache action

---

fvm/src/executor/default.rs
fvm/src/machine/boxed.rs
fvm/src/machine/default.rs
fvm/src/state_tree.rs
fvm/tests/default_kernel/ops.rs
sdk/src/crypto.rs
sdk/src/rand.rs
testing/conformance/src/driver.rs
testing/conformance/tests/runner.rs

(needed to update the rust version)

chore: more clippy backports

---

Cargo.lock
fvm/Cargo.toml
fvm/src/machine/engine.rs
fvm/src/syscalls/error.rs
testing/conformance/Cargo.toml

feat: upgrade wasmtime to 8.0.1 (backport to v2)

---

fvm/src/gas/price_list.rs

chore: fix gas price comments

---

Cargo.lock
ipld/encoding/Cargo.toml

Pulls in the correct cid version.

chore: update serde-ipld-cbor

---

Cargo.lock
fvm/Cargo.toml
ipld/amt/Cargo.toml
ipld/bitfield/Cargo.toml
ipld/blockstore/Cargo.toml
ipld/car/Cargo.toml
ipld/encoding/Cargo.toml
ipld/hamt/Cargo.toml
ipld/kamt/Cargo.toml
sdk/Cargo.toml
shared/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/test_actors/actors/fil-events-actor/Cargo.toml
testing/test_actors/actors/fil-gas-calibration-actor/Cargo.toml
testing/test_actors/actors/fil-gaslimit-actor/Cargo.toml
testing/test_actors/actors/fil-integer-overflow-actor/Cargo.toml
tools/fvm-bench/Cargo.toml

Importantly, upgrade bls-signatures (breaking).

chore: upgrade deps prior to release

---

Cargo.lock
shared/Cargo.toml
testing/integration/Cargo.toml

Unfortunately, this would require some upgrades that aren't quite ready.

chore: downgrade bls signatures

---

Cargo.lock
testing/integration/Cargo.toml
testing/test_actors/actors/fil-create-actor/Cargo.toml
testing/test_actors/actors/fil-syscall-actor/Cargo.toml

test: depend on the correct builtin actors branch

---

fvm/src/externs/mod.rs
fvm/src/kernel/default.rs
fvm/src/lib.rs
fvm/tests/dummy.rs
testing/conformance/src/externs.rs
testing/conformance/src/rand.rs
testing/conformance/src/vector.rs

Backports #1842 onto the FVM v2. Testing by syncing calibrationnet.

feat: perform randomness hashing in the kernel

---

Cargo.lock
fvm/CHANGELOG.md
fvm/Cargo.toml
sdk/Cargo.toml
shared/Cargo.toml
testing/conformance/Cargo.toml

chore: release fvm 2.6.0

---

fvm/src/gas/price_list.rs
fvm/src/kernel/default.rs

Implements the soon-to-land FIP: https://github.com/filecoin-project/FIPs/pull/817
Closes #1860

feat: pricelist: implement randomness and tipset_cid repricing

---

Cargo.lock
fvm/Cargo.toml
rust-toolchain.toml
shared/Cargo.toml

feat: add feature flag support for cuda-supraseal

feat: upgrade to latest proofs and related dependencies

---

Cargo.lock
fvm/CHANGELOG.md
fvm/Cargo.toml
sdk/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml
testing/calibration/shared/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/test_actors/actors/fil-address-actor/Cargo.toml
testing/test_actors/actors/fil-create-actor/Cargo.toml
testing/test_actors/actors/fil-events-actor/Cargo.toml
testing/test_actors/actors/fil-exit-data-actor/Cargo.toml
testing/test_actors/actors/fil-gas-calibration-actor/Cargo.toml
testing/test_actors/actors/fil-gaslimit-actor/Cargo.toml
testing/test_actors/actors/fil-hello-world-actor/Cargo.toml
testing/test_actors/actors/fil-integer-overflow-actor/Cargo.toml
testing/test_actors/actors/fil-ipld-actor/Cargo.toml
testing/test_actors/actors/fil-malformed-syscall-actor/Cargo.toml
testing/test_actors/actors/fil-oom-actor/Cargo.toml
testing/test_actors/actors/fil-readonly-actor/Cargo.toml
testing/test_actors/actors/fil-sself-actor/Cargo.toml
testing/test_actors/actors/fil-stack-overflow-actor/Cargo.toml
testing/test_actors/actors/fil-syscall-actor/Cargo.toml

Updates:
- Proofs.
- Wasmtime.

chore: release fvm v3.8 and fvm_shared v3.6

---

Cargo.lock
README.md
fvm/Cargo.toml
sdk/Cargo.toml
shared/Cargo.toml
testing/calibration/shared/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/test_actors/actors/fil-address-actor/Cargo.toml
testing/test_actors/actors/fil-create-actor/Cargo.toml
testing/test_actors/actors/fil-events-actor/Cargo.toml
testing/test_actors/actors/fil-exit-data-actor/Cargo.toml
testing/test_actors/actors/fil-gas-calibration-actor/Cargo.toml
testing/test_actors/actors/fil-gaslimit-actor/Cargo.toml
testing/test_actors/actors/fil-hello-world-actor/Cargo.toml
testing/test_actors/actors/fil-integer-overflow-actor/Cargo.toml
testing/test_actors/actors/fil-ipld-actor/Cargo.toml
testing/test_actors/actors/fil-malformed-syscall-actor/Cargo.toml
testing/test_actors/actors/fil-oom-actor/Cargo.toml
testing/test_actors/actors/fil-readonly-actor/Cargo.toml
testing/test_actors/actors/fil-sself-actor/Cargo.toml
testing/test_actors/actors/fil-stack-overflow-actor/Cargo.toml
testing/test_actors/actors/fil-syscall-actor/Cargo.toml

⚠️ BREAKING ⚠️
Commits after this one will contain nv21 breaking network changes.

chore: release v4.0.0-alpha.1

---

testing/conformance/src/vm.rs

We no longer need this as we can access these fields from the machine directly.

feat: remove "kernel data" from the conformance test kernel/machine

---

ipld/kamt/src/error.rs
ipld/kamt/src/iter.rs
ipld/kamt/src/kamt.rs
ipld/kamt/src/lib.rs
ipld/kamt/src/node.rs

- Resolving https://github.com/filecoin-project/ref-fvm/issues/1862
- implemented iter and iter_from for kamt referring to hamt implementation.
- wrote simple test for iter_from [here](https://github.com/lordshashank/ref-fvm/blob/088dcbf015756ac7bd887cfa273d2de522b572a4/ipld/kamt/src/kamt.rs#L409)
- Also implemented function to declare kamt with custom bit width [here](https://github.com/lordshashank/ref-fvm/blob/088dcbf015756ac7bd887cfa273d2de522b572a4/ipld/kamt/src/kamt.rs#L86) and wrote its test [here](https://github.com/lordshashank/ref-fvm/blob/088dcbf015756ac7bd887cfa273d2de522b572a4/ipld/kamt/src/kamt.rs#L437)

Resolving Kamt issue#1862

---

Cargo.lock
Cargo.toml
fvm/CHANGELOG.md
sdk/CHANGELOG.md
shared/CHANGELOG.md

chore: release fvm 4.1.2

---

Cargo.lock
Cargo.toml

chore: update ahash

---

fvm/src/blockstore/buffered.rs
ipld/amt/src/node.rs
ipld/bitfield/src/iter/mod.rs
ipld/hamt/src/lib.rs
ipld/hamt/src/node.rs
ipld/kamt/src/node.rs
rust-toolchain.toml
sdk/src/message.rs
shared/src/address/mod.rs
shared/src/econ/mod.rs
testing/conformance/src/driver.rs
testing/conformance/src/vm.rs
testing/integration/tests/gas_calibration_test.rs
testing/test_actors/actors/fil-events-actor/src/actor.rs
testing/test_actors/actors/fil-exit-data-actor/src/actor.rs
testing/test_actors/actors/fil-gas-calibration-actor/src/actor.rs
testing/test_actors/actors/fil-oom-actor/src/lib.rs

Needed to upgrade wasmtime, and now's a reasonable time to do this.

chore: update rust and fix clippy lints

---

CONTRIBUTING.md

- Fixed broken link
- Added example PR
- Fixed some typos

Small tidy-ups in CONTRIBUTING.md

---

fvm/Cargo.toml
fvm/src/gas/price_list.rs
fvm/src/machine/default.rs
shared/src/version/mod.rs

feat: add nv24-skeleton

---

Cargo.lock
Cargo.toml
fvm/Cargo.toml
fvm/src/machine/engine.rs
testing/conformance/Cargo.toml

* chore: use workspace dependencies for wasmtime
* chore: update wasmtime from v12 to v24

[v2] update wasmtime from v12 to v24

---

Cargo.lock
Cargo.toml
fvm/Cargo.toml
fvm/src/kernel/error.rs
ipld/encoding/Cargo.toml
testing/conformance/Cargo.toml
tools/fvm-bench/Cargo.toml

All except cid/multihash because those will take more work.

chore: update deps

---

Cargo.lock
fvm/Cargo.toml
fvm/src/kernel/error.rs
shared/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/integration/tests/gasfuzz.rs
testing/test_actors/actors/fil-syscall-actor/Cargo.toml
tools/fvm-bench/Cargo.toml

[v3] chore: update deps

---

fvm/src/machine/mod.rs

What if I want to manually jump through the epochs?

Set epoch manually

---

fvm/CHANGELOG.md
fvm/Cargo.toml
fvm/src/gas/price_list.rs
fvm/src/machine/default.rs
sdk/CHANGELOG.md
shared/CHANGELOG.md

chore: remove the `nv24-dev` feature flag

chore: remove the `nv24-dev` feature flag

---

ipld/amt/src/iter.rs

When we hit the end of the AMT we'll update the "key" to where the next tree should start. Unfortunately, if we've filled in the high-end of the AMT, this key could overflow the max u64 by exactly one (i.e., it'll wrap to 0). So, instead, we saturate to the MAX_INDEX (which is `u64-1`).

fix(amt): saturate the index at MAX_INDEX+1

---

Cargo.lock
Cargo.toml
fvm/Cargo.toml
fvm/src/blockstore/buffered.rs
fvm/src/kernel/default.rs
fvm/src/kernel/hash.rs
fvm/src/kernel/mod.rs
fvm/src/lib.rs
fvm/src/machine/manifest.rs
fvm/src/state_tree.rs
fvm/tests/default_kernel/mod.rs
fvm/tests/default_kernel/ops.rs
fvm/tests/dummy.rs
shared/Cargo.toml
shared/src/crypto/hash.rs
shared/tests/commcid_tests.rs
testing/conformance/Cargo.toml
testing/conformance/src/driver.rs
testing/conformance/src/vm.rs

- cid
- multihash
- ipld-core
This is a major breaking change and requires a bit of a refactor.

chore: update ipld crates

---

fvm/CHANGELOG.md
fvm/Cargo.toml
fvm/src/gas/price_list.rs
fvm/src/machine/default.rs

chore: remove the nv25-dev feature flag

chore: remove the nv25-dev feature flag

---

fvm/src/gas/price_list.rs

PR against the new `release/4.6` branch which is @ tag `fvm@v4.6.0` / 11c4e06f2fbdb4842f53fe2aabe1a1e9ec50a99e

fix(gas): properly charge NI-PoRep gas according to FIP-0092

---

fvm/Cargo.toml
fvm/src/gas/price_list.rs
fvm/src/machine/default.rs
shared/src/version/mod.rs

feat: add nv27-skeleton

---

Cargo.lock
Cargo.toml
fvm/CHANGELOG.md
sdk/CHANGELOG.md
shared/CHANGELOG.md

chore: release v4.7.2

---

fvm/CHANGELOG.md
fvm/Cargo.toml
fvm/src/gas/price_list.rs
fvm/src/machine/default.rs

chore: remove the nv27-dev feature flag

chore: remove the nv27-dev feature flag

---

RELEASE.md

- updated the release doc with some additional information learnt during the recent backporting process.

chore(doc): update release doc with backport info
