filecoin-project/ref-fvm

fvm/src/executor/default.rs
fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/machine/default.rs
fvm/src/state_tree.rs
fvm/src/syscalls/sself.rs
shared/src/error/mod.rs
shared/src/sector/registered_proof.rs
testing/conformance/src/vm.rs

These cases should be unreachable in our current actors, but would not have been unreachable in user programmable actors.
Fixes #185 by _not_ returning fatal errors if the current actor doesn't exist in state.
After deletion:
1. Actors have "zero" balance.
2. Getting & setting the root fails with "illegal actor".
3. Sending still works, but sending with a value will fail because the balance is zero.
4. Sending _to_ this actor will fail.
Effectively, I'm treating "deletion" as "unlinking" the actor in the state-tree. It still _exists_ until it returns, it just can't be looked-up or linked back into the state.
NOTE: the exact error codes will change with https://github.com/filecoin-project/fvm-specs/pull/53.

Harden actor deletion (and some other errors)

---

actors/init/src/lib.rs
actors/market/src/lib.rs
actors/miner/src/lib.rs
actors/multisig/src/lib.rs
actors/paych/src/lib.rs
actors/power/src/lib.rs
actors/reward/src/lib.rs
actors/runtime/src/actor_error.rs
actors/runtime/src/builtin/shared.rs
actors/runtime/src/runtime/fvm.rs
actors/runtime/src/runtime/mod.rs
actors/runtime/src/test_utils.rs
actors/runtime/src/util/chaos/mod.rs
actors/runtime/src/util/downcast.rs
actors/verifreg/src/lib.rs
fvm/src/syscalls/network.rs
sdk/src/actor.rs
sdk/src/crypto.rs
sdk/src/debug.rs
sdk/src/gas.rs
sdk/src/ipld.rs
sdk/src/network.rs
sdk/src/sself.rs
sdk/src/sys/network.rs

Either:
1. These functions statically cannot fail (https://github.com/filecoin-project/fvm-specs/issues/580 to follow up on this).
2. These functions can only fail when passed invalid data that we've ensured is statically impossible with the type system.
Changes:
- FVM
- `curr_epoch` syscall returns an i64 to be consistent everywhere.
- SDK
- Newly infallible: `actor::resolve_address`, `actor::get_actor_code_cid`, `crypto::hash_blake2b`, `gas::charge`, `network::*`, `sself::current_balance`.
- Removed `ipld::transaction` (dead code).
- Changed `Address` and `Cid` to by-reference in some cases for better consistency.
- Actors
- Removed "fatal" errors.
- Adjusted to new infallible syscalls.
fixes #190

feat: remove errors from infallible sdk functions

---

actors/runtime/src/runtime/fvm.rs
sdk/src/message.rs

These are all infallible, so we might as well just panic at the syscall level.

feat: remove sdk::message::* error cases

---

sdk/src/actor.rs

There's no need to make the syscall if we already have an ID address. This also _documents_ the fact that resolving an address doesn't guarantee that the actor actually exists.

nit: short-circuit address resolution syscall

---

.github/workflows/ci.yml
Makefile

The new target in the makefile is not needed because testing `fvm_token_actor` package is covered by the check named `test`. To make it more explicit and faster, I extracted `fvm_token_actor` tests to another job.
I also made it possible to install additional packages per `cargo` target in the workflow. Then, I used it to install `ocl-icd-opencl-dev` in the new `test-fvm-token-actor` job.
@raulk heads up, looks like there is some flakiness in the tests. One of the CI runs failed as follows: https://github.com/filecoin-project/ref-fvm/runs/4935482784?check_suite_focus=true

ci: allow custom package installation for cargo

---

actors/runtime/src/runtime/fvm.rs
fvm/src/syscalls/crypto.rs
fvm/src/syscalls/debug.rs
sdk/src/crypto.rs
testing/conformance/src/vm.rs

1. Check the exit code in the actors runtime, in addition to checking the syscall result.
2. Verify signatures in conformance tests.
3. Correctly marshal the signer address in the sdk (don't use CBOR).
4. Avoid panicking when passing non-utf8 log messages (drive-by fix).
5. Fix parameter order in some crypto syscalls.
Unfortunately, I'm not updating the conformance tests in this PR due to some outstanding issues.

various fixes to the VM found on the new conformance tests

---

fvm/src/call_manager/default.rs
fvm/src/gas/mod.rs
testing/conformance/Cargo.toml
testing/conformance/src/vector.rs
testing/conformance/src/vm.rs
testing/conformance/tests/runner.rs

There were no more bugs in the FVM itself but this PR fixes a few bugs in the conformance test system:
1. Charge gas even for operations that aren't forwarded.
2. Correctly decode the circulating supply in test vectors (doesn't fit in an f64).
Additionally, it improves debuggability a bit:
1. Traces gas charges.
2. Traces value-only sends.
3. Make state-diffing work with partial states (i.e., just diff the relevant actors).
4. Very basic actor state diffing (diffs the root object as cbor).

update conformance vectors

---

actors/runtime/src/actor_error.rs
actors/runtime/src/runtime/fvm.rs
actors/runtime/src/test_utils.rs
fvm/src/call_manager/default.rs
fvm/src/executor/default.rs
fvm/src/executor/mod.rs
fvm/src/gas/mod.rs
fvm/src/kernel/default.rs
fvm/src/kernel/error.rs
fvm/src/machine/default.rs
fvm/src/machine/mod.rs
fvm/src/state_tree.rs
fvm/src/syscalls/actor.rs
fvm/src/syscalls/bind.rs
fvm/src/syscalls/context.rs
fvm/src/syscalls/crypto.rs
fvm/src/syscalls/error.rs
fvm/src/syscalls/vm.rs
sdk/Cargo.toml
sdk/src/actor.rs
sdk/src/crypto.rs
sdk/src/error.rs
sdk/src/lib.rs
sdk/src/message.rs
sdk/src/send.rs
sdk/src/sself.rs
sdk/src/sys/mod.rs
shared/src/error/mod.rs

This compiles now but will need some work:
1. https://github.com/filecoin-project/fvm-specs/pull/53 needs to be finalized.
2. We need to figure out how we want to handle "unexpected" errors. Currently, I'm panicking, but maybe we want to call `abort` with some exit code?

refactor: split out syscall errors from exit codes

---

actors/miner/src/lib.rs
shared/src/sector/seal.rs

The deal IDs are unused in `SealVerifyInfo`. It was an error that they remained in the Go version of this struct, which was replicated here. This is a nice opportunity to clean it up without prompting updates to a bunch of Go repos (such as filecoin-project/filecoin-ffi).

Remove unused deal ids from SealVerifyInfo

---

actors/miner/src/lib.rs
shared/src/sector/seal.rs

Reverts filecoin-project/ref-fvm#304
These get written to state when submitting seals for "bulk verification". This will require a network upgrade.
Unfortunately, when this PR was merged, conformance testing in CI was broken (see #310).

Revert "Remove unused deal ids from SealVerifyInfo"

---

fvm/src/call_manager/backtrace.rs
fvm/src/executor/default.rs
fvm/src/executor/mod.rs

We still account for gas, but we:
1. Don't charge on-chain gas.
2. Don't debt for gas.
3. Don't check the nonce.
NOTES:
1. We still _use_ the nonce (e.g., for actor creation).
2. We still account for gas.
Honestly, we should probably just have _two_ methods, but untangling these is a bit tricky.

feat: properly handle implicit messages

---

actors/market/src/lib.rs
actors/miner/Cargo.toml
actors/miner/src/bitfield_queue.rs
actors/miner/src/deadline_state.rs
actors/miner/src/expiration_queue.rs
actors/miner/src/lib.rs
actors/miner/src/sector_map.rs
actors/miner/src/sectors.rs
actors/miner/src/state.rs
actors/miner/src/termination.rs
actors/miner/src/vesting_state.rs
actors/multisig/src/lib.rs
actors/power/Cargo.toml
actors/power/src/lib.rs
actors/runtime/Cargo.toml
ipld/bitfield/Cargo.toml
ipld/bitfield/src/lib.rs
ipld/bitfield/tests/bitfield_tests.rs

HashMaps/Sets have worst-case O(N) runtime for most operations. Runtime perf is _expected_ to be `O(1)`, but that makes randomness assumptions. Unfortunately, in a deterministic system (e.g., actors compiled to  WASM), we can't make these assumption (in the presence of malicious agents, at least).
Basically, I'm concerned an attacker may be able to pick "keys" (addresses, sector infos, etc.) such that some `O(n)` algorithm turns into an `O(n^2)` algorithm.
In practice:
1. This doesn't _really_ matter for _most_ actors. It only matters for "shared" actors where some malicious party might influence the state in such a way that some other actor (e.g., cron, in our case), might get stuck.
2. This could be significantly mitigated by seeding HashMaps with chain randomness. It would still be …

Remove all uses of hash maps in actors

---

Cargo.toml
actors/init/Cargo.toml
actors/market/Cargo.toml
actors/miner/Cargo.toml
actors/multisig/Cargo.toml
actors/paych/Cargo.toml
actors/power/Cargo.toml
actors/runtime/Cargo.toml
actors/verifreg/Cargo.toml
examples/actor/Cargo.toml
fvm/Cargo.toml
ipld/amt/Cargo.toml
ipld/bitfield/Cargo.toml
ipld/car/Cargo.toml
ipld/hamt/Cargo.toml
sdk/Cargo.toml
shared/Cargo.toml
testing/conformance/Cargo.toml

We don't really need them for workspaces. The only patch we need is for CIDs.

feat: remove patches

---

actors/account/Cargo.toml
actors/account/build.rs
actors/cron/Cargo.toml
actors/cron/build.rs
actors/init/Cargo.toml
actors/init/build.rs
actors/market/Cargo.toml
actors/market/build.rs
actors/miner/Cargo.toml
actors/miner/build.rs
actors/multisig/Cargo.toml
actors/multisig/build.rs
actors/paych/Cargo.toml
actors/paych/build.rs
actors/power/Cargo.toml
actors/power/build.rs
actors/reward/Cargo.toml
actors/reward/build.rs
actors/runtime/Cargo.toml
actors/runtime/build.rs
actors/system/Cargo.toml
actors/system/build.rs
actors/verifreg/Cargo.toml
actors/verifreg/build.rs
fvm/src/machine/default.rs

- Use substrate-wasm-builder (upstream) not wasm-builder (a fork).
- Use the latest git to make sure the flags are actually applied
- Fix the flags:
- overflow-checks=yes
- lto=thin (I tried fat, but the build times were significantly and the binary sizes were no smaller)
fixes #322

actors: fix wasm build flags

---

actors/runtime/src/runtime/mod.rs
actors/runtime/src/test_utils.rs
fvm/src/externs/mod.rs
fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/lib.rs
fvm/src/syscalls/crypto.rs
sdk/src/crypto.rs
sdk/src/sys/crypto.rs
shared/src/consensus/mod.rs
shared/src/sys/out.rs
testing/conformance/src/externs.rs
testing/conformance/src/vm.rs

allow the verify consensus fault extern to return gasused

---

fvm/src/kernel/blocks.rs
fvm/src/kernel/default.rs

By using a `Box` instead of an `Rc`. We had an `Rc` to facilitate sharing (immutable) blocks between actors, but we never used it for that _anyways_.
Also make the block fields private.

feat: remove a block copy on read

---

fvm/Cargo.toml
fvm/src/call_manager/default.rs
fvm/src/machine/boxed.rs
fvm/src/machine/default.rs
fvm/src/machine/engine.rs
fvm/src/machine/mod.rs
fvm/src/syscalls/crypto.rs
testing/conformance/benches/bench_drivers.rs
testing/conformance/src/vm.rs

- cache syscall linker and constructed syscalls
- cache "pre instantiated" modules
This reduces conformance test run time from ~600s to ~100s on my machine and significantly increases network sync performance.

feat: optimize actor loading

---

testing/conformance/Cargo.toml

Related to #344, but this doesn't fix it (see the linked cargo issue).

fix: exclude test-vectors submodule from crate

---

Cargo.toml
ipld/hamt/Cargo.toml
ipld/hamt/src/pointer.rs
shared/Cargo.toml
shared/src/encoding/errors.rs
shared/src/encoding/mod.rs
testing/conformance/Cargo.toml
testing/conformance/src/driver.rs

Use a CBOR library that is tailored towards DAG-CBOR.
CIDs don't work as expected with Serde untagged enums, hence add a custom
implementation for the Pointer (de)serialization. That implementation works
similarly to the Serde untagged enum implementation.
First the data is deserialized into a common format that supports all types.
In our case that's `Ipld`, in Serde it's `Content`. Those are then converted
into the actual types the enum is using.
Directly converting from the serialized form into the concrete enum types is
not possible. One would need to try each of the possibilities sequentially
until one of them matches. The deserializer is consumed when deserializing,
hence it can only be used once. This is the reason to have the intermediate
step.

fix: use a different CBOR library

---

fvm/src/gas/mod.rs
fvm/src/gas/price_list.rs
fvm/src/machine/default.rs

Although this has no practical consequence today (there's only one PriceList in the FVM), this future-proofs us so that the evil that is `price_list_by_epoch` may not endure.

Switch price_list_by_epoch to price_list_by_network_version

---

ipld/bitfield/src/lib.rs
ipld/bitfield/src/rleplus/mod.rs

And refactor "first" to behave the same way.
Fixes the second point of https://github.com/filecoin-project/builtin-actors/issues/55.

feat(bitfield): add optimized last

---

README.md

- Remove reference to actors, which now live in https://github.com/filecoin-project/builtin-actors.

chore: update readme.

---

fvm/Cargo.toml
sdk/Cargo.toml
shared/Cargo.toml

Of the FVM, shared crate, and the sdk. Primarily, this completely removes the "identity" multihash feature.

Release v0.2.1

---

.github/workflows/ci.yml

Current SSCACHE is stuck due to: https://github.com/actions/toolkit/issues/658
as seen within https://github.com/filecoin-project/ref-fvm/runs/5711220587?check_suite_focus=true in `Post Setting up cache`
The simplest solution is to invalidate it by switching the start of the cache key to v1.

Invalidate SSCACHE on github

---

shared/src/piece/mod.rs

This is wanted for the built-in actors mock runtime.

Derive Debug for PieceInfo

---

fvm/src/lib.rs
fvm/src/machine/default.rs
testing/conformance/Cargo.toml
testing/conformance/src/vm.rs

1. If no manifest CID is passed, load the manifest from the system actor and assume "v1" for now. In the future, we'll likely use the network version to infer the manifest version.
2. If a manifest CID _is_ passed, assume it's a versioned manifest and use the specified version.
replaces #404

feat: switch to the new versioned manifest.

---

ipld/car/src/error.rs
shared/src/encoding/cbor.rs
shared/src/encoding/mod.rs

The error of the underlying CBOR library is an implementation detail,
it shouldn't leak into the public API. Instead use the error that
wraps it into the one specified by the module.

fix: don't leak underlying library error

---

shared/src/encoding/cbor.rs
shared/src/encoding/mod.rs

The previous patch only removed it from to_vec, but we need to do this everywhere.

fix: remove cbor serde error from everywhere

---

.clusterfuzzlite/build.sh
ipld/bitfield/Cargo.toml
ipld/bitfield/src/lib.rs
ipld/bitfield/src/rleplus/mod.rs
ipld/bitfield/src/unvalidated.rs
ipld/hamt/fuzz/Cargo.toml
testing/common_fuzz/Cargo.toml
testing/common_fuzz/fuzz/.gitignore
testing/common_fuzz/fuzz/Cargo.toml
testing/common_fuzz/fuzz/corpus/rle_decode
testing/common_fuzz/fuzz/corpus/rle_encode/rle_encode2
testing/common_fuzz/fuzz/corpus/rle_ops
testing/common_fuzz/fuzz/fuzz_targets/rle_decode.rs
testing/common_fuzz/fuzz/fuzz_targets/rle_encode.rs
testing/common_fuzz/fuzz/fuzz_targets/rle_ops.rs
testing/common_fuzz/fuzz/rust-toolchain
testing/common_fuzz/src/main.rs

decode-encode loop is currently disabled due to https://github.com/filecoin-project/ref-fvm/pull/409
I'm not happy with the directory structure, the cargo-fuzz requires
that there is a parent crate for every `fuzz` crate which makes things a bit
annoying.

Add RLE fuzzing

---

ipld/bitfield/Cargo.toml

This version is incompatible with previous versions due to a few changed
function signatures, and stricter validation. Continue using 0.3.0 to
validate networks before nv16.

chore: release fvm_ipld_bitfield 0.4.0

---

fvm/src/machine/engine.rs

This sets most of the basic settings (even if they are the same as defaults in case those change in a wasmtime update)

Set some wasmtime config settings

---

ipld/bitfield/src/rleplus/mod.rs

Honestly, we probably _don't_ need this in the FVM because:
1. Malicious inputs will burn gas for compute and won't be able to OOM the node.
2. Large bitfields will fail to serialize to state anyways.
However, I'd like relaxing this check to be an explicit step.
Fixes C1.

fix: enforce max bitfield size on decode

---

shared/src/version/mod.rs

Needed for FIP0031 implementation in filecoin-ffi.

add V16 to network version

---

fvm/src/call_manager/default.rs

The ordering of the checks here, and the comparison, are confusing (and
arguably incorrect but we're following the spec).

doc: explain call-stack-depth logic

---

shared/src/version/mod.rs

That way changing this isn't a breaking change.

fix: mark NetworkVersion as non-exhaustive

---

fvm/Cargo.toml
sdk/Cargo.toml
shared/Cargo.toml
testing/conformance/Cargo.toml

Technically, the fvm_shared release is a breaking change. But it won't impact any creates that actually _rely_ on 0.4.0 (the actors, and only the actors) and I just released it yesterday.

Release fvm 0.5.0, fvm_shared 0.4.1

---

fvm/Cargo.toml
testing/conformance/Cargo.toml

This release _just_ bumps wasmtime to a version that builds on aarch64.

chore: release 0.5.1

---

fvm/src/call_manager/default.rs
fvm/src/call_manager/mod.rs
fvm/src/executor/default.rs
fvm/src/syscalls/error.rs
fvm/src/syscalls/send.rs
fvm/src/syscalls/vm.rs
sdk/src/message.rs
sdk/src/send.rs
shared/src/error/mod.rs

This is for discussion first, following initial discussion on Slack. I've implemented ExitCode as a wrapper over a u32, not an enum. It thus accepts any value. I've then added constants for the system and standard values, updating them to match the FVM [spec](https://github.com/filecoin-project/fvm-specs/blob/main/07-errors.md).
Possible changes:
- Some way to use ExitCode values as values of an enum, rather than as a bag of constants.
- Rename back to CamelCase and explicitly ignore Clippy
The worst bit of this change, IMO, is renaming to ALL_CAPS to follow Rust convention for constants that are not enum values. I did try leaving the SystemExitCode values as an enum of integers, with a `From` implementation, but that results in a bunch of `.into()` wherever they are used. I opted to use …

Implement ExitCode as u32 wrapper, and use new spec codes

---

fvm/src/syscalls/vm.rs

Fixes #253.
I'm a little confused why I need a network version check here (to have conformance tests pass). I thought the master branch was for nv16 already. Should I instead update the conformance tests? How do I do that?

Reject system exit codes from abort

---

shared/src/bigint/bigint_ser.rs
shared/src/bigint/biguint_ser.rs
shared/src/bigint/mod.rs

The limit is taken from https://github.com/filecoin-project/go-state-types/blob/6027e22b77fd07693bf782401d10215057af9aad/big/int.go#L13

fix(shared): limit BigInt encoding and decoding sizes

---

shared/src/crypto/signature.rs

In order to use `#[serde(remote = "Signature")]` it is required to have its fields defined as public.
I need to be able to define how to serialize/deserialize message in json and for that I use serde remote trick. The Signature is part of a SignedMessage struct that I want to serialize/deserialize.

Make signature properties public

---

fvm/src/machine/default.rs

needed to instantiate the machine for nv16 in lotus.
We'll also need to bubble up a new release to filecoin-ffi, but for now I should be able to make do with patch.

add nv16 to supported network versions

---

fvm/Cargo.toml
sdk/CHANGELOG.md
sdk/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml
testing/conformance/Cargo.toml

Major breaking change: refactored error codes.
TODO: backport this chnage to prior actor releases?
Blocks https://github.com/filecoin-project/builtin-actors/pull/200

Release shared 0.5.0

---

sdk/src/sys/actor.rs
sdk/src/sys/crypto.rs
sdk/src/sys/debug.rs
sdk/src/sys/gas.rs
sdk/src/sys/ipld.rs
sdk/src/sys/message.rs
sdk/src/sys/mod.rs
sdk/src/sys/network.rs
sdk/src/sys/rand.rs
sdk/src/sys/send.rs
sdk/src/sys/sself.rs
sdk/src/sys/vm.rs
shared/src/sys/mod.rs

I've decided to document these in the SDK because this is the cleanest, low-level API definition we have. My plan is to link to the documentation from the spec instead of duplicating the syscall definitions in both places.
Rendered: https://bafybeif5utc6rkqubx3iiikkpn6ubompnd7xdowliznndocyaqgozy2uni.ipfs.dweb.link/fvm_sdk/sys/index.html

doc: document syscalls & errors

---

sdk/Cargo.toml
sdk/src/debug.rs
sdk/src/sys/mod.rs

When the debug feature is disabled, most actor debugging logic should get statically compiled out.
I've left it enabled by default for now, but we should consider disabling it by default for the final release. But if we do that, we need _some_ way to re-execute actors with debugging enabled.

feat: add a feature to statically disable debugging in the sdk

---

fvm/src/call_manager/default.rs
fvm/src/kernel/default.rs
fvm/src/lib.rs
fvm/src/machine/boxed.rs
fvm/src/machine/default.rs
fvm/src/machine/mod.rs
testing/conformance/benches/bench_drivers.rs
testing/conformance/src/driver.rs
testing/conformance/src/vm.rs

1. Reduce the number of arguments to the constructor.
2. Renames "debug" to actor_debugging to make it clear what it does, and document that it's
consensus critical.
3. Split the config into "network-wide" and "epoch-specific" sections.
This change also makes it clear that these options are all consensus critical.
fixes #249

refactor: combine/refactor context/config/machine arguments

---

fvm/src/blockstore/buffered.rs
fvm/src/call_manager/default.rs
fvm/src/executor/default.rs
fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/lib.rs
fvm/src/machine/boxed.rs
fvm/src/machine/default.rs
fvm/src/machine/mod.rs
fvm/src/state_tree.rs
ipld/hamt/src/hamt.rs
testing/conformance/src/driver.rs
testing/conformance/src/vm.rs

This refactor makes two significant changes:
1. Renames consume/take into `into_*` less ambiguous `into_*` functions.
2. Boxes the "inner" call manager to reduce the amount of copying as we move up and down the callstack.

Refactor consume/take

---

fvm/src/gas/price_list.rs
fvm/src/kernel/default.rs

We're charging for the number of bytes hashed, not the size of the entropy.

fix: charge randomness gas based on length of entropy

---

fvm/CHANGELOG.md
fvm/Cargo.toml
fvm/src/syscalls/bind.rs
fvm/src/syscalls/vm.rs
sdk/CHANGELOG.md
sdk/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml
shared/src/sys/mod.rs
shared/src/sys/out.rs
testing/conformance/Cargo.toml

I was hoping to _not_ do this as it might have a perf implication, but:
- Padding is undefined so we could end up leaking rust memory (and causing non-determinism at runtime).
- Requiring that everything be "packed" simplifies the spec. We don't need to explain alignment, just:
- little endian byte order
- packed
- In practice, there should be no performance issues (with existing syscalls). Specifically, we can re-order fields to avoid unaligned loads. This PR takes care of that.
Part of https://github.com/filecoin-project/fvm-specs/issues/63.

Use repr(packed, C) for syscall types

---

testing/conformance/Cargo.toml

This also fixes the actors version with the tilde version constraint so we won't auto-upgrade to the next _minor_ version (but will auto-upgrade patch releases).

chore: upgrade actors to use the new syscall abi

---

fvm/src/call_manager/default.rs
fvm/src/call_manager/mod.rs
fvm/src/executor/default.rs
fvm/src/executor/mod.rs
fvm/src/kernel/error.rs
fvm/src/lib.rs
fvm/src/machine/mod.rs
fvm/src/trace/mod.rs
testing/conformance/src/vm.rs

Resolves #318 
This gets us most of the way to matching Lotus execution traces -- fine gas tracing isn't implemented yet, but it will be impossible to meet that level of detail in M1 anyway.
The ExecutionTrace is created and populated by the call manager, which returns it on `finish`.

Implement execution traces for the FVM

---

sdk/src/sys/actor.rs
sdk/src/sys/crypto.rs
sdk/src/sys/gas.rs
sdk/src/sys/ipld.rs
sdk/src/sys/mod.rs
sdk/src/sys/rand.rs
sdk/src/sys/send.rs
sdk/src/sys/sself.rs
sdk/src/sys/vm.rs
shared/src/error/mod.rs

Rendered: https://ipfs.fleek.co/ipfs/bafybeicdt5pghmuyzvlpspxmvyaaroio3rfqxw2whcwxmed5kvqtfphuui/fvm_sdk/sys/index.html
1. Document the mapping between syscalls and wasm functions.
2. Linkify error numbers in syscall documentation.
3. Remove some incorrectly documented error numbers.
4. Exhaustively (almost all) arguments.
5. Document the syscall error number enum.
6. Link to the ABI documentation in the spec.

doc: improve syscall documentation

---

sdk/src/sys/mod.rs

If the fvm::abort syscall fails, abort from within rust instead of panicing. This will compile to an "unreachable" instruction in wasm and _won't_ invoke the panic processing logic.

fix: abort if aborting fails

---

fvm/src/call_manager/default.rs
fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/syscalls/bind.rs
fvm/src/syscalls/mod.rs
testing/conformance/src/vm.rs

Commit #1: I think this got clobbered in one of the review periods. 
Commit #2: The GasTracker's gas_available doesn't actually get updated through execution, so we should snapshot and consume based on gas_used instead.
Thanks to AWade for the catches.

fix: gas: charge for execunits based on snapshot

---

fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/syscalls/context.rs
fvm/src/syscalls/crypto.rs
fvm/src/syscalls/mod.rs
sdk/src/crypto.rs
sdk/src/sys/crypto.rs
testing/conformance/src/vm.rs

This makes it a bit easier to add support for additional hash functions later. We could just have many syscalls, but parameterizing over a multicodec makes it easier to implement/use multihash libraries in actors.
fixes #270

feat: parameterize the hash syscall over the hash type

---

fvm/src/syscalls/context.rs
ipld/blockstore/Cargo.toml
ipld/encoding/Cargo.toml
ipld/encoding/src/errors.rs
ipld/encoding/src/lib.rs
shared/src/bigint/bigint_ser.rs
shared/src/bigint/biguint_ser.rs
testing/conformance/Cargo.toml

ipld/encoding: switch to cbor4ii

---

fvm/Cargo.toml
ipld/amt/CHANGELOG.md
ipld/amt/Cargo.toml
ipld/bitfield/CHANGELOG.md
ipld/bitfield/Cargo.toml
ipld/car/CHANGELOG.md
ipld/car/Cargo.toml
ipld/encoding/CHANGELOG.md
ipld/encoding/Cargo.toml
ipld/hamt/CHANGELOG.md
ipld/hamt/Cargo.toml
sdk/CHANGELOG.md
sdk/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/integration/tests/fil-hello-world-actor/Cargo.toml

Unfortunately, this requires a bunch of releases because the change in fvm_ipld_encoding is technically a breaking one. But _most_ of these releases are small patch releases.
- fvm_shared - 0.6.1
- fvm_ipld_car - 0.4.1
- fvm_ipld_hamt - 0.5.1
- fvm_ipld_amt - 0.4.1
- fvm_ipld_encoding - 0.2.0
- fvm_sdk - 0.6.1

chore: release for cbor library switch

---

testing/conformance/Cargo.toml

Switches actors to the cbor4ii-backed encoding library.

chore: update actors in conformance tests

---

fvm/src/executor/default.rs
fvm/src/executor/mod.rs
fvm/src/system_actor.rs

See #523.
Also fixes a bug in system actors state, which was broken and revealed by the cbor4ii library (which is stricter than its predecessor).

propagate all gas outputs in ApplyRet

---

fvm/src/call_manager/default.rs
fvm/src/gas/mod.rs
fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/machine/engine.rs
fvm/src/syscalls/bind.rs
fvm/src/syscalls/mod.rs
testing/conformance/src/vm.rs

Basically:
1. On entering wasm, we call `update_gas_available` to update the available gas for the actor.
2. On exiting wasm, we call `charge_for_exec` to charge for execution gas.
Unlike the previous code:
1. We can handle this the same way in both the CallManager and the syscalls.
2. We never "borrow" or "return" the gas from/to the gas tracker.

feat: refactor gas charging to remove "borrowing"

---

fvm/src/call_manager/default.rs
fvm/src/machine/engine.rs
fvm/src/syscalls/bind.rs
fvm/src/syscalls/mod.rs
testing/integration/tests/lib.rs

Instead of looking up the memory export on every syscall, resolve it when we construct the invocation container.
fixes #510

feat: resolve the memory once

---

fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/syscalls/bind.rs
fvm/src/syscalls/crypto.rs
sdk/src/crypto.rs
sdk/src/sys/crypto.rs
shared/src/crypto/signature.rs
testing/conformance/src/vm.rs

Don't pass signatures as cbor-encoded objects with signature types. Instead, pass the type and the signature bytes separately.
This change _also_ avoids copying the signature when verifying it.
fixes https://github.com/filecoin-project/ref-fvm/issues/511

feat: raw signatures in syscalls

---

ipld/amt/benches/amt_benchmark.rs

Looks like something changed on nightly making this clippy lint more aggressive. Assuming this is like this to prevent optimizations, although I'm not sure how effective it is.

fix clippy on nightly.

---

ipld/amt/benches/amt_benchmark.rs
rust-toolchain

Currently Rust nightly is needed as the currently used `bellperson` version
needs else wouldn't build on ARM64. Using a specific version makes sure
that we don't get arbitrary Clippy failures on CI.
Also fix Clippy warning that comes up with using this nightly version.

chore: use a specific Rust nightly version

---

ipld/bitfield/src/lib.rs
ipld/bitfield/src/rleplus/mod.rs
ipld/bitfield/src/unvalidated.rs
ipld/bitfield/tests/bitfield_tests.rs

Error if one tries to decode a bitfield that is too large.
I don't know if that's really needed or not. I've added the test case from the Forest Actor Review.

fix: make sure bitfield is within limits

---

fvm/src/call_manager/backtrace.rs
fvm/src/call_manager/default.rs
fvm/src/executor/default.rs
fvm/src/machine/default.rs
fvm/src/syscalls/bind.rs
testing/integration/examples/integration.rs
testing/integration/src/builtin.rs
testing/integration/src/tester.rs
testing/integration/tests/lib.rs

Closes #508.
This PR transmutes fatal errors into the `SYS_ASSERTION_FAILED`  exit code at the top layer (Executor) to produce a consensus outcome on fatal errors.
It also modifies the Backtrace components to generalise them so they can tackle syscall errors as well as fatal errors. The cause is informed at different times for each, so the APIs have been adapted accordingly:
- For syscall errors, we inform the cause as soon as the syscall fails. Thus we reset the backtrace and accumulate the propagation chain (`Backtrace#begin()`).
- For fatal errors, we inform the cause at the top. Thus we accumulate the propagation chain, _then_ we inform the cause (`Backtrace#set_cause()`).
I think capturing backtraces (both FVM backtraces and Rust backtraces) is crucial for debuggability. Because I …

transmute fatal errors into `SYS_ASSERTION_FAILED` exit code.

---

sdk/src/lib.rs
sdk/src/message.rs
sdk/src/send.rs
sdk/src/vm.rs

They make more sense here than in the `vm` package.

sdk: reinstate the message package for message accessors.

---

testing/integration/src/tester.rs

go-fvm-sdk is using this tester for unit testing, but here I hope to be able to add accounts as expected, so that it is convenient to make assertions in unit test.

testing/integration: allow manually-defined accounts

---

fvm/src/call_manager/default.rs
fvm/src/executor/default.rs
fvm/src/gas/charge.rs
fvm/src/gas/mod.rs
fvm/src/gas/outputs.rs
fvm/src/gas/price_list.rs
fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/syscalls/bind.rs
fvm/src/syscalls/gas.rs
fvm/src/syscalls/mod.rs
testing/conformance/src/vm.rs

Motivation: we had two bugs in gas units (milligas versus gas):
1. Consensus fault charges from lotus (only applies to nv15).
2. Window post scaling charge.
This fixes those bugs, and adds a new "safe" gas type that lets us automatically avoid:
1. Multiplying gas by gas. Only `Gas * (i32/i64)` is implemented.
2. Adding gas to non-gas. Only `Gas + Gas` is implemented.
3. Swapping gas/milligas.
4. Not using saturating arithmetic. All gas operations use saturating arithmetic internally.
The automatic saturating arithmetic also makes the code significantly cleaner.

Strongly typed gas units, and fix two related bugs

---

fvm/Cargo.toml
fvm/src/call_manager/default.rs
fvm/src/executor/default.rs
fvm/src/machine/mod.rs
testing/integration/Cargo.toml
testing/integration/tests/fil-stack-overflow-actor/Cargo.toml
testing/integration/tests/fil-stack-overflow-actor/build.rs
testing/integration/tests/fil-stack-overflow-actor/rust-toolchain
testing/integration/tests/fil-stack-overflow-actor/src/lib.rs
testing/integration/tests/lib.rs

Better stack limits

---

fvm/src/executor/default.rs
fvm/src/executor/mod.rs
fvm/src/executor/threaded.rs
testing/integration/tests/lib.rs

We only _really_ need this executor when the caller doesn't guarantee the stack size.
Unfortunately, it can make testing hard because it means that the `Machine` needs to be `Send`. This breaks #557 which contains `Rc`s and `RefCell`s.

refactor: split threaded executor into a new struct

---

fvm/src/call_manager/default.rs
testing/integration/Cargo.toml
testing/integration/src/builtin.rs
testing/integration/tests/lib.rs

Catches panics when invoking Wasm and transforms them into fatal errors. I'm not sure about the safety properties of this, and if this has the chance of poisoning the machine. It doesn't appear like it will.
This also adds an integration test to induce the behaviour.

catch panics inside Wasm and lower to fatal errors.

---

fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/syscalls/ipld.rs
fvm/src/syscalls/mod.rs
sdk/src/ipld.rs
sdk/src/message.rs
sdk/src/send.rs
sdk/src/sys/ipld.rs
testing/conformance/src/vm.rs

Fixes the naming consistency issues identified in #521, but does not yet address the confusion around `block_link`.

clean up ipld syscall naming.

---

.github/workflows/ci.yml

This way we get useful feedback from other steps even if clippy, rustfmt, or conformance fails.

ci: set fail-fast to false

---

Cargo.toml
fvm/src/machine/default.rs
testing/conformance/Cargo.toml
testing/integration/Cargo.toml

This also sets the resolver to version 2, to avoid unifying the "testing" feature. Otherwise, the conformance tests break because the actors don't get preloaded.

fix: update actors to fix conformance tests

---

fvm/src/executor/default.rs
fvm/src/executor/mod.rs
fvm/src/executor/threaded.rs

This lets us call flush on a top-level ThreadedExecutor.

feat: add a flush method to the executor trait

---

fvm/src/kernel/default.rs
fvm/src/syscalls/context.rs

1. Catch panics when decoding cbor from actors.
2. Catch panics when verifying proofs, etc.
The only strictly necessary change is the window post one, as a panic there could make a proof indisputable. But there's no real _issue_ with being careful and turning all of these panics into "illegal argument" errors as they're all well isolated.

catch additional panics

---

fvm/src/call_manager/default.rs
fvm/src/kernel/default.rs
fvm/src/machine/default.rs
fvm/src/state_tree.rs
fvm/src/syscalls/debug.rs
sdk/src/sys/crypto.rs

1. If we fail to create an account due to a serialization error, treat it as an illegal argument and move on rather than failing.
2. Return NotFound if we fail to find an actor when resolving an address to a key.
3. Return NotFound (as documented) if the beneficiary doesn't exist on delete.
4. Return Forbidden (as documented) if the beneficiary is self on delete.
5. Remove nv14 support from `transfer`, and simplify some error handling.
6. Avoid logging when debugging is enabled.
7. Return Forbidden for various actor creation errors, instead of IllegalArgument.
Unresolved: `resolve_to_key_addr` (called when verifying a signature), returns IllegalArgument if the "signer" address is not an account. The thing is, IllegalArgument usually means that the caller "should have known better" (e.g., …

chore: audit errors

---

ipld/encoding/Cargo.toml

This fixes https://github.com/ipld/serde_ipld_dagcbor/pull/3.

deps: update serde_ipld_dagcbor to 0.2.2.

---

Cargo.toml
fvm/src/kernel/default.rs
sdk/src/ipld.rs
testing/integration/Cargo.toml
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-ipld-actor/build.rs
testing/integration/tests/fil-ipld-actor/rust-toolchain
testing/integration/tests/fil-ipld-actor/src/lib.rs
testing/integration/tests/lib.rs

1. Return the correct offset (relative to the end of the logical buffer, not relative to the end of the bytes read).
2. Don't cast "remaining" to a usize in read_block as it can be negative.
3. Add an exhaustive test.

fix: fix read syscall and sdk method

---

ipld/amt/src/amt.rs

Thanks to @WadeAlexC for the catch!

fix: AMT: correctly return whether found in batch_delete

---

fvm/Cargo.toml
fvm/src/gas/price_list.rs
fvm/tests/default_kernel/mod.rs
fvm/tests/default_kernel/ops.rs
fvm/tests/dummy.rs
fvm/tests/fvm.rs

Also adds `pretty_assertions` as a dev dependency since trying to find what is wrong with large structs using the default is near impossible.

Unit Tests for Default kernel `GasOps`

---

fvm/src/machine/engine.rs

Might fix the `wasm stack size cannot exceed the async stack size` issue @karim-agha is seeing

fix: machine config: disable async even with feature enabled

---

fvm/CHANGELOG.md
fvm/Cargo.toml
fvm/src/gas/price_list.rs
fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/syscalls/crypto.rs
fvm/src/syscalls/mod.rs
sdk/Cargo.toml
sdk/src/crypto.rs
sdk/src/sys/crypto.rs
shared/src/crypto/signature.rs
testing/conformance/Cargo.toml
testing/conformance/src/vm.rs
testing/integration/Cargo.toml
testing/integration/tests/fil-hello-world-actor/Cargo.toml
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-stack-overflow-actor/Cargo.toml

Adding new syscall to FVM that allows recovery of signer's public key from a message hash and a signature.
Issue: https://github.com/filecoin-project/ref-fvm/issues/617

Recover public key FVM syscall

---

fvm/Cargo.toml
shared/Cargo.toml
shared/src/sector/registered_proof.rs

Bumps to filecoin-proofs-api v11.1

Add new proofs version type

---

fvm/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml

Removes the need for https://github.com/filecoin-project/filecoin-ffi/pull/287
Also introduces some nice optimizations, apparently.

chore: update wasmtime

---

.github/actions/rust-sccache/action.yml
.github/workflows/ci.yml
fvm/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml

Wasmtime v0.38 introduced a regression, causing integration test `native_overflow_somethingsomething` to run for waay to long.
Rolling back the dep brought back some CI issues I saw earlier where the cache would keep growing after each build, so now it is trimmed before upload (as well as printing out sccache and cargo cache size)

Trim Ci cache before upload, rollback wasmtime to v0.37

---

.github/workflows/ci.yml
.gitignore
fvm/Cargo.toml
fvm/src/call_manager/default.rs
fvm/src/call_manager/mod.rs
fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/lib.rs
fvm/src/machine/boxed.rs
fvm/src/machine/default.rs
fvm/src/machine/mod.rs
fvm/src/syscalls/debug.rs
fvm/src/syscalls/mod.rs
fvm/tests/dummy.rs
sdk/src/debug.rs
sdk/src/sys/debug.rs
testing/conformance/Cargo.toml
testing/conformance/src/vm.rs
testing/integration/Cargo.toml
testing/integration/README.md
testing/integration/src/dummy.rs
testing/integration/src/tester.rs
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-ipld-actor/build.rs
testing/integration/tests/fil-ipld-actor/src/lib.rs
testing/integration/tests/fil-stack-overflow-actor/Cargo.toml

adds a new syscall under `debug` to save artifacts to a folder ~~in current dir `artifacts/` which is somewhat horrible and should probably be something else, but it works and adding the ability to modify that sort of thing is easy enough, just need to get a consensus on how it should be done.~~ defined by env var `FVM_STORE_ARTIFACT_DIR`
ATM this doesn't do any CI as I think CI should be heavily refactored anyways and adding this coverage can be added during then (ref https://github.com/filecoin-project/ref-fvm/issues/609)

Debug artifacts syscall + integration test coverage

---

ipld/encoding/CHANGELOG.md
ipld/encoding/src/lib.rs

When developing an actor, using `Deserialize_tuple` and `Serialize_tuple` from the `fvm_iplf_encoding` crate it would be useful to also have the `serde crate exported. It would also help with consistency of `serde` versioning between actors and the crate in the future. 
Discussed with @raulk during check-in for FVM EBP on Thursday 07/14

Expose serde from fvm_ipld_encoding

---

testing/integration/examples/integration.rs
testing/integration/src/dummy.rs
testing/integration/src/lib.rs
testing/integration/src/tester.rs
testing/integration/tests/fil_integer_overflow.rs
testing/integration/tests/fil_syscall.rs
testing/integration/tests/lib.rs

Let integration tests generic over externs

---

fvm/Cargo.toml
fvm/src/machine/default.rs

Getting chain randomness of current epoch is not allowed. Adds `rand` dep for now till better solutions are made.

add thread random generation of machine IDs 

---

fvm/src/call_manager/default.rs
fvm/src/machine/engine.rs

When the m2-native feature is enabled, the call manager now prepares the code for execution by calling the engine.

m2 native: ensure that code for an actor is ready for execution.

---

fvm/src/call_manager/default.rs
fvm/src/executor/default.rs
fvm/src/gas/charge.rs
fvm/src/gas/mod.rs
fvm/src/gas/price_list.rs
fvm/src/syscalls/bind.rs
fvm/src/trace/mod.rs
testing/conformance/src/vm.rs

BREAKING:
- This adds a new execution event type.
- The GasCharge object is now `'static`, but internally uses a `Cow` for the name.

feat: add gas charges to the execution trace

---

fvm/src/gas/price_list.rs
shared/src/actor/builtin.rs

Note: there's an active proposal to remove the type token entirely in #712. However, for the reasons outlined in the discussion, we need to retain it for now, unless we find a better indirection for actor typing (or we extinguish the need for it altogether).
This is needed to add the EVM actor (https://github.com/filecoin-project/builtin-actors/pull/517) to the built-in actors bundle.

shared: add EVM built-in actor type.

---

.gitmodules

This will help CI, but won't help anyone else depending on ref-fvm because, unfortunately, cargo will ignore this hint.

chore: checkout shallow submodules

---

fvm/Cargo.toml
fvm/src/machine/engine.rs

It's unmaintained and has some soundness issues. We don't really _need_ it, so I've just gone ahead and removed it entirely (re-implementing what we need).

feat: remove anymap

---

ipld/encoding/src/cbor.rs
shared/Cargo.toml
shared/src/message.rs

Relates to https://github.com/filecoin-project/builtin-actors/issues/91 and https://github.com/filecoin-project/builtin-actors/pull/577

chore: Remove blake2b hashing which was moved to builtin-actors

---

sdk/src/rand.rs

this is a necessary underlying changing for [builtin actor pull request 560](https://github.com/filecoin-project/builtin-actors/pull/560), to give an fix length byte array for `Randomness` instead of a `u8` vector

change randomness type to fix length byte array

---

fvm/CHANGELOG.md
sdk/CHANGELOG.md
sdk/Cargo.toml
testing/integration/tests/fil-hello-world-actor/Cargo.toml
testing/integration/tests/fil-integer-overflow-actor/Cargo.toml
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-malformed-syscall-actor/Cargo.toml
testing/integration/tests/fil-stack-overflow-actor/Cargo.toml
testing/integration/tests/fil-syscall-actor/Cargo.toml

Looks like I released alpha 1 when we bumped the FVM, so on to alpha 2?

chore: release sdk 2.0.0-alpha.2

---

fvm/Cargo.toml

Otherwise, compilation fails. It looks like some other crate was transitively enabling this feature, but not anymore.

chore: explicitly enable anyhow backtrace feature

---

shared/src/econ/mod.rs

1. Implement `{integer} * TokenAmount` to mirror the `TokenAmount * {integer}` implementation. Unfortunately, we can't use the same trick and need to implement `Mul` for each type.
2. Implement `Sum` for `TokenAmount` so we can sum iterators.
3. Implement `TokenAmount::from_nano` so we can construct from nanoFIL.

Add additional TokenAmount operations

---

.github/workflows/ci.yml
testing/integration/Cargo.toml
testing/integration/tests/fil-ipld-actor/Cargo.toml

- 'coverage' is not actually a feature, and should not be used as such.
- 'wasm-coverage' wasn't used anywhere, as far as I could tell.
This caused problems on publish because the `fil_ipld_actor` is a dev dependency, and features can't apply to dev dependencies like that.

fix: correct coverage features

---

fvm/CHANGELOG.md
fvm/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml

This will let us cut a new fvm_integration_tests release.

chore: release fvm v2 (alpha.2)

---

testing/integration/tests/fil-malformed-syscall-actor/src/lib.rs
testing/integration/tests/fil_integer_overflow.rs
testing/integration/tests/fil_syscall.rs

Instead, use the WASM_BINARY const exported by wasm-builder.

fix: avoid plucking integration test actors from target

---

Cargo.toml
testing/integration/Cargo.toml
testing/integration/examples/integration.rs
testing/integration/src/builtin.rs
testing/integration/src/bundle.rs
testing/integration/src/error.rs
testing/integration/src/lib.rs
testing/integration/src/tester.rs
testing/integration/tests/bundles/mod.rs
testing/integration/tests/fil_integer_overflow.rs
testing/integration/tests/fil_syscall.rs
testing/integration/tests/main.rs

This change:
- Moves the actor "bundle" dependency to the dev dependencies.
- Makes the `Tester` take a "bundle root cid".
- Exports a helper function for importing a bundle into a blockstore.
That way:
1. Users can instantiate integration tests with their _own_ bundle.
2. We can publish the integration testing _framework_ while testing against a dev bundle locally.

feat: avoid importing the bundle into the integration tests

---

sdk/src/crypto.rs
testing/integration/tests/fil-syscall-actor/src/lib.rs

uses `([u8; 64], usize)` instead of a vec

add hash_arr fn to SDK

---

testing/integration/Cargo.toml

Otherwise, crates.io will reject a publish of this crate.

chore: remove version specifier from bundle dev-dependency

---

shared/src/version/mod.rs

Backports #855 to the release/v2 branch.

NetworkVersion: add nv17

---

shared/src/econ/mod.rs

This explicit `u64` has been annoying downstream many times. Happily it should require no change in existing callers that pass u64.
FYI @ZenGround0

Change TokenAmount::from_whole to take any Into<BigInt> parameter

---

ipld/bitfield/benches/benchmarks/main.rs
ipld/bitfield/src/lib.rs
ipld/bitfield/src/ops.rs
ipld/bitfield/tests/bitfield_tests.rs

We have quite a few bitfield operations where one bitfield is empty.
Optimize them.

feat: optimize no-op bitfield operations

---

fvm/Cargo.toml
fvm/src/machine/engine.rs
testing/conformance/Cargo.toml
testing/integration/Cargo.toml

Closes #852, assuming it doesn't break things.

chore: deps: Update to wasmtime 0.40.1

---

shared/src/address/mod.rs
shared/src/address/network.rs
shared/src/address/payload.rs

add ordering to address so they can be used as keys in BTreeMaps #894

add ordering to address

---

ipld/encoding/src/cbor.rs

The derived representation of a list of decimals is very unhelpful when debugging, e.g. CBOR-encoded values. The hex string will at least be usable in an CBOR inspector, and I think usually not less useful for cases when the bytes are representing something else (tho since this is the CBOR library, that'll be uncommon).
FYI @ZenGround0 when debugging actors.

Format RawBytes debug as hex string rather than array of decimals

---

fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/machine/engine.rs
testing/conformance/src/vm.rs

In general, wasm modules should already be cached. However, pre-loading during tests is expensive, so it's nice to allow lazy loading.
This is likely still useful in M2.2. Even though the module _should_ be pre-compiled, the module cache will still be a _cache_.
Also note: A "baseline" compiler is coming to wasmtime (https://github.com/bytecodealliance/wasmtime/pull/4907) that will make lazy-loading a more viable option.
replaces #907 #714

feat: auto-load wasm modules from blockstore

---

sdk/src/message.rs

eaten during refactoring in #905.

sdk: add invocation context accessors for gas limit and premium

---

ipld/hamt/src/hamt.rs
ipld/hamt/src/node.rs
ipld/hamt/tests/hamt_tests.rs

fixes https://github.com/filecoin-project/builtin-actors/pull/709
The PR adds an optional `flushed_cid` field to the `Hamt` which is used to remember the CID it was initialized with until something changes and the `Hamt` if flushed again. If the field is set during `flush`, we have nothing to do and can return the already calculated CID. 
This saves the effort of serializing the root node and passing the data through the Wasm machinery for the CID to be calculated when there was no change made to the contents of the map.
If this PR is acceptable, it would be worth doing the same for the `Amt` in another PR.

EVM-899: Hamt::flush short circuit on no change

---

fvm/src/machine/engine.rs

This has a significant performance impact but got enabled in the wasmtime update.

fix: re-disable backtraces

---

fvm/src/machine/engine.rs

This has a significant performance impact but got enabled in the wasmtime update.

fix: re-disable backtraces (#919)

---

fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/syscalls/actor.rs
testing/conformance/src/vm.rs

Some history:
- At first, we returned an Option because these syscalls would return a special sentinel value for "not found".
- Then we changed the syscalls to return the NotFound error code, but we never updated the kernel methods.
Now, I'm adding another kernel method. But in my case, to keep this pattern, I'd need to return `Option<Option<Address>>`... so I'm proposing that we change these other kernel functions instead.

feat: simplify syscall returns

---

ipld/amt/Cargo.toml
ipld/amt/fuzz/Cargo.toml
ipld/blockstore/Cargo.toml
ipld/car/Cargo.toml
ipld/encoding/Cargo.toml
ipld/hamt/Cargo.toml
ipld/hamt/fuzz/Cargo.toml
sdk/Cargo.toml

It's nearly the end of 2022, and there are some nice features (e.g., better format strings).

chore: use rust 2021 edition

---

sdk/src/actor.rs

fix: return an Option from balance_of

---

fvm/src/account_actor.rs
fvm/src/call_manager/default.rs
fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/machine/manifest.rs
fvm/src/state_tree.rs
fvm/src/syscalls/actor.rs
fvm/src/syscalls/mod.rs
sdk/src/actor.rs
sdk/src/sys/actor.rs
shared/src/address/mod.rs
shared/tests/address_test.rs
testing/conformance/src/vm.rs
testing/integration/Cargo.toml
testing/integration/src/builtin.rs
testing/integration/src/tester.rs
testing/integration/tests/address_test.rs
testing/integration/tests/fil-address-actor/Cargo.toml
testing/integration/tests/fil-address-actor/build.rs
testing/integration/tests/fil-address-actor/src/actor.rs
testing/integration/tests/fil-address-actor/src/lib.rs

- Auto-create embryos on send.
- Allow overwriting embryo actors (used by the init actor).
- Record "predictable" addresses in state.
- Add a syscall for retrieving predictable addresses.

feat: f4 address class, embryo actors, and lookup_address

---

ipld/amt/CHANGELOG.md
ipld/amt/Cargo.toml
ipld/amt/src/amt.rs

- A vec is simpler for what we're doing here.
- Ahash needs randmness...

fix: remove ahash from the amt

---

fvm/Cargo.toml
fvm/src/machine/engine.rs
testing/conformance/Cargo.toml
testing/integration/Cargo.toml

Backports #943 without the other dependency updates.
Fixes #962.

chore: update wasmtime to 1.0

---

fvm/src/syscalls/actor.rs
testing/integration/tests/fil-syscall-actor/Cargo.toml
testing/integration/tests/fil-syscall-actor/src/actor.rs

Before, we'd only try to "read" an address if the length were 0, which was obviously incorrect. Previously, we would have caught this with the test vectors, but we had to disable those until we get a chance to extract new ones from a new test network.
This also adds a test so we don't run into this situation again.

fix: correct address length check for create_actor

---

shared/src/address/mod.rs
shared/tests/address_test.rs

Specifically, use `f` as the separator.

fix: make the f4 address format conform to FIP0048

---

fvm/src/call_manager/default.rs
fvm/src/call_manager/mod.rs
fvm/src/executor/default.rs
fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/syscalls/vm.rs
fvm/tests/dummy.rs
testing/conformance/src/vm.rs

Before, we'd look in the actor state itself. But that's no longer necessary.
This patch:
1. Saves us a bit of gas/complexity.
2. Paves the way for allowing sends from f4 addresses.

feat: resolve addresses by looking in the state-tree

---

fvm/Cargo.toml
fvm/src/executor/default.rs
fvm/src/kernel/default.rs
shared/Cargo.toml
shared/src/crypto/signature.rs

There are two commits, we can decide to drop the second:
1. Commit 1 allows sending from an f4 embryo.
2. Commit 2 allows validating messages from an f4 embryo. However, this likely requires https://github.com/filecoin-project/FIPs/discussions/497 to actually be useful. We can pull this off as a last minute hack, but it's not great.

Hack: allow f4-embryos to be used as accounts

---

sdk/src/actor.rs
sdk/src/lib.rs

This constant is used to size address buffers. The `actor::lookup_address` syscall was failing with f4 addresses with an "address output buffer is too small" error.

sdk: fix maximum address length.

---

fvm/src/executor/default.rs
shared/src/crypto/signature.rs
testing/integration/Cargo.toml
testing/integration/src/builtin.rs
testing/integration/src/tester.rs
testing/integration/tests/bundles/mod.rs
testing/integration/tests/embryo_sender_test.rs

These were not caught in CI because we don't build with `--all-features` due to that triggering CUDA dependencies. Need to figure out a solution.
Also adds a test, even though it can only be triggered manually now by calling `cargo test` with `--feature f4-as-account`.

fix compile issues with f4-as-account feature.

---

ipld/amt/src/amt.rs
ipld/amt/src/lib.rs
ipld/amt/src/root.rs
ipld/amt/tests/amt_tests.rs

This PR adds support for serializing and deserializing amt v0 data structures, which are still used in filecoin for reading headers etc.
Fixes: #924

Add support for legacy amt v0

---

README.md
testing/conformance/README.md
testing/conformance/benches/bench_drivers.rs
testing/conformance/src/bin/perf-conformance.rs
testing/conformance/src/driver.rs
testing/conformance/src/vector.rs
testing/conformance/src/vm.rs
testing/conformance/tests/runner.rs

Resolves https://github.com/filecoin-project/ref-fvm/issues/1007 
This PR runs the `conformance` tests against https://github.com/filecoin-project/fvm-test-vectors/pull/7 which contain test vectors for NetworkVersion=15 and ActorVersion=7. 
On this particular test-vector PR, which hasn't been merged since May, we still have the specs V6 tests which have since been [removed](https://github.com/filecoin-project/fvm-test-vectors/pull/6) from `master`. However because we still have that, I added some selectors and filters to skip these. 
The PR has some enhancements and fixes to the tests:
* Added the ability to handle `VECTOR` being a subdirectory of the corpus, not just a specific test
* Added the file name as a context to failing tests and failing test setups to make it easier to identify …

MEM-1007: Reinstate tests

---

fvm/src/call_manager/default.rs
fvm/src/call_manager/limiter.rs
fvm/src/call_manager/mod.rs
fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/machine/engine.rs
fvm/src/machine/mod.rs
fvm/tests/dummy.rs
testing/conformance/src/vm.rs
testing/integration/src/tester.rs
testing/integration/tests/main.rs

Part of https://github.com/filecoin-project/ref-fvm/issues/1009 
The PR adds an `ExecResourceLimiter` that puts limits on the memory consumption allowed during execution in two ways:
1. `max_inst_memory_bytes` limits the amount of memory any single message _send_ can use
2. `max_exec_memory_bytes` limits the amount of memory that can be used throughout the whole execution. _This is wrong, see notes._
The limiter is created at the beginning of the message execution and used for everything as long as the `CallManager` is alive. Both `CallManager` and `Kernel` got a new `limiter_mut` method to return the limiter where they have to be handed over to wasmtime.
On the 2nd point it turned out that the maximum limit should have been applied on the call stack _at any given time_, not overall, ie. …

MEM-1009: Use a ResourceLimiter

---

fvm/src/lib.rs
fvm/src/state_tree.rs
fvm/tests/dummy.rs
shared/src/state/mod.rs
testing/integration/examples/integration.rs
testing/integration/tests/address_test.rs
testing/integration/tests/embryo_sender_test.rs
testing/integration/tests/fil_integer_overflow.rs
testing/integration/tests/fil_syscall.rs
testing/integration/tests/main.rs

Really, we have changed the data structure for ActorState, so we must bump the state tree version as well and we can't parse anything else.

state tree v5

---

fvm/Cargo.toml

We don't currently use them in the builtin actors, but we should.

fix: enable instrumentation of sign extension instruction

---

fvm/src/call_manager/default.rs
fvm/src/machine/engine.rs
fvm/src/machine/limiter.rs
fvm/src/syscalls/mod.rs
fvm/tests/dummy.rs
testing/conformance/src/vm.rs

Closes https://github.com/filecoin-project/ref-fvm/issues/1009 
Fixes the `ExecResourceLimiter` to apply the `max_exec_memory_bytes` limit on the call stack itself, restoring the available memory limits as the stack depth goes back towards zero, rather than the whole execution; the latter is only limited by the available gas.
Initially I tried "deriving" a new limiter so that we can just drop it when the call stack is finished. It doesn't seem that simple though, because the new kernel is created from the `CallManager`, so the limiter inside the `CallManager` must reflect the current total memory in the call stack. Deriving something that points at this instance and gets dropped together with the `Kernel` would require some shared internal memory between the (many) limiters. That seemed …

MEM-1009: Apply max memory on call stack, not execution

---

fvm/src/gas/price_list.rs
fvm/src/machine/engine.rs
fvm/src/syscalls/mod.rs

Fixes https://github.com/filecoin-project/ref-fvm/issues/1055
The PR adds a `charge_for_init` function to the `syscall` package (similar to `charge_for_exec`) which is called from `Engine::get_instance` to charge gas for the minimum amount of memory the module will require to start. 
This simplified `charge_for_exec` as well because it doesn't have to worry about the discount we give for the first page any more, since that is never accounted for in the wasm gas. I verified this by running a test and logging calls to `ExecResourceLimiter::memory_growing`:
```
MEMORY GROWING current=0 desired=1179648 maximum=Some(4294967296)
MEMORY GROWING current=1179648 desired=1245184 maximum=Some(536870912)
MEMORY GROWING current=1245184 desired=1310720 maximum=Some(536870912)
```
The first call is …

MEM-1055: Charge gas for initializing memory

---

ipld/hamt/src/hash_bits.rs

Fixes `HashBits::next` returned an error when we have consumed all but the last bits of a key, and what's left is less than the bit width. The PR changes it so that it consumes whatever is left, and only fails on the next call when the whole key has already been consumed. 
The following table shows width of the last chunk of the 32 byte long hash with various bit widths:
| bit_width | last nibble width |
|-|-|
8 | 8 
7 | 4 
6 | 4
5 | 1
4 | 4
3 | 1
2 | 2
1 | 1
The reason this probably hasn't come up before is that with hashing it's very unlikely that to keys share all but their last bits. However with the hybrid hashing+offset based strategy used by Solidity this is exactly what happens for arrays, and then some bit widths work while others don't.

FIX: HashBits::next when bit_width does not divide 256 and the full hash is consumed

---

fvm/CHANGELOG.md
fvm/Cargo.toml
ipld/hamt/CHANGELOG.md
ipld/hamt/Cargo.toml
sdk/CHANGELOG.md
sdk/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/integration/tests/fil-address-actor/Cargo.toml
testing/integration/tests/fil-hello-world-actor/Cargo.toml
testing/integration/tests/fil-integer-overflow-actor/Cargo.toml
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-malformed-syscall-actor/Cargo.toml
testing/integration/tests/fil-stack-overflow-actor/Cargo.toml
testing/integration/tests/fil-syscall-actor/Cargo.toml

- fvm => 3.0.0-alpha.7
- fvm_shared => 3.0.0-alpha.10
- fvm_sdk => 3.0.0-alpha.10
- fvm_ipld_hamt => 0.6.1

release fvm crates; versions below (+).

---

ipld/hamt/fuzz/fuzz_targets/extensions.rs
ipld/hamt/src/lib.rs
ipld/hamt/src/node.rs
ipld/hamt/src/pointer.rs
ipld/hamt/tests/hamt_tests.rs

part of https://github.com/filecoin-project/ref-fvm/issues/892 
Adds an option to the HAMT `Config` to keep the first N levels of the tree free of key-value pairs, reserved for routing links. The motivation is to reduce the write amplification we observed in https://github.com/filecoin-project/ref-fvm/issues/888
This should help with the `mapping` type that Solidity puts in random keys in the HAMT which weight down on everything by saturating the root node and then its children with data. 
Unfortunately we also want the top level variables to be easily accessible, they would be okayish to be in the root node (unless perhaps if they are fixed size arrays stored inline). This would be an awkward setting for the HAMT to have, though. Also if there are enough top level variables their keys …

EVM-892: Add min_data_depth option.

---

fvm/src/blockstore/buffered.rs

Resetting the buffer was never advertised as a behaviour of this method.
This makes it possible to call flush multiple times to selectively flush roots during its lifetime. Selective flushes are used to flush the event AMTs as they are being produced.

fix: BufferedBlockstore#flush should not reset the write buffer.

---

Cargo.toml
fvm/src/blockstore/buffered.rs

Upstream broke the world by yanking a version.

fix: patch funty for now

---

fvm/src/syscalls/mod.rs
fvm/src/syscalls/network.rs
sdk/src/network.rs
shared/src/sys/out.rs

Now that we have a network context, there's no need to have separate syscalls for these. We've kept a separate syscall for the circulating supply, because we'd like to restrict that to special actors...
Also, rename network_curr_epoch to just epoch.

refactor: move base-fee & timestamp into the network context

---

Cargo.lock
fvm/CHANGELOG.md
fvm/Cargo.toml
sdk/CHANGELOG.md
sdk/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/integration/tests/fil-address-actor/Cargo.toml
testing/integration/tests/fil-events-actor/Cargo.toml
testing/integration/tests/fil-hello-world-actor/Cargo.toml
testing/integration/tests/fil-integer-overflow-actor/Cargo.toml
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-malformed-syscall-actor/Cargo.toml
testing/integration/tests/fil-stack-overflow-actor/Cargo.toml
testing/integration/tests/fil-syscall-actor/Cargo.toml

This release includes a breaking change to the message/network context syscalls.

chore: release sdk, fvm, shared, and integration tests

---

Cargo.lock
fvm/Cargo.toml
fvm/src/call_manager/default.rs

Specifically, OOM and TRAPs during instantiation are _not_ fatal.
fixes #1102

fix: avoid treating some instantiation errors as fatal

---

fvm/src/executor/default.rs
fvm/src/externs/mod.rs
fvm/src/kernel/default.rs
fvm/src/lib.rs
fvm/src/machine/default.rs
fvm/src/machine/mod.rs
fvm/tests/dummy.rs
testing/conformance/src/externs.rs
testing/conformance/src/vm.rs
testing/integration/src/dummy.rs
testing/integration/src/tester.rs

So, @vyzo was right. This is the best way to do this.
It also means we don't need the whole network context thing.
part of https://github.com/filecoin-project/ref-fvm/issues/933
fixes https://github.com/filecoin-project/ref-fvm/issues/913 (by getting rid of the NetworkContext).

feat: use externs for tipset cid lookups

---

fvm/CHANGELOG.md
fvm/src/call_manager/default.rs
fvm/src/call_manager/mod.rs
fvm/src/executor/default.rs
fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/syscalls/actor.rs
fvm/src/syscalls/mod.rs
fvm/tests/dummy.rs
sdk/CHANGELOG.md
sdk/src/actor.rs
sdk/src/sys/actor.rs
testing/conformance/src/vm.rs

1. Use the origin as specified in the top-level message without trying to resolve it. This is necessary for account abstraction because, per-finality, we should use the _stable_ address (f1-f3) to compute new `f2` addresses. Unfortunately, we have no way to lookup an actor's "stable" (`f2`) address. Unfortunately, we can't just use the actor's `f4` address because not all abstract accounts will have one (thinking beyond the EVM here).
2. Replace the `new_actor_address` syscall with `next_actor_address`. We now update the "num actors created" _after_ creating the next actor (see https://github.com/filecoin-project/ref-fvm/issues/941).
All these changes are a bit intertwined because I didn't want to expose a new `origin_address` method on the CallManager, only to remove it later.
fixes #941

feat: refactor actor creation logic

---

fvm/src/call_manager/default.rs
fvm/src/call_manager/mod.rs
fvm/src/gas/mod.rs
fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/syscalls/network.rs
fvm/src/syscalls/vm.rs
fvm/tests/default_kernel/ops.rs
fvm/tests/dummy.rs
testing/conformance/src/vm.rs

Remove the per-item functions and collapse them into single "context" functions. This will let us:
1. Enforce restrictions necessary for account abstraction.
2. Correctly charge gas.
Also: move the gas premium into the call manager and out of the gas tracker. The gas tracker is for tracking gas available/spent and doesn't care about price.

refactor: merge "context" kernel methods

---

fvm/src/call_manager/default.rs
fvm/src/call_manager/mod.rs
fvm/src/executor/default.rs
fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/syscalls/error.rs
fvm/src/syscalls/mod.rs
fvm/src/syscalls/send.rs
fvm/src/syscalls/vm.rs
fvm/src/trace/mod.rs
sdk/src/sys/vm.rs
sdk/src/vm.rs
testing/integration/tests/main.rs

Implements generalized aborts as exits, which can carry data and also allow non-local returns (exit(0)).
Closes #986.

Generalize Abort to Exit with data

---

ipld/amt/src/amt.rs
ipld/amt/tests/amt_tests.rs

This works because we never have to read or deserialize when creating an AMT from scratch.
Most of the code changes are actually just re-arranging the implementation into three sections:
1. The first that has no type restrictions (useful for avoiding type bounds where we don't need them).
2. The second for the newly changed function that doesn't have the `V: DeserializeOwned` requirement.
3. The third for everything else.

feat: allow constructing an AMT from an iterator or borrowed values.

---

Cargo.lock
testing/integration/Cargo.toml
testing/integration/examples/integration.rs
testing/integration/tests/fil_syscall.rs
testing/integration/tests/main.rs

`wat` is built and maintained by the bytecode alliance, and is pure rust. Importantly, it doesn't invoke cmake.

feat: replace wat2wasm with the pure-rust wat crate

---

fvm/src/syscalls/vm.rs

Even if we pass it an invalid message, we shouldn't fail.

fix: make sure exit never fails

---

fvm/src/call_manager/default.rs
fvm/src/executor/default.rs
fvm/src/init_actor.rs
fvm/src/kernel/default.rs
fvm/src/machine/default.rs
fvm/src/machine/mod.rs
fvm/src/state_tree.rs
fvm/src/system_actor.rs
testing/conformance/benches/bench_conformance_overhead.rs
testing/conformance/src/driver.rs
testing/integration/src/builtin.rs
testing/integration/src/tester.rs
testing/integration/tests/embryo_sender_test.rs

This is in preparation for "readonly" mode. Basically, I'm:
- Changing all the actor get/set/modify methods to take actor IDs (removing any internal resolution). That way the caller has to handle all of the error cases and can chose what to do.
- Avoid marking failures in some state-tree modification functions as "fatal errors". This will let us enforce the readonly constraint at a very low-level (inside the state-tree).
Why didn't we do this in the first place? Basically, legacy code inherited from Forest (likely trying to be compatible with the lotus VM).

feat: use actor IDs and remove some fatal errors

---

fvm/src/gas/price_list.rs
testing/integration/tests/main.rs

Part of https://github.com/filecoin-project/ref-fvm/issues/1072
Also fixes the underflow reported in https://github.com/filecoin-project/Fuzzing-FVM/issues/38

fix: charge for the first page of gas

---

fvm/src/machine/mod.rs
testing/integration/tests/main.rs

see https://github.com/filecoin-project/ref-fvm/issues/369#issuecomment-1329573938
This allows us to hit the maximum recursion limit even if we have 1MiB stacks (plus some other memory).

fix: raise the maximum memory limit from 512MiB to 2GiB

---

shared/src/error/mod.rs

The grammar was bugging me ("indicates a" instead of "indicates that a"), so I just removed "indicates" and cleaned up the wording a bit.

fix: exit code wording

---

Cargo.lock
fvm/src/call_manager/default.rs
fvm/src/call_manager/mod.rs
fvm/src/executor/default.rs
fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/state_tree.rs
fvm/src/syscalls/send.rs
fvm/tests/dummy.rs
sdk/src/error.rs
sdk/src/send.rs
sdk/src/sself.rs
sdk/src/sys/send.rs
sdk/src/vm.rs
shared/src/error/mod.rs
shared/src/sys/mod.rs
shared/src/sys/out.rs
testing/conformance/src/vm.rs
testing/integration/Cargo.toml
testing/integration/tests/fil-readonly-actor/Cargo.toml
testing/integration/tests/fil-readonly-actor/build.rs
testing/integration/tests/fil-readonly-actor/src/lib.rs
testing/integration/tests/readonly_test.rs

Adds a read-only mode for sends.
1. Adds "flags" to the sends syscall. We can extend it in the future to support additional flags.
2. Adds the concept of "read-only" layers to both the event accumulator and the state tree. This means we can track the read-only state at the _lowest_ level.
The general approach here is to reject mutations _at_ the mutation site instead of early. That means we'll charge gas first. The alternative would be to check up-front at the top of the syscall, but that's non-trivial because a send may automatically create an actor in some cases.

feat: add a read-only mode to sends

---

fvm/src/kernel/default.rs
sdk/src/message.rs
shared/src/sys/out.rs
testing/integration/tests/fil-gaslimit-actor/src/actor.rs
testing/integration/tests/fil-syscall-actor/src/actor.rs

We don't actually need this, and users should use `gas::available`.
fixes #1168

feat: remove the gas limit from the context

---

sdk/src/send.rs
testing/integration/tests/fil-address-actor/src/actor.rs
testing/integration/tests/fil-events-actor/src/actor.rs
testing/integration/tests/fil-gaslimit-actor/src/actor.rs
testing/integration/tests/fil-readonly-actor/src/lib.rs
testing/integration/tests/fil-stack-overflow-actor/src/actor.rs

Remove send_read_only. The goal was to avoid breaking changes, but we needed to break things anyways to thread the gas through.

refactor: make send take all arguments

---

fvm/src/machine/engine.rs

Otherwise, some Wasm modules will balloon in size when compiled.

feat: disable memory_init_cow

---

fvm/src/kernel/default.rs

i dont known why, but in sdk,got error when build fvm dependency, but build   ref-fvm successfully
```
error[E0282]: type annotations needed
--> /Users/lijunlong/.cargo/git/checkouts/ref-fvm-618db269bf84f1ac/8b4f157/fvm/src/kernel/default.rs:864:87
|
864 |             .map_err(|_| syscall_error!(IllegalArgument; "failed to load actor code").into())?;
|                                                                                       ^^^^
|
error[E0283]: type annotations needed
--> /Users/lijunlong/.cargo/git/checkouts/ref-fvm-618db269bf84f1ac/8b4f157/fvm/src/kernel/default.rs:864:87
|
864 |             .map_err(|_| syscall_error!(IllegalArgument; "failed to load actor code").into())?;
|                                                                                       ^^^^
|
note: …
```

feat: remove into in install_actor

---

ipld/hamt/CHANGELOG.md
ipld/hamt/fuzz/Cargo.toml
ipld/hamt/fuzz/fuzz_targets/extensions.rs
ipld/hamt/src/hamt.rs
ipld/hamt/src/lib.rs
ipld/hamt/src/node.rs
ipld/hamt/src/pointer.rs
ipld/hamt/tests/hamt_tests.rs

This PR contains some refactorings on the HAMT tests and the `min_data_depth` option from https://github.com/filecoin-project/ref-fvm/pull/935 which is the only one identified as a common good that we want to keep independent of the EVM footprint optimisation, which we'll carry on with a separate data structure.

EVM-892: HAMT min_data_depth option

---

fvm/src/syscalls/send.rs
sdk/src/send.rs

fix: use 0 to mean 0, u64::MAX to mean "all the gas"

---

Cargo.lock
fvm/CHANGELOG.md
fvm/Cargo.toml
sdk/CHANGELOG.md
sdk/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/integration/tests/fil-address-actor/Cargo.toml
testing/integration/tests/fil-events-actor/Cargo.toml
testing/integration/tests/fil-exit-data-actor/Cargo.toml
testing/integration/tests/fil-gaslimit-actor/Cargo.toml
testing/integration/tests/fil-hello-world-actor/Cargo.toml
testing/integration/tests/fil-integer-overflow-actor/Cargo.toml
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-malformed-syscall-actor/Cargo.toml
testing/integration/tests/fil-readonly-actor/Cargo.toml
testing/integration/tests/fil-stack-overflow-actor/Cargo.toml
testing/integration/tests/fil-syscall-actor/Cargo.toml

This is a small change to count "0" gas as actually 0, instead of infinite. At the same time, we now pass u64::MAX for "all gas".

chore: release fvm & sdk

---

fvm/src/call_manager/default.rs
fvm/src/call_manager/mod.rs
fvm/src/engine.rs
fvm/src/executor/default.rs
fvm/src/lib.rs
fvm/src/machine/boxed.rs
fvm/src/machine/default.rs
fvm/src/machine/mod.rs
fvm/tests/dummy.rs
testing/conformance/benches/bench_conformance.rs
testing/conformance/benches/bench_conformance_overhead.rs
testing/conformance/benches/bench_drivers.rs
testing/conformance/src/driver.rs
testing/conformance/src/vm.rs
testing/integration/src/tester.rs

Now that we're using the pooling allocator in wasmtime, we have to be careful about sharing a single engine between multiple concurrent message executions. Otherwise, we could run out of wasm "instances" and fail execution (e.g., if the user is validating two blocks in parallel).
To handle this, I've:
1. Turned the engine into an "engine pool" where we allocate `concurrency * call_depth` instances.
2. Put the EnginePool inside the Executor.
3. Put the Engine itself inside the CallManager.
That way, we "acquire" an Engine every time we handle a new message, and release the engine when we're done.
Unfortunately, putting the engine on the _machine_ didn't really make sense anymore, because the engine's lifetime is tied to a specific call and returned to the pool afterwards.
We could have …

refactor: extract the engine from the machine and make it a pool

---

fvm/src/gas/price_list.rs

I'm not actually charging anything right now, but this lets us charge for:
1. Memory copying.
2. Memory "filling" (where I'm treating all memory expansion as "filling").
fixes #1075

feat: add charging for all memory copy/init operations

---

fvm/src/machine/mod.rs
sdk/src/network.rs
shared/src/chainid/mod.rs
shared/src/lib.rs
testing/integration/tests/fil-syscall-actor/src/actor.rs
testing/integration/tests/main.rs

#1230 
#1231 
This can't be in FVM if we want built-in actors to actually reference the type (which it doesn't _have_ to, but IMO it should).

FVM: Move ChainID to shared

---

ipld/encoding/src/cbor.rs
ipld/encoding/src/errors.rs
ipld/encoding/src/ipld_block.rs
ipld/encoding/src/lib.rs
ipld/encoding/src/raw.rs
sdk/src/message.rs
sdk/src/send.rs
testing/integration/tests/fil-integer-overflow-actor/src/lib.rs
testing/integration/tests/fil-stack-overflow-actor/src/lib.rs

IpldBlock supports multiple codecs, including IPLD_RAW.
Serializing byte vectors will correctly serialize anything that serializes to "raw bytes". However, it _won't_ serialize "byte lists", so `Vec<u8>` and `[u8]` won't work. But that shouldn't be an issue in practice.
Users _should_ serialize to/from `ByteBuf`.

v2: Change SDK::send's params to take new type IpldBlock

---

fvm/Cargo.toml
ipld/encoding/CHANGELOG.md
ipld/encoding/Cargo.toml
sdk/CHANGELOG.md
sdk/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/integration/tests/fil-hello-world-actor/Cargo.toml
testing/integration/tests/fil-integer-overflow-actor/Cargo.toml
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-malformed-syscall-actor/Cargo.toml
testing/integration/tests/fil-stack-overflow-actor/Cargo.toml
testing/integration/tests/fil-syscall-actor/Cargo.toml

@Stebalien / reviewer: please confirm that ipld_encoding can be a patch release (only _adding_ a type), while SDK is a minor release.

Release SDK 2.1.0, ipld_encoding 0.2.3

---

.github/workflows/ci.yml
sdk/Cargo.toml
sdk/src/debug.rs
sdk/src/sys/mod.rs
testing/integration/Cargo.toml

1. Avoid cases where we need to specify default features (except opencl in the fvm crate).
2. Disable default features in CI.
This lets us _reliably_ disable OpenCL. Otherwise, we need OpenCL to build, which isn't usually present in CI.
This also removes the "debug" feature from the SDK, because we always enable that anyways.

fix: avoid default features and disable in CI

---

ipld/amt/src/amt.rs
ipld/amt/tests/amt_tests.rs

Closes https://github.com/filecoin-project/ref-fvm/issues/915
The PR adds a `flushed_cid` to the `Amt` data structure so that we can skip writing to the block store when `flush()` is called if nothing changed since the data was loaded or last flushed. This should save a little gas when `Amt` is used in smart contracts.

OPT-915: Amt::flush short circuit if nothing changed.

---

ipld/hamt/fuzz/fuzz_targets/extensions.rs
ipld/hamt/src/lib.rs
ipld/hamt/src/node.rs
ipld/hamt/src/pointer.rs
ipld/hamt/tests/hamt_tests.rs

Related to https://github.com/filecoin-project/ref-fvm/issues/892 
The PR moves the currently constant `MAX_ARRAY_WIDTH` into the `hamt::Config`. 
We realized in https://github.com/filecoin-project/builtin-actors/pull/926 that the `min_data_depth` option added in https://github.com/filecoin-project/ref-fvm/pull/1088 is only really useful if the size of the `KeyValuePair`s are much larger than the pointers they are replaced with, or when we know for sure that there will be enough items inserted that they will result in a deep HAMT, and when we only need to access a few entries at a time. In these cases we can skip having to read/write an overweight root node every time.
For the EVM this wasn't the case, because the keys are the values are both 32 bytes, which is comparable to a CID. In …

OPT-892: Hamt max array width made configurable.

---

fvm/src/call_manager/default.rs
fvm/src/machine/manifest.rs

The singletons now generally assert that they've been created by the "system" actor.
fixes #1295

chore: remove "singleton" check

---

fvm/src/call_manager/default.rs
fvm/src/call_manager/mod.rs
fvm/src/executor/default.rs
fvm/src/gas/price_list.rs
fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/state_tree.rs
fvm/src/syscalls/actor.rs
fvm/src/syscalls/mod.rs
fvm/tests/dummy.rs
sdk/src/actor.rs
sdk/src/sys/actor.rs
testing/conformance/src/vm.rs
testing/integration/src/builtin.rs
testing/integration/src/tester.rs
testing/integration/tests/embryo_sender_test.rs
testing/integration/tests/fil-address-actor/src/actor.rs
testing/integration/tests/fil-syscall-actor/src/actor.rs

This:
- Simplifies the FIP (we can add it to FIP0048 and be done).
- Simplifies the concepts (predictable was nasty).
- Allows us to eventually just assign f4 addresses to everything.
There are three parts to this change:
1. Restore the logic for resolving key addresses when verifying signatures.
2. Mass rename of predictable -> delegated.
3. No longer store f1/f3 in this field.
fixes #1289

feat: only store delegated addresses in the state-tree

---

fvm/src/call_manager/default.rs
testing/integration/tests/fil-address-actor/src/actor.rs

This isn't strictly necessary, since there _shouldn't_ be anything wrong with deploying embryos to other ID namespaces. However, only embryos in the EAM's namespace can be deployed at today, so we might as well restrict this for now and not have to think about it.

CallManager: Restrict embryo creation to the EAM's namespace

---

Cargo.lock
ipld/encoding/src/cbor.rs
ipld/encoding/src/errors.rs
ipld/encoding/src/ipld_block.rs
ipld/encoding/src/lib.rs
ipld/encoding/src/raw.rs
sdk/src/message.rs
sdk/src/send.rs
testing/calibration/contract/fil-gas-calibration-actor/src/lib.rs
testing/integration/tests/fil-address-actor/src/actor.rs
testing/integration/tests/fil-events-actor/src/actor.rs
testing/integration/tests/fil-gaslimit-actor/src/actor.rs
testing/integration/tests/fil-integer-overflow-actor/src/actor/mod.rs
testing/integration/tests/fil-readonly-actor/src/lib.rs
testing/integration/tests/fil-stack-overflow-actor/src/actor.rs

Towards #987, but doesn't close it.
Introduces a new IpldBlock type that can support various codecs (currently DAG_CBOR and IPLD_RAW), and switches the SDK::send method to use `Option<IpldBlock>` for params.

v3: Change SDK::send's params to take new type IpldBlock

---

ipld/encoding/src/ipld_block.rs
testing/integration/tests/fil-events-actor/src/actor.rs

This matches the behaviour introduced on the v2 FVM in #1199

fix: IpldBlock::serialize_cbor should return an Option

---

Cargo.lock
fvm/Cargo.toml
ipld/encoding/CHANGELOG.md
ipld/encoding/Cargo.toml
testing/calibration/Cargo.toml
testing/calibration/contract/fil-gas-calibration-actor/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/integration/tests/fil-address-actor/Cargo.toml
testing/integration/tests/fil-events-actor/Cargo.toml
testing/integration/tests/fil-exit-data-actor/Cargo.toml
testing/integration/tests/fil-gaslimit-actor/Cargo.toml
testing/integration/tests/fil-integer-overflow-actor/Cargo.toml
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-readonly-actor/Cargo.toml
testing/integration/tests/fil-syscall-actor/Cargo.toml

The only change is a tweak of the behaviour of `IpldBlock::serialize_cbor` to return `Option<IpldBlock>` instead of `IpldBlock`

Release ipld_encoding 0.3.2

---

fvm/src/state_tree.rs

This will let us charge the right amount for updating state. Otherwise, we end up making changes to the state-tree even if we only _read_ some actor's state.
fixes #120

Split the "read" cache from the "write" cache in the state-tree

---

fvm/src/executor/default.rs

This fixes a bug reported by @raulk where EthAccounts weren't having their nonce and balances updated at creation.

Executor: fix: use correct sender state for account abstraction

---

fvm/src/gas/charge.rs
fvm/src/gas/price_list.rs
fvm/src/kernel/default.rs
fvm/tests/default_kernel/ops.rs
testing/conformance/src/tracing.rs

1. Remove the old gas schedules. We don't support these releases and we don't need to try to maintain compatibility.
2. Use ScalingCost everywhere to make things simpler.
3. Add clear TODOs for gas prices that need to be figured out.
4. Try to clearly split up operations in a way that should be easier to measure.
5. Rename the "storage gas" field on gas charges to "other gas", and move all charges that aren't charging for _immediate_ computation. This makes benchmarking easier. Includes:
- Deferred operations (e.g., flush).
- Memory retention
- Storage
The following changes have been made since M1. This includes reverting some of the changes that are currently on master.
- Secp256k1 signature verification has gained a new 10gas/byte cost to reflect the cost of hashing (blake2b).
- BLS …

refactor: update the gas schedule

---

fvm/src/gas/price_list.rs

We now explicitly charge for individual instructions, and reject unsupported ones.
This doesn't (confirmed with fvm-bench) change the actual _costs_ of any instructions (yet).

Explicit gas charges for different instruction types (take 2)

---

fvm/src/gas/price_list.rs

Ideally we'd have a constant somewhere for this, but we'll need to think a bit more about the structure here.

feat: charge 0.4gas/byte for memory copy and initialization

---

fvm/src/account_actor.rs
fvm/src/init_actor.rs
fvm/src/syscalls/context.rs
fvm/src/system_actor.rs
ipld/encoding/src/cbor.rs
sdk/src/crypto.rs
shared/src/address/mod.rs
shared/src/crypto/signature.rs
shared/src/event/mod.rs
shared/src/message.rs
shared/src/piece/mod.rs
shared/src/receipt.rs
shared/src/sector/post.rs
shared/src/sector/seal.rs
shared/src/smooth/alpha_beta_filter.rs
shared/src/state/mod.rs
shared/tests/address_test.rs
testing/conformance/benches/bench_conformance_overhead.rs
testing/conformance/benches/bench_drivers.rs
testing/conformance/src/bin/perf-conformance.rs
testing/conformance/src/driver.rs
testing/integration/tests/fil-events-actor/src/actor.rs

This "convenience" trait in the shared libraries introduced additional coupling between actors and FVM libraries, e.g. where an actor object that didn't provide the empty `impl Cbor` block would be unusable in some places.
It's not that convenient, since removing it gives a nice net reduction in code.
The built-in actors no longer use this as of https://github.com/filecoin-project/builtin-actors/pull/960

Remove the Cbor trait and its uses

---

fvm/src/kernel/default.rs
sdk/src/crypto.rs
sdk/src/sys/crypto.rs

This change doesn't require a FIP because the builtin actors won't call this syscall with anything but a key address.
fixes #1228

fix: remove support for non-key addresses from verify_signature

---

fvm/src/syscalls/event.rs
testing/integration/tests/events_test.rs

Also moves the setup logic to a helper method.

test: events: add a test case for out-of-gas.

---

fvm/src/gas/charge.rs
fvm/src/gas/price_list.rs

This change makes the block "read" charge more accurate.
It also moves all the "extern" charges to the "other" gas field so we can keep benchmarking locally. In the future, we'll likely want four fields to split this into multiple fields, but not now.
part of #1264

feat: fix block read charges

---

fvm/src/state_tree.rs

Instead of keeping true state "layers", we now keep an undo history.
1. When opening a new transaction, we record the current undo history height for both the resolve and state cache.
2. On abort, we walk the undo history backwards, undoing any changes.
This is `O(changes)` on revert, but that's fine. The cost of a potential revert can be charged when the change is made in the first place.
This is strictly better than the current situation where we spend `O(changes)` on every commit, which turns into `O(changes * call_depth)`.
Specifically:
1. Commits are O(1).
2. Actor Insertions/Deletions are O(1).
3. Actor address/state are O(1).
4. Reverts are O(N) in the amount of history being reverted.
I've also removed the `StateSnapshots` abstraction as it was just getting in the way.
fixes #1343

feat: rewrite the state snapshot system to have O(1) lookups

---

fvm/src/kernel/default.rs
fvm/src/syscalls/actor.rs
sdk/src/sys/actor.rs
testing/integration/tests/fil-syscall-actor/src/actor.rs

The second half of #949. Found by @ZenGround0 in #1378
fixes #1378

fix: return NotFound from balance_of

---

fvm/src/call_manager/default.rs
fvm/src/engine.rs
fvm/src/kernel/mod.rs
fvm/src/machine/default.rs
fvm/src/machine/limiter.rs
fvm/src/machine/mod.rs
fvm/src/syscalls/mod.rs
fvm/tests/dummy.rs
testing/conformance/src/vm.rs
testing/integration/tests/main.rs

Motivation:
1. Explicitly limit table memory. We shouldn't be growing tables, but it's nice to have this check in place.
2. Pave the way for explicitly limiting block memory. We still need to _benchmark_ maximum blockstore memory before we can actually enable a limit, but I'd like to get _a_ limit into M2.1 if possible (instead of relying on gas).
Changes:
First, this refactors memory limits to remove the per-instance limits from the limiter itself (this is enforced by wasmtime) and instead track a global/shared "memory" limit. It then applies this to tables.
Second, this patch removes wasmtime interfaces from the limiter, instead implementing a wrapper to adapt to wasmtime's expected interface. I generally try to avoid exposing wasmtime types.
Finally, this fixes a small bug in the test …

feat: refactor memory limits and apply to tables

---

Cargo.lock
ipld/kamt/Cargo.toml
ipld/kamt/src/ext.rs
ipld/kamt/src/pointer.rs

We were using the "struct" (json-like) representation instead of the tuple representation, and we were encoding the extension as a list of bytes (numbers) instead of as a byte-string.
This version:
1. Simplifies the serialization/deserialization logic. We had all the IPLD stuff to because we didn't have a tag. Now that we have a tag, we can use CBOR's built-in support for it.
2. Encodes links as a single tuple of CID, length, and pointer.
Unfortunately, it I couldn't find a simple way to _entirely_ rely on the deriving logic, but I've made it do most of the work.
I'm inlining the extension into the link to save a byte in the encoding.
fixes #1356

KAMT: fix serialization/deserialization

---

fvm/src/call_manager/default.rs
fvm/src/call_manager/mod.rs
fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/trace/mod.rs
fvm/tests/dummy.rs
testing/conformance/src/vm.rs

I am attempting to improve instrumentation to support analysis of gas charges across spans of code. See #1397.
This PR adds a `Log` execution event to the trace format. A log event is recorded when the `log` syscall is invoked. The log event carries a single `String` message.
A string is the most basic payload to carry here, so I think the right place to start. Some structure may be encoded into strings (for subsequent offline analysis). We could consider adding some kind of key/value pair metadata, but I suggest we defer until observed usage justifies it.
Note that the GasCharge event's `name` is a `Cow<'static, str>`. I presume this is because the same literal name is expected to be used frequently and this type will lead to meaningful optimisation. I'm not sure that that's appropriate …

[v2] Add a Log execution event, created with the log syscall

---

fvm/src/call_manager/default.rs
fvm/src/syscalls/vm.rs
testing/integration/tests/fil-stack-overflow-actor/src/actor.rs

This was always supposed to be 1024, but became 1025 due to a bug in the implementation (before network launch). We're taking this opportunity to fix this long-standing bug as we change other system limits to bring them in-line with other VMs like the EVM.
(i.e., this will require a one-line comment in the FIP, so we might as well do it right now).

feat: change the recursive call limit to 1024

---

fvm/src/gas/price_list.rs

TL;DR: This reduces read/write costs by 0.4.
The point of this fee is to charge at _least_ 10gas/byte. So that's what we now do. Instead of charging an additional fee, we:
1. Compute the actual per-byte "compute" fees.
2. Compute the minimum memory retention fee.
3. Apply a memory retention surcharge up to the minimum memory retention fee.
This seems complex, but the effect is simple: We're now charging 0.4 gas less per byte for reads and writes. I could have just reduced the memory retention cost by 0.4, but the new logic more accurately reflects our intentions with this fee.

feat: adjust memory retention fee

---

sdk/src/debug.rs

Well, this took a very long time to discover.
This is already fixed on master, but built-in actors are still targeting v2.
Note that even after this change I _still_ can't get logs to produce syscalls when using the v2 SDK, but I can if I install my own logger, which is good enough for now.
Related: #1397

[v2] Fix log initialisation to set max level, else all messages are discarded

---

fvm/src/kernel/default.rs
fvm/src/machine/mod.rs

Chosen to be 1MiB as that should be about 10x larger than anything in-use today.
fixes https://github.com/filecoin-project/ref-fvm/issues/1278

feat: add a basic block size limit

---

Cargo.lock
fvm/Cargo.toml
testing/calibration/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml

I'm not entirely sure if we'll be able to update beyond 2.0.2 on time without at least some fixes/features in wasmtime due to https://github.com/filecoin-project/ref-fvm/pull/1412#pullrequestreview-1247553574.
This is likely the second best thing we can do.

deps: Update wasmtime to v2.0.2

---

Cargo.lock
fvm/CHANGELOG.md
fvm/Cargo.toml
ipld/amt/CHANGELOG.md
ipld/amt/Cargo.toml
ipld/kamt/CHANGELOG.md
ipld/kamt/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml

I'm skipping the HAMT because that has some API changes and no new features.

chore: release fvm, kamt, amt

---

fvm/src/kernel/default.rs
sdk/src/network.rs
shared/src/sys/out.rs
shared/src/version/mod.rs

The enum means we'd need to extend this for every network version added. We still have constants for every _named_ network version.

feat: use a struct for network versions

---

fvm/src/call_manager/default.rs
fvm/src/engine.rs

We were implicitly converting them to "anyhow" errors, then treating them as fatal.
fixes #1486

fix: correctly return out of gas errors when instantiating

---

fvm/src/state_tree.rs

When we register a new address (e.g., when auto-creating an actor on first send), cache it.
This will be important for gas tracking.

feat: cache new addresses

---

Cargo.lock
fvm/src/kernel/default.rs

This appears to be a casualty of rust's feature unification. We should have caught this in CI, but feature unification ensured that this feature got _enabled_, so we didn't.

fix: fix build when testing isn't enabled

---

fvm/src/blockstore/buffered.rs
fvm/src/call_manager/default.rs
fvm/src/executor/default.rs
fvm/src/kernel/blocks.rs
ipld/encoding/src/ipld_block.rs
ipld/encoding/src/lib.rs
testing/integration/tests/fil-address-actor/src/actor.rs
testing/integration/tests/fil-events-actor/src/actor.rs
testing/integration/tests/fil-exit-data-actor/src/lib.rs
testing/integration/tests/fil-gaslimit-actor/src/actor.rs
testing/integration/tests/fil-integer-overflow-actor/src/actor/mod.rs
testing/integration/tests/fil-readonly-actor/src/lib.rs

FVM: Use CBOR instead of DAG_CBOR for message params

---

ipld/car/src/lib.rs
ipld/car/tests/car_file_test.rs

resolves #1522 
- Move private fn `load_car_inner` to `CarReader::read_into()`
- `load_car` and `load_car_unchecked` construct their own car readers and call `read_into`
- Add file test using CarReader directly 
Provide a way for users to perform actions/checks on car data before loading it into the store

feat: `CarReader::read_into()`

---

fvm/src/call_manager/default.rs
testing/integration/tests/fil-create-actor/src/actor.rs

Previously, this would have failed anyways when the constructor method call gets rejected (because placeholders were rejecting all calls).
However, we're changing this such that placeholders accept all calls, so we need to forbid their explicit creation here.
part of #1567.

feat: explicitly reject placeholder creation

---

Cargo.lock
fvm/CHANGELOG.md
fvm/Cargo.toml
sdk/CHANGELOG.md
sdk/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml
testing/calibration/Cargo.toml
testing/calibration/contract/fil-gas-calibration-actor/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/integration/tests/fil-address-actor/Cargo.toml
testing/integration/tests/fil-create-actor/Cargo.toml
testing/integration/tests/fil-events-actor/Cargo.toml
testing/integration/tests/fil-exit-data-actor/Cargo.toml
testing/integration/tests/fil-gaslimit-actor/Cargo.toml
testing/integration/tests/fil-hello-world-actor/Cargo.toml
testing/integration/tests/fil-integer-overflow-actor/Cargo.toml
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-malformed-syscall-actor/Cargo.toml
testing/integration/tests/fil-readonly-actor/Cargo.toml
testing/integration/tests/fil-stack-overflow-actor/Cargo.toml
testing/integration/tests/fil-syscall-actor/Cargo.toml

It's not absolutely necessary to release the SDK and shared, but might as well.

release `fvm@v3.0.0-alpha.22`, `fvm_shared@v3.0.0-alpha.18`, `fvm_sdk@v3.0.0-alpha.23`.

---

fvm/src/call_manager/default.rs
fvm/src/call_manager/mod.rs
fvm/src/executor/default.rs
fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/state_tree.rs
fvm/tests/default_kernel/mod.rs
fvm/tests/dummy.rs
testing/conformance/src/vm.rs
testing/integration/src/builtin.rs
testing/integration/src/error.rs
testing/integration/src/tester.rs
testing/integration/tests/fil-readonly-actor/src/lib.rs

This moves read-only handling from inside the state-tree to the kernel, and rejects events when read-only.
I originally put it inside the state-tree to simplify things, but it meant that that the read-only state only got applied at the end, and somewhat inconsistently:
1. Non-zero value transfers to self technically worked.
2. Gas was charged up to the first time a state-update was attempted.
Now, read-only is applied in the kernel _except_ when automatically creating new actors on send (because we don't know if it exists yet).
fixes #1628
fixes #1624

EVM: apply read-only early and reject events

---

fvm/src/call_manager/default.rs
fvm/src/call_manager/mod.rs
fvm/src/engine.rs
fvm/src/executor/default.rs
fvm/src/executor/mod.rs
fvm/src/gas/mod.rs
fvm/src/gas/outputs.rs
fvm/src/gas/price_list.rs
fvm/src/syscalls/gas.rs
fvm/src/syscalls/mod.rs
fvm/src/syscalls/send.rs
fvm/tests/default_kernel/ops.rs
fvm/tests/dummy.rs
shared/src/message.rs
shared/src/receipt.rs
testing/calibration/src/lib.rs
testing/conformance/src/tracing.rs
testing/conformance/src/vector.rs
testing/conformance/src/vm.rs
testing/integration/src/testkit/fevm.rs
tools/fvm-bench/src/fevm.rs
tools/fvm-bench/src/main.rs

This removes negative gas charges and makes gas a u64. Motivations:
1. We (finally) no longer have negative gas charges.
2. This makes it easier to reason about gas and ensure that gas never goes "backwards".
If the gas limit starts above i64::MAX _milligas_, we saturate it to i64::MAX.

feat: remove negative gas charges everywhere

---

fvm/src/kernel/default.rs

I'm currently specifying these limits in the FIP and figured this was the time to deal with the TODO.
This change forbids looking up the current tipset CID. This is technically possible in expected consensus, but may not be possible in all forms of consensus.
Fixes #1023

feat: tweak tipset lookback limits

---

fvm/tests/dummy.rs
shared/src/lib.rs

This wasn't used internally, so it wasn't caught. We now use it.

fix: use u64 for the block gas limit

---

fvm/src/executor/default.rs

We're switching between multiple FVM versions anyways, so we don't need
to support pre h-nv20 here.

chore: remove hyperspace fallback gas premium

---

fvm/src/call_manager/default.rs
fvm/src/kernel/blocks.rs
fvm/src/trace/mod.rs

Otherwise, users can't decode them. Requested by the @frrist.

feat: put blocks with codecs in the trace

---

fvm/src/syscalls/event.rs

We already enforce a limit in the kernel itself, and this one was way too low.

fix: remove event size limit

---

.gitignore
ipld/hamt/src/hamt.rs
ipld/hamt/src/node.rs
ipld/hamt/tests/hamt_tests.rs

Thank you @Stebalien for the alternative approach to the "path" based approach explored in https://github.com/filecoin-project/ref-fvm/pull/1636. This implementation uses the keys of the HAMT as a starting point. The iteration returns the next-to-be-traversed key or `None` if all values have been traversed.
One caveat of this approach is that for ranged_iteration, the keys of the HAMT must be `Clone`. 
`mut starting_cursor: Option<(HashBits, &Q)>` acts as a sentinel value. At each depth, we can use it to determine which subtree contains the starting node. Subtrees to the left of it can be skipped entirely leading to significant gas savings when those nodes would have been expanded from the Blockstore. Subtrees to the right are passed `None` indicating that all leaves must be traversed. …

Ranged HAMT iteration specified via keys

---

Cargo.lock
testing/integration/Cargo.toml
testing/integration/src/tester.rs
testing/integration/tests/bundles/mod.rs
testing/integration/tests/gasfuzz.rs

See #1667 
Note: In the very first fuzzpoint, execution fails with `SYS_SENDER_STATE_INVALID` instead of `SYS_OUT_OF_GAS`.
Not sure if this is a bug, ie execution should fail with out of gas or that's correct.
If it _is_ a bug, we should fix it and update the test to not skip the first fuzzpoint.
[EDIT: not a bug in ref-fvm, but rather in the test; see comment below]
Note2: The test exercises 96 fuzzpoints and takes 67.36s on my laptop.

test: gas stress fuzzing

---

fvm/src/state_tree.rs

The `ActorState` struct `address` field was updated to `delegated_address`, however the `Arbitrary` implementation has not been updated and still references the old `address` field that no longer exists. This change simply updates the `Arbitrary` implementation to reference the new field.

Correct address field in `ActorState` arbitrary implementation

---

ipld/amt/src/amt.rs
ipld/amt/src/node.rs
ipld/amt/tests/amt_tests.rs

Follow up to https://github.com/filecoin-project/ref-fvm/pull/1665/files applying the same principles to AMTs
Since keys on AMTs are definitely clone-able, we don't introduce any new trait bounds with the new method `Node::for_each_while_ranged`. Therefore, we could merge some code paths and have `Amt::for_each_while` call `Node::for_each_while_ranged` passing `None` for start_at and max. This of course incurs a slight performance penalty for the extra bounds checks during complete traversals.

Ranged iteration for AMTs

---

README.md

- Remove maturity roadmap. It's out of date and doesn't really serve any purpose.
- Add a link to the project website.
- Update to v3.
- Fix MSRV specification.

readme: update readme for v3

---

shared/src/error/mod.rs

Adds a standard exit code that allows actors to indicate they are not prepared to receive funds: https://github.com/filecoin-project/builtin-actors/issues/836
Example usage in builtin-actors: https://github.com/filecoin-project/builtin-actors/pull/1241

add standard exit code for non-payable functions

---

.github/workflows/ci.yml
Cargo.lock
fvm/Cargo.toml
shared/Cargo.toml
testing/calibration/Cargo.toml

This is technically a breaking change as we implement some `From` conversions for proofs in the shared library.

chore: update proofs

---

.github/workflows/ci.yml
fvm/Cargo.toml
shared/Cargo.toml

We need to do this on v3 and v2 because we can only link to one version of blstrs at a time.

chore: upgrade proofs (v2)

---

Cargo.lock
fvm/CHANGELOG.md
fvm/Cargo.toml
sdk/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml
testing/calibration/Cargo.toml
testing/calibration/contract/fil-gas-calibration-actor/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/integration/tests/fil-address-actor/Cargo.toml
testing/integration/tests/fil-create-actor/Cargo.toml
testing/integration/tests/fil-events-actor/Cargo.toml
testing/integration/tests/fil-exit-data-actor/Cargo.toml
testing/integration/tests/fil-gaslimit-actor/Cargo.toml
testing/integration/tests/fil-hello-world-actor/Cargo.toml
testing/integration/tests/fil-integer-overflow-actor/Cargo.toml
testing/integration/tests/fil-ipld-actor/Cargo.toml
testing/integration/tests/fil-malformed-syscall-actor/Cargo.toml
testing/integration/tests/fil-oom-actor/Cargo.toml
testing/integration/tests/fil-readonly-actor/Cargo.toml
testing/integration/tests/fil-stack-overflow-actor/Cargo.toml
testing/integration/tests/fil-syscall-actor/Cargo.toml

This release updates the proofs code and nothing else.

chore: release fvm & fvm_shared v3.1.0

---

Cargo.lock
sdk/src/error.rs
sdk/src/sself.rs
sdk/src/sys/ipld.rs
sdk/src/sys/sself.rs
shared/src/sys/mod.rs
shared/src/sys/out.rs
testing/integration/Cargo.toml
testing/integration/src/tester.rs
testing/integration/tests/fil-create-actor/src/actor.rs
testing/integration/tests/fil-ipld-actor/src/actor.rs
testing/integration/tests/fil-oom-actor/Cargo.toml
testing/integration/tests/fil-sself-actor/Cargo.toml
testing/integration/tests/fil-sself-actor/build.rs
testing/integration/tests/fil-sself-actor/src/actor.rs
testing/integration/tests/fil-sself-actor/src/lib.rs
testing/integration/tests/fil-syscall-actor/src/actor.rs
testing/integration/tests/main.rs

This PR adds multiple tests for our fvm sdk api to confirm they behave according to fvm sdk [docs](https://docs.rs/fvm_sdk/3.0.0-alpha.24/fvm_sdk/index.html).
Fixes: https://github.com/filecoin-project/ref-fvm/issues/585 
Note that there are still tests to be written for `actor::next_actor_address` and `crypto::verify_consensus_fault`.

Add exhaustive tests for fvm sdk api

---

fvm/src/kernel/error.rs

This makes string interpolation ("message: {some_variable}") work.
Previously, we'd apply string formatting to syscall error messages if and only if we had one or more format arguments. Now, we apply the formatting whenever the message is a string literal.
found by @fridrik01 in https://github.com/filecoin-project/ref-fvm/pull/1698

fix: correctly format syscall error messages

---

.github/workflows/ci.yml

- This causes build failures in CI (at least with sccache). We had disabled this before, but I re-enabled it when I upgraded CI.
- This is likely increasing cache sizes, and just isn't worth it.

ci: disable incremental build in CI

---

Cargo.toml

This commit overrides the development profile for our fvm_gas_calibration integration test so it strips all the generated binaries (6 in total) of debug symbols.
This reduces disk space usage by over 4GB so it should give us enough headroom for running integration tests on Gibhug (which only has 12GB SSD).
fixes: https://github.com/filecoin-project/ref-fvm/issues/1710

fix: Github integration tests failed due to running out of disk space

---

testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/test_actors/actors/fil-create-actor/Cargo.toml
testing/test_actors/actors/fil-syscall-actor/Cargo.toml

This commit removes the m2-native feature for builtin-actors which has been removed from the project.
With this PR all CI tests :heavy_check_mark: pass on master

Fix failing CI check due to missing m2-native feature in builtin-actors

---

Cargo.lock
fvm/Cargo.toml
ipld/kamt/Cargo.toml
shared/Cargo.toml
testing/common_fuzz/fuzz/Cargo.toml
testing/conformance/Cargo.toml
testing/test_actors/actors/fil-address-actor/Cargo.toml
tools/fvm-bench/Cargo.toml

Used cargo-machete tool that uses regexps against source code to find unused dependencies. Overall this removes 10 packages dependencies from Cargo.lock.
See: https://github.com/filecoin-project/ref-fvm/issues/1682

Remove unused dependencies

---

fvm/src/gas/price_list.rs
fvm/src/machine/default.rs
shared/src/version/mod.rs

feat: introduce network versions 19 and 20

---

shared/src/sector/registered_proof.rs

Seems unused across both ref-fvm and builtin-actors.

refactor: drop unused registered_seal_proof method

---

Cargo.lock
fvm/Cargo.toml
shared/Cargo.toml
shared/src/sector/registered_proof.rs

feat: FIP-0061: Add new PoSt proof types

---

Cargo.lock
testing/conformance/Cargo.toml
testing/conformance/benches/bench_conformance.rs
testing/conformance/benches/bench_conformance_overhead.rs
testing/conformance/tests/runner.rs
tools/fvm-bench/Cargo.toml

1. Update all deps. We haven't done this in a while.
2. Replace `pretty_env_logger` with `env_logger`. The former depends on a very outdated version of `env_logger` and doesn't look maintained.

chore: update and cleanup deps

---

.github/workflows/ci.yml
fvm/src/machine/default.rs

This PR adds a new CI job that runs `cargo check --features=m2-native`.
Fixes: https://github.com/filecoin-project/ref-fvm/issues/1260

Add CI check for m2-native feature

---

.github/workflows/ci.yml

This PR enables code coverage for our integration tests, it seems to bump up our coverage from to 55% to 75% ([link](https://app.codecov.io/github/filecoin-project/ref-fvm/commit/167dc3b4de9c1086e64f4f67a640e4497c2e2887))
Fixes: https://github.com/filecoin-project/ref-fvm/issues/979

Enable code coverage in integration tests

---

fvm/src/kernel/default.rs

We no longer have only one PoSt proof type corresponding to each Seal proof type. As a result, when verifying PoSts, we must supply the proof type that the proof "announces" as the public Replica's PoSt proof type. This is still secure as proofs code checks that all replicas have the same proof type, and actors code confirms that the proof type of the first PoSt is valid.
If we wanted to, we could revert this change in FVM4, at which point we'll have a one PoSt per Seal restriction again. If we _really_ wanted to, we could make this code network version dependent, and only apply this change to nv19, but I think that belongs in actors code.

feat: kernel: use specified proof type when verifying PoSts

---

testing/integration/tests/gas_calibration_test.rs
testing/test_actors/actors/fil-gas-calibration-actor/src/actor.rs

This PR enables the `on_event_evm_shapes` calibration test which was failing due to last event being too large so that total event values exceeded the limit defined in `validate_actor_event`.
Fixes: https://github.com/filecoin-project/ref-fvm/issues/1699

Fix broken calibration test

---

rust-toolchain.toml
shared/src/sector/registered_proof.rs

#1748, but on the release branch

fix: correctly convert RegisteredPoStProof type

---

fvm/src/kernel/default.rs

This resolves the inconsistent state on calibrationnet that resulted from the bug fixed in #1750. It's unfortunate to have to have a patch like this, but we can drop it when we graduate to FVM4.

feat: reject V1P1 proofs on calibrationnet before cutoff

---

shared/src/address/mod.rs
shared/src/lib.rs

The `fvm_shared` crate contains two mainnet addresses that are parsed at runtime. If `current_network()` is set to calibnet, this causes the parsing to fail. The fix is to always use the mainnet parser.

fix: parse static addresses as mainnet addresses

---

Cargo.lock
fvm/Cargo.toml
shared/Cargo.toml

Update the proofs library for the FVM v2. This will allow us to significantly shrink our binary size.

chore: update proofs (v2)

---

Cargo.lock
fvm/CHANGELOG.md
fvm/Cargo.toml
sdk/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml
testing/calibration/shared/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/test_actors/actors/fil-address-actor/Cargo.toml
testing/test_actors/actors/fil-create-actor/Cargo.toml
testing/test_actors/actors/fil-events-actor/Cargo.toml
testing/test_actors/actors/fil-exit-data-actor/Cargo.toml
testing/test_actors/actors/fil-gas-calibration-actor/Cargo.toml
testing/test_actors/actors/fil-gaslimit-actor/Cargo.toml
testing/test_actors/actors/fil-hello-world-actor/Cargo.toml
testing/test_actors/actors/fil-integer-overflow-actor/Cargo.toml
testing/test_actors/actors/fil-ipld-actor/Cargo.toml
testing/test_actors/actors/fil-malformed-syscall-actor/Cargo.toml
testing/test_actors/actors/fil-oom-actor/Cargo.toml
testing/test_actors/actors/fil-readonly-actor/Cargo.toml
testing/test_actors/actors/fil-sself-actor/Cargo.toml
testing/test_actors/actors/fil-stack-overflow-actor/Cargo.toml
testing/test_actors/actors/fil-syscall-actor/Cargo.toml

And fvm_shared@v3.3.1 (to fix some issues with addresses).
But mostly to release fvm@3.4.0 with wasmtime 8.0.1 support.

chore: release fvm 3.4.0

---

Cargo.lock
fvm/CHANGELOG.md
fvm/Cargo.toml
sdk/CHANGELOG.md
sdk/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml
testing/conformance/Cargo.toml

Along with fvm_shared 2.4 and fvm_sdk 2.3.

chore: release fvm v2.4

---

.github/workflows/ci.yml

Because this happens all to frequently.

ci: avoid failing CI when codecov fails

---

fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/syscalls/send.rs
testing/conformance/src/vm.rs

This type parameter supports a kernel to be wrapped, and have the wrapped type also be instantiated on the other side of the send. Something like this is necessary to support injecting kernel behaviour for testing.
@alexytsu and I couldn't get the TestKernel/TestCallManager pattern to work from github.com/anorth/fvm-workbench (where we need to fake out proof verification, and long term wish to be able to inject arbitrary kernel behaviour). This new scheme avoids the coupled TestCallManager and associated funky transmutation.
It's limited in that, unless we can figure out the right type constraints, a TestCallManager itself can't be wrapped, because it ignores the type parameter provided to it.
This is a partial resolution of #1779 (we're unblocked for now). But as noted there, still very …

Add type parameter to Kernel::send specifying type for receiving kernel

---

fvm/src/engine.rs
fvm/src/engine/concurrency.rs
fvm/src/engine/instance_pool.rs
fvm/src/engine/mod.rs

This introduces a resource pool component for wasm instances, which allows oversubscription and but prevents deadlocks by "locking" the pool to the first engine that brings the number of available instances below the number required to execute a single message. When the pool is locked to a specific engine, only that engine will be able to acquire more instances to ensure it can completely execute its message.
Future work:
- Memory limits. Ideally we'd apply the same concept to memory as the current approach could lead to memory exhaustion if the user isn't careful and allows too much parallelism without enough memory to back it up.
- Optimal "locking" strategy. At the moment, we "lock" the pool to an engine when we drop below the number of instances required to execute a single message. …

instance pool resource management

---

Cargo.lock
Cargo.toml
fvm/Cargo.toml
fvm/src/lib.rs
sdk/Cargo.toml
sdk/src/lib.rs
shared/Cargo.toml
shared/src/lib.rs
shared/tests/address_test.rs
testing/conformance/Cargo.toml
testing/conformance/benches/bench_conformance_overhead.rs
testing/conformance/benches/bench_drivers.rs
testing/conformance/src/lib.rs

This also dedups the blockstore/encoding crates across versions, which may simplify some stuff.
NOTE: obviously, the changes to the sdk aren't live in the network. Those are just for testing.

chore: update ipld & wasmtime crates

---

Cargo.lock
fvm/Cargo.toml
fvm/src/blockstore/buffered.rs

In preparation for reachability analysis (we're going to re-use this same code).
- Make it less generic (performance).
- Remove blocks from the write buffer as we write them to avoid duplicate writes.
- Simplify some of the checks around what is allowed. For example, I'm now allowing CBOR + Identity hash which should have been allowed previously but wasn't (we don't use it but still, it should have been allowed).
- Remove the explicit 100 byte CID length check. The `Cid` type already validates that the digest can be no longer than 64 bytes.
- Be less strict on DagCBOR validation. Counter-intuitively, being overly strict here is dangerous as it gives us more points where implementations can disagree and fork. Instead, we enforce the following rules for DAG_CBOR:
1. Blocks must have a valid …

refactor: fixup fvm IPLD flush logic

---

fvm/src/call_manager/default.rs

This came up when reviewing the gas costs: we don't need this copy.

chore: remove an unnecessary event copy

---

fvm/src/engine/mod.rs

This function is no longer deprecated.

fix: remove unecessary allow(deprecated) marker

---

fvm/src/call_manager/default.rs
fvm/src/call_manager/mod.rs
fvm/src/executor/default.rs
fvm/src/gas/price_list.rs
fvm/src/kernel/default.rs
fvm/tests/dummy.rs

(ipld reachability pre-factor)
In #1824, we'll need to charge for tracking reachable links on return. However, we'd _like_ to apply the gas limit specified by the caller so the callee can't "go over" their gas limit. That means we need a return-value charge inside the call manager instead of inside the caller (executor/kernel).
So, I figured I'd just apply a refactor that's been a long-time coming and remove the `with_transaction` dance. Instead, I put _all_ of the transaction logic into `CallManager::send`. This makes the function a bit heftier but, IMO, it's easier to reason about this way. It also removes an implementation detail (`with_transaction`) from the `CallManager` trait.

refactor: remove `with_transaction` and move "return" gas charge

---

fvm/src/init_actor.rs
ipld/hamt/src/hamt.rs
ipld/hamt/src/lib.rs
ipld/hamt/src/node.rs
ipld/hamt/src/pointer.rs
ipld/hamt/tests/hamt_tests.rs

More context: https://github.com/ChainSafe/forest/pull/3060#pullrequestreview-1503177969

Add support for HamtV0 from forest(commit hash: b622af5a6)

---

ipld/hamt/benches/hamt_benchmark.rs
ipld/hamt/src/hamt.rs
ipld/hamt/src/lib.rs
ipld/kamt/benches/kamt_benchmark.rs
ipld/kamt/src/kamt.rs
ipld/kamt/src/lib.rs

1. We don't intentionally use these anywhere.
2. We _do_ unintentionally use these where we shouldn't (https://github.com/filecoin-project/builtin-actors/issues/1346).
fixes https://github.com/filecoin-project/ref-fvm/issues/1828

chore: deprecate default bitwidths in the KAMT/AMT

---

ipld/hamt/src/hamt.rs
ipld/hamt/src/node.rs
ipld/hamt/src/pointer.rs

And "default" it to V3. Neither of these changes really matter, but I was getting thrown by the somewhat inconsistent type parameter order.
The parameter order isn't fully consistent (K/V in some cases, V/K in others) but that's a whole different issue and unrelated to recent changes.

chore(hamt): move the version parameter to the end

---

Cargo.lock
testing/integration/Cargo.toml
testing/test_actors/actors/fil-create-actor/Cargo.toml
testing/test_actors/actors/fil-syscall-actor/Cargo.toml

And disable "experimental/fvm-m2" features in tests. Otherwise, maintaining our "next" branches becomes difficult: we'd need an "experimental/fvm-m2-next" branch corresponding to the "next" branch here.... which I'm not going to do.

test: switch back to builtin-actors "master"

---

testing/test_actors/actors/fil-events-actor/src/actor.rs

Clippy is getting angry about this.

fix: use ptr::null instead of casting 0 to a pointer

---

Cargo.lock
fvm/Cargo.toml
fvm/src/externs/mod.rs
fvm/src/kernel/default.rs
fvm/src/lib.rs
fvm/tests/dummy.rs
testing/conformance/src/externs.rs
testing/conformance/src/rand.rs
testing/conformance/src/vector.rs
testing/integration/src/dummy.rs

Fixes #1277 
We currently rely on clients like Lotus to do the hashing required for drawing randomness. This PR pulls that into the kernel.
We should eventually push the work of hashing into the actor directly, which can request it over syscalls.

feat: perform randomness hashing in the kernel

---

fvm/src/call_manager/default.rs
fvm/src/gas/mod.rs
fvm/src/gas/timer.rs
fvm/src/kernel/default.rs
fvm/src/syscalls/bind.rs
fvm/src/syscalls/mod.rs

My last commit introduced a bug where I ignored the error from a call to `CallManager::charge_gas` when we _meant_ to simply ignore the gas timer, not the entire error. This bug was in the charge for `on_method_return`.
So I decided to remove the `must_use` marker from gas timers _in general_ so we didn't have to explicitly ignore the results. We generally don't care about these timers anyways.
While doing that, I found another bug in the `tipset_cid` syscall where we made the same mistake. this issue is tricker because this code is already deployed to mainnet, but we should be able to fix it without any consensus issues. Basically, right now:
1. We won't detect the out of gas condition when we should.
2. We'll fetch the requested tipset CID from state.
3. We'll return it to the user.
4. …

fix(fvm): fix (and prevent) two bugs in out of gas handling.

---

Cargo.lock
fvm/CHANGELOG.md
fvm/Cargo.toml
ipld/hamt/CHANGELOG.md
ipld/hamt/Cargo.toml
sdk/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml
testing/calibration/shared/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/test_actors/actors/fil-address-actor/Cargo.toml
testing/test_actors/actors/fil-create-actor/Cargo.toml
testing/test_actors/actors/fil-events-actor/Cargo.toml
testing/test_actors/actors/fil-exit-data-actor/Cargo.toml
testing/test_actors/actors/fil-gas-calibration-actor/Cargo.toml
testing/test_actors/actors/fil-gaslimit-actor/Cargo.toml
testing/test_actors/actors/fil-hello-world-actor/Cargo.toml
testing/test_actors/actors/fil-integer-overflow-actor/Cargo.toml
testing/test_actors/actors/fil-ipld-actor/Cargo.toml
testing/test_actors/actors/fil-malformed-syscall-actor/Cargo.toml
testing/test_actors/actors/fil-oom-actor/Cargo.toml
testing/test_actors/actors/fil-readonly-actor/Cargo.toml
testing/test_actors/actors/fil-sself-actor/Cargo.toml
testing/test_actors/actors/fil-stack-overflow-actor/Cargo.toml
testing/test_actors/actors/fil-syscall-actor/Cargo.toml

As in the title, I intend to use these releases to support nv21 development in Lotus.

chore: release fvm, fvm_shared, and HAMT crates

---

Cargo.lock
fvm/CHANGELOG.md
fvm/Cargo.toml
sdk/Cargo.toml
shared/Cargo.toml
testing/conformance/Cargo.toml

Reverts #1845, which accidentally bumped versions on a couple more crates, and correctly only releases the fvm crate.

chore: release fvm v2.6.0

---

fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/syscalls/crypto.rs
fvm/src/syscalls/mod.rs
sdk/src/crypto.rs
sdk/src/sys/crypto.rs
testing/conformance/src/vm.rs

This is unused in the builtin actors. No FIP necessary as it's unused and was restricted to the miner actor anyways.

feat: remove the verify-seal syscall

---

fvm/src/call_manager/default.rs
fvm/src/trace/mod.rs

Related: https://github.com/filecoin-project/ref-fvm/issues/1793 and https://github.com/filecoin-project/fvm-pm/issues/613
This PR adds the following fields to `ExecutionEvent` which are required to confirm to the trace api [spec](https://docs.alchemy.com/reference/trace-api):
- `gas_limit`: The gas provided by the sender
- `read_only`: Whether the call is read only or not

feat: add new fields to message trace for supporting new trace api

---

Cargo.lock
fvm/src/gas/price_list.rs
fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/syscalls/rand.rs
sdk/src/rand.rs
sdk/src/sys/rand.rs
testing/conformance/src/driver.rs
testing/conformance/src/vm.rs
testing/integration/Cargo.toml

#1847 
I might need to iron out the FVM-actors-FVM dependencies for green CI, but should be reviewable.

feat: FVM no longer draws randomness for you

---

Cargo.lock
testing/integration/src/tester.rs
testing/integration/src/testkit/fevm.rs
tools/fvm-bench/Cargo.toml
tools/fvm-bench/src/fevm.rs
tools/fvm-bench/src/main.rs

1. We were giving endowments to contracts by default, which fails with no helpful error when the contracts constructor isn't "payable".
2. Include other misc fixes/improvements found while debugging the first issue.

fix(fevm-bench): don't give contracts endowments

---

ipld/hamt/src/error.rs
ipld/hamt/src/hamt.rs
ipld/hamt/src/iter.rs
ipld/hamt/src/lib.rs
ipld/hamt/src/node.rs
ipld/hamt/tests/hamt_tests.rs

Previously, we only supported "internal" iteration with a callback. This switches to an external iterator which:
1. Allows us to make the APIs a little more composable.
2. Allows HAMT iterators to be used in rust for loops.
3. Avoids the awkward error wrapping when bubbling up errors from `for_each` calls.
Usage:
```rust
let mut hamt = Hamt::new_with_bit_width(&bs, 4);
// ...
for item in &hamt {
let (k, v) = item?; // error handling is a bit annoying.
}
// ranged iteration
for item in hamt.iter_from(start_key).take(50) {
// ...
}
```
part of https://github.com/filecoin-project/ref-fvm/issues/286

feat(hamt): implement external iteration

---

ipld/amt/Cargo.toml
ipld/amt/src/amt.rs
ipld/amt/src/value_mut.rs
ipld/amt/tests/amt_tests.rs

Remove the `go-interop` feature based on the discussion in the linked issue.
Closes https://github.com/filecoin-project/ref-fvm/issues/1856

remove go-interop from amt

---

Cargo.lock
ipld/bitfield/CHANGELOG.md
ipld/bitfield/Cargo.toml

No code changes, but this pulls in a newer version of the blockstore/encoding crates.

chore: release fvm_ipld_bitfield

---

fvm/Cargo.toml
shared/Cargo.toml

These should have been deps of the FVM all along. This removes a few dependencies from the sdk.

chore: move some deps from shared to the FVM

---

ipld/hamt/Cargo.toml
ipld/hamt/src/bitfield.rs
ipld/hamt/src/hamt.rs
ipld/hamt/src/iter.rs
ipld/hamt/src/node.rs
ipld/hamt/tests/hamt_tests.rs

This duplicates some logic we already have in the go hamt implementation but failed to replicate here. The lack of validation here won't cause any issues on the current network as we only read HAMTs we've written, never untrusted HAMTs. However, we should fix this anyways.

feat: hamt: paranoid validation when reading nodes

---

Cargo.lock
ipld/car/Cargo.toml
ipld/car/src/util.rs

This is what we use in the FVM and the builtin actors. I'm switching to it now because we can't upgrade to the latest version of the integer-encoding library due to a breaking change (the futures it produces are no longer send).

feat(car): replace integer-encoding with unsigned-varint

---

Cargo.lock
fvm/CHANGELOG.md
fvm/Cargo.toml
sdk/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml
testing/conformance/Cargo.toml

- Updates proofs.
- Updates wasmtime.
- Other misc dep updates.

chore: release fvm v2.7.0 & fvm_shared v2.6.0

---

Cargo.lock
testing/integration/Cargo.toml

We need this in the helix libraries.

chore: release integration tests 3.2.0

---

ipld/hamt/src/bitfield.rs
ipld/hamt/src/hash_bits.rs
ipld/hamt/src/node.rs

Using a u8 here means we can statically guarantee that no bitfield access will panic due to a bounds error.
Based on https://github.com/filecoin-project/ref-fvm/pull/1864

fix: use better types in HAMT hashing

---

Makefile
README.md

- Don't set rust flags manually.
- Cargo fmt check, don't actually format.
- Don't allow warnings in the makefile.
- Let rustup install the correct targets automatically.
replaces #1883

chore: fix build instructions

---

Cargo.lock
fvm/src/call_manager/default.rs
fvm/src/gas/price_list.rs
fvm/src/kernel/default.rs
testing/calibration/shared/src/lib.rs
testing/integration/Cargo.toml
testing/integration/tests/events_test.rs
testing/integration/tests/gas_calibration_test.rs
testing/test_actors/actors/fil-events-actor/src/actor.rs
testing/test_actors/actors/fil-gas-calibration-actor/src/actor.rs

This charges the correct event gas and adds a few benchmarks. It also:
1. Tries to remove some variability when recording events by pre-allocating space.`
2. Validates utf8 up-front, then slices the validated string for better performance (and easier benchmarking).

feat: charge event gas

---

fvm/src/kernel/default.rs
testing/test_actors/actors/fil-events-actor/src/actor.rs

1. Fail with LimitExceeded where it makes sense.
2. Validate that we comsume all keys/values.

feat: cleanup event error cases

---

fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/syscalls/sself.rs
sdk/src/error.rs
sdk/src/sself.rs
sdk/src/sys/sself.rs
testing/conformance/src/vm.rs
testing/test_actors/actors/fil-readonly-actor/src/actor.rs
testing/test_actors/actors/fil-sself-actor/src/actor.rs

fixes https://github.com/filecoin-project/ref-fvm/issues/1837

feat: remove beneficiary from self destruct

---

Cargo.lock
fvm/CHANGELOG.md
fvm/Cargo.toml
sdk/CHANGELOG.md
sdk/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml
testing/calibration/shared/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/test_actors/actors/fil-address-actor/Cargo.toml
testing/test_actors/actors/fil-create-actor/Cargo.toml
testing/test_actors/actors/fil-events-actor/Cargo.toml
testing/test_actors/actors/fil-exit-data-actor/Cargo.toml
testing/test_actors/actors/fil-gas-calibration-actor/Cargo.toml
testing/test_actors/actors/fil-gaslimit-actor/Cargo.toml
testing/test_actors/actors/fil-hello-world-actor/Cargo.toml
testing/test_actors/actors/fil-integer-overflow-actor/Cargo.toml
testing/test_actors/actors/fil-ipld-actor/Cargo.toml
testing/test_actors/actors/fil-malformed-syscall-actor/Cargo.toml
testing/test_actors/actors/fil-oom-actor/Cargo.toml
testing/test_actors/actors/fil-readonly-actor/Cargo.toml
testing/test_actors/actors/fil-sself-actor/Cargo.toml
testing/test_actors/actors/fil-stack-overflow-actor/Cargo.toml
testing/test_actors/actors/fil-syscall-actor/Cargo.toml

We're skipping alpha.1 as we used that release to mark the switch over and I like to keep the version bump at the _end_ of the release cycle (to make it clear where the release happened).

chore: release v4.0.0-alpha.2

---

Cargo.lock
testing/test_actors/actors/fil-syscall-actor/Cargo.toml

This should fix much of the issues on CI

chore: update lockfile & deps post release

---

testing/integration/src/builtin.rs
testing/integration/src/tester.rs

The FVM relies on this so it can burn funds on self-destruct.

fix: auto-create the burnt funds account

---

fvm/src/gas/mod.rs

`GasDuration` is used in public API `GasTimer::new(duration: &mut GasDuration)` and as a public field `pub elapsed: GasDuration` in `GasCharge`, however, it's not publicly exported from the crate.  It will be helpful for e.g. converting between GasDuration in fvm@3 and fvm@4
This PR tries to fix that by publicly exporting it. Please let me know your feedback, thanks!

fix: publicly export `GasDuration`

---

fvm/src/gas/price_list.rs
fvm/src/kernel/default.rs
shared/src/sector/post.rs
shared/src/sector/registered_proof.rs

This is the counterpart of [PR 1391](https://github.com/filecoin-project/builtin-actors/pull/1391) from builtin actors repository.

Remove support of v1 proofs

---

Cargo.lock
fvm/CHANGELOG.md
fvm/Cargo.toml
sdk/CHANGELOG.md
sdk/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml
testing/calibration/shared/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/test_actors/actors/fil-address-actor/Cargo.toml
testing/test_actors/actors/fil-create-actor/Cargo.toml
testing/test_actors/actors/fil-events-actor/Cargo.toml
testing/test_actors/actors/fil-exit-data-actor/Cargo.toml
testing/test_actors/actors/fil-gas-calibration-actor/Cargo.toml
testing/test_actors/actors/fil-gaslimit-actor/Cargo.toml
testing/test_actors/actors/fil-hello-world-actor/Cargo.toml
testing/test_actors/actors/fil-integer-overflow-actor/Cargo.toml
testing/test_actors/actors/fil-ipld-actor/Cargo.toml
testing/test_actors/actors/fil-malformed-syscall-actor/Cargo.toml
testing/test_actors/actors/fil-oom-actor/Cargo.toml
testing/test_actors/actors/fil-readonly-actor/Cargo.toml
testing/test_actors/actors/fil-sself-actor/Cargo.toml
testing/test_actors/actors/fil-stack-overflow-actor/Cargo.toml
testing/test_actors/actors/fil-syscall-actor/Cargo.toml

- Removes v1 proofs.
- Exposes GasDuration constructor/type.

chore: release fvm v4 alpha-3

---

ipld/amt/src/node.rs

This issue is found [here](https://github.com/filecoin-project/builtin-actors/pull/1326#discussion_r1339431461), instead of panic, we can just return. 
This is useful when `start_at` is estimated which may be out of range.

amt: support `start_at` that is out of range in the first place

---

ipld/amt/src/amt.rs
ipld/amt/tests/amt_tests.rs

This lets us avoid traversing the AMT entirely when it isn't deep enough for the value to even appear.

pre-check AMT height when iterating

---

shared/src/sector/post.rs
shared/src/sector/registered_proof.rs

We removed too much code in https://github.com/filecoin-project/ref-fvm/pull/1896.
This PR fixes the situation:
- Add back Winning proof types
- Keep proofs indexation
- Remove `registered_winning_post_proof` method

fix: Add back Winning proof types

---

fvm/src/call_manager/default.rs
fvm/src/call_manager/mod.rs
fvm/src/executor/default.rs
fvm/src/kernel/default.rs
fvm/src/kernel/error.rs
fvm/src/kernel/mod.rs
fvm/src/syscalls/actor.rs
fvm/src/syscalls/bind.rs
fvm/src/syscalls/context.rs
fvm/src/syscalls/error.rs
fvm/src/syscalls/vm.rs
fvm/tests/default_kernel/mod.rs
sdk/src/actor.rs
sdk/src/sys/actor.rs
shared/src/error/mod.rs

Add a general-purpose ControlFlow syscall return value and use it. This way we don't need to add an `::Abort` case to the `ExecutionError` itself.

actor upgrade error refactor

---

fvm/src/kernel/default.rs

For https://github.com/filecoin-project/builtin-actors/issues/1464.
Built-in Actor events are encoded with CBOR and so FVM needs to allow that encoding.

Allow cbor encoding for events

---

shared/src/address/mod.rs

We currently just print the protocol and bytes, but that's not very human friendly.
Now:
```rust
println!("{:?}", Address::new_id(1));
```
Prints:
> `Address("f01")`

feat: pretty-print addresses when debug-formatting

---

Cargo.lock
shared/Cargo.toml
shared/src/address/network.rs

This prevents it from messing with the other tests.
fixes #1924

test: run the address::set_network test in a new process

---

shared/src/address/mod.rs

Running `cargo test` seems to non-deterministically select different networks causing the Address test_debug() test to fail

fix test failure when running cargo test

---

Cargo.lock
fvm/src/executor/default.rs
fvm/src/kernel/default.rs
fvm/src/kernel/filecoin.rs
fvm/src/kernel/mod.rs
testing/conformance/Cargo.toml
testing/conformance/src/vm.rs

Users can now glob-import the kernel's "prelude" module instead of, e.g., glob-importing the entire `kernel` and the top-level `fvm` crate. Ideally ambassador would handle importing all of its internal types, but it doesn't.

fix: make delegation simpler by introducing a prelude module

---

fvm/src/kernel/default.rs
fvm/src/kernel/filecoin.rs
fvm/src/kernel/mod.rs
fvm/src/syscalls/actor.rs
fvm/src/syscalls/crypto.rs
fvm/src/syscalls/debug.rs
fvm/src/syscalls/event.rs
fvm/src/syscalls/gas.rs
fvm/src/syscalls/ipld.rs
fvm/src/syscalls/mod.rs
fvm/src/syscalls/network.rs
fvm/src/syscalls/rand.rs
fvm/src/syscalls/sself.rs
fvm/src/syscalls/vm.rs
testing/conformance/src/vm.rs

This change has two parts:
1. Remove most (all except gas) "ops" from the base kernel trait, allowing kernels to implement only some operations.
2. Make syscalls declare the ops they actually need instead of depending on the entire kernel.
This should make it possible to implement custom kernels that expose fewer operations.
It also removes the `LimiterOps` trait as that's not really an "op".

refactor: make partial kernels possible

---

fvm/src/engine/mod.rs
fvm/src/kernel/mod.rs
fvm/src/syscalls/mod.rs
testing/conformance/src/vm.rs

The result of this function is cached and not tied to any given kernel. It shouldn't have access to a particular kernel's state because the "result" of calling this function will be used with multiple kernels (of the same type).

refactor: make `bind_syscalls` an associated function

---

fvm/src/kernel/filecoin.rs
fvm/src/lib.rs
fvm/src/syscalls/mod.rs
testing/conformance/src/vm.rs
testing/integration/src/tester.rs

It's not _actually_ generic over the inner kernel type (only works for
the `DefaultKernel`), so we might as well simplify that.
I.e., was:
DefaultFilecoinKernel<DefaultKernel<impl CallManager>>
Now:
DefaultFilecoinKernel<impl CallManager>

refactor: simplify the DefaultFilecoinKernel generics

---

fvm/CHANGELOG.md
fvm/src/executor/threaded.rs

And default to 8 if we can't get this information. This isn't a perfect metric (e.g., it doesn't take IO into account) but it's better than nothing).

fix: set the default thread-pool size by the available concurrency

---

fvm/src/kernel/mod.rs
fvm/src/syscalls/mod.rs
testing/conformance/src/vm.rs

Unfortunately, I had to drop the generics to prevent some circular type constraint evaluation issues. This is likely because:
1. `SyscallHandler` is generic over "self".
2. `SyscallHandler<Self>` is only implemented if `Self: FilecoinKernel`.
3. `FilecoinKernel` is only implemented if `Self: SyscallHandler<Self>`.
Rust _can_ figure all of this out if we specify concrete types, but it can't yet prove this generically.
NOTE: Ideally tests would catch this, but we don't yet have conformance tests for v4.

fix: bind syscalls in conformance tests

---

fvm/src/syscalls/context.rs
fvm/src/syscalls/filecoin.rs
fvm/src/syscalls/mod.rs

We're now exposing this to users so we need to clean this up a bit:
1. Document it.
2. Remove `Memory::read_cbor` from the public API, it's not safe (time-wise) to call on untrusted memory.

feat: cleanup & document the context API

---

fvm/src/engine/mod.rs
fvm/src/kernel/mod.rs
fvm/src/syscalls/actor.rs
fvm/src/syscalls/error.rs
fvm/src/syscalls/linker.rs
fvm/src/syscalls/mod.rs
testing/conformance/src/vm.rs

This cleans up and hides the implementation details of our syscall binding API.
Previously, we passed a wasmtime linker to the `SyscallHandler`. Unfortunately:
1. This exposed implementation details (wasmtime, the InvocationData object type, etc.).
2. The user had to import the `BindSyscall` trait to bind syscalls.
I've changed this by:
1. Replacing the `BindSyscall` trait (previously implemented on the "linker") with a `Syscall` trait implemented on all valid "syscall" functions.
2. Exposing an opaque `Linker` type with a `link_syscall` method instead of exposing the wasmtime linker directly. This lets us change/augment this type later.
I've also renamed "bind" to "link" in most places for consistency.

feat: cleanup Linker API

---

fvm/src/call_manager/default.rs
fvm/src/engine/mod.rs
fvm/src/executor/default.rs
fvm/src/kernel/default.rs
fvm/src/lib.rs
testing/conformance/benches/bench_drivers.rs
testing/conformance/src/driver.rs
testing/integration/src/tester.rs

1. Hide all wasmtime specific parts.
2. Unexport functions that don't need to be a part of the public API.
3. Rename functions for consistency.
4. Delete some unused code.

feat: cleanup Engine API

---

fvm/src/call_manager/default.rs

We'll record the trace error in `call_actor` itself.

fix: don't record the call error twice if we hit the max depth

---

fvm/src/call_manager/default.rs
fvm/src/call_manager/mod.rs
fvm/src/trace/mod.rs

This change has two parts:
1. Record the _entire_ actor state on invoke. This will let us accurately determine the state, address, etc. of an actor at the time of invocation even if the transaction is later reverted.
2. Stop tracing non-"send" events. Specifically:
- I've stopped tracing upgrades. They're not traditional "calls" and we'll want to handle them differently anyways.
- Previously, we were tracing InvokeActor events for implicit constructor calls and upgrades. I've removed those as well as I want all InvokeActor events to be paired with some other event.
This should finally give us enough information in Lotus to accurately translate an FVM trace into an EVM trace. Furthermore, the extra state we're recording in the InvokeActor event will be useful for debugging.

feat: record the entire actor state on invoke

---

fvm/src/call_manager/backtrace.rs
fvm/src/call_manager/default.rs

This is a pretty public API (information gets displayed to the user) and I'd rather not go about changing it at the moment. We'll probably bring this back eventually, but I'm trying to cut a release and integrate with the FFI with minimal outward-facing changes.

fix: revert backtrace frame from entrypoint to method

---

fvm/src/engine/mod.rs
fvm/src/gas/price_list.rs
fvm/src/kernel/default.rs
fvm/src/kernel/filecoin.rs
fvm/src/kernel/mod.rs
fvm/src/syscalls/gas.rs
fvm/src/syscalls/linker.rs
fvm/src/syscalls/mod.rs
fvm/tests/default_kernel/ops.rs
testing/conformance/src/vm.rs

It's not really a proper "ops" trait, it's more "basic functionality".
Additionally, the concept of a global price list is going to go away as we make the kernel more pluggable.
1. Move `GasOps::gas_available`/`GasOps::charge_gas` to the main `Kernel` trait as all kernels require them.
2. Remove `GasOps::gas_used`, it's only used for testing.
3. Remove `GasOps::price_list`. We're still exposing it on the CallManager, but one step at a time).

refactor: remove GasOps from the Kernel

---

fvm/src/kernel/default.rs
fvm/src/kernel/filecoin.rs
fvm/src/kernel/mod.rs
fvm/src/syscalls/actor.rs
fvm/src/syscalls/mod.rs
fvm/src/syscalls/send.rs
testing/conformance/src/vm.rs

Make them higher-level ops like everything else. I considered combining them into a single "call op" however, not all users may want to implement actor upgrading.
I've also moved the generic from the methods to the trait itself. This resolves anorth's comment on the `TestKernel` by allowing additional bounds to be specified by the _implementer_, instead of having all the bounds encoded on the trait itself:
> Note that KK, the type of the kernel to crate for the receiving actor, is ignored, and Self is passed as the type parameter for the nested call. If we could find the correct bound to specify KK for the call, we would. This restricts the ability for the TestKernel to itself be wrapped by another kernel type.

refactor: move send/upgrade out of the kernel

---

Cargo.lock
Cargo.toml
fvm/Cargo.toml
testing/integration/Cargo.toml
testing/integration/src/custom_kernel/mod.rs
testing/integration/src/lib.rs
testing/integration/src/tester.rs
testing/integration/tests/main.rs
testing/test_actors/actors/fil-custom-syscall/Cargo.toml
testing/test_actors/actors/fil-custom-syscall/src/actor.rs
testing/test_actors/actors/fil-custom-syscall/src/lib.rs
testing/test_actors/build.rs

See https://github.com/filecoin-project/ref-fvm/issues/1957
This PR adds an integration test which tests calling a new syscall using a custom kernel from actor code.

Add an integration test for testing new syscall using custom kernel

---

ipld/bitfield/src/lib.rs

This will defer to our implementation of `PartialEq`.

chore: implement Eq for bitfields

---

sdk/Cargo.toml
sdk/src/actor.rs
sdk/src/sys/actor.rs
testing/test_actors/actors/fil-upgrade-actor/Cargo.toml
testing/test_actors/actors/fil-upgrade-receive-actor/Cargo.toml

We now _compile_ with these features enabled (but not available to running actors) in the FVM itself, but it's better to leave them out of the SDK so we don't accidentally try to use them.

Put upgrade/install behind feature flags again

---

Cargo.lock
Cargo.toml
fvm/CHANGELOG.md
sdk/CHANGELOG.md
shared/CHANGELOG.md

This is a v4.1 because it's not a network-breaking change.

chore: release fvm, fvm_sdk, and fvm_shared v4.1.0

---

Cargo.toml

Unfortunately, cargo requires these to publish (for now).

fix: build: add versions to workspace dependencies

---

fvm/Cargo.toml
shared/Cargo.toml

When importing "self" as a dev-dependency (used to specify additional features when testing), we need to _not_ specify a version. Otherwise, cargo gets touchy when we try to publish because, obviously, that version hasn't yet been released (BECAUSE WE'RE CURRENTLY RELEASING IT!).

fix: build: use path dependencies for "self" imports

---

Cargo.lock
Cargo.toml
fvm/CHANGELOG.md
sdk/CHANGELOG.md
shared/CHANGELOG.md

Enables nv22 support by default.

chore: release fvm 4.1.1

---

Cargo.lock
Cargo.toml
fvm/Cargo.toml
fvm/src/lib.rs
shared/Cargo.toml
shared/src/lib.rs

That way, we actually get useful information.

test: exclude test logic from coverage reports

---

ipld/kamt/benches/kamt_benchmark.rs
ipld/kamt/src/kamt.rs
ipld/kamt/tests/kamt_tests.rs

I was going to leave this and deprecate it later, but we're making other braking changes anyways (to the error type).

feat: kamt: deprecate kamt for_each

---

ipld/kamt/Cargo.toml
ipld/kamt/src/iter.rs
ipld/kamt/src/node.rs

It was unused and we've removed it from the HAMT as well.

feat: kamt: remove "ignore dead links" feature

---

fvm/src/call_manager/default.rs
fvm/src/trace/mod.rs

FVMv3 exposed actor code-CIDs in traces, but v4 now exposes the entire invoked actor. This patch backports the FVMv4 logic to v3.
However, note: this change is slightly simplified. FVMv3 has a bug where we might include _multiple_ invoke events for the same actor if, e.g., we had to implicitly create it. This was fixed in FVMv4 but that fix has _not_ been backported. In practice, this shouldn't cause any issues in FVMv3 as long as the _last_ invoke event is used (which is how the filecoin-ffi library handles this).

Backport FVMv4 tracing changes to v3

---

fvm/src/kernel/default.rs

I gather that targeting `feat/nv22` is appropriate for this?
I can get Lotus itests that touch new events code using the dev branch on builtin-actors to pass after fixing this so hopefully this is all that's required here.

feat: allow CBOR events

---

Cargo.lock
fvm/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml

We already use the v12.0.2 on v4 so anyone on the network will be running that, but we might as well update it everywhere.

chore: update wasmtime to v12.0.2 on v3

---

shared/src/address/mod.rs

Trying to clean up this module a bit. I'll remove the other uses of lazy_static in a future (significantly more breaking) change.

feat: shared: check bls zero address without lazy_static

---

Cargo.lock
fvm/Cargo.toml
fvm/src/gas/timer.rs

We still need this crate in the IPLD datastructures because we use
`get_or_try_init`, but we don't need it in the FVM proper.

feat: fvm: remove once_cell

---

Cargo.lock
Cargo.toml
ipld/amt/fuzz/Cargo.toml
ipld/amt/fuzz/fuzz_targets/equivalence.rs
ipld/hamt/fuzz/Cargo.toml
ipld/hamt/fuzz/fuzz_targets/common.rs
ipld/kamt/fuzz/Cargo.toml
ipld/kamt/fuzz/fuzz_targets/common.rs

We don't really have a good reason to use it, so we might as well stick
to the standard `HashMap`.

chore: remove ahash

---

fvm/src/machine/default.rs
ipld/blockstore/src/block.rs

We can pre-compute the "empty" block and avoid a lazy static. It matters less here because we're not inside an actor (so we'd only compute this once on start anyways, but I'm trying to reduce our usage of lazy_static to the minimum.

chore: fvm: remove another lazy_static

---

Cargo.lock
Cargo.toml
fvm/CHANGELOG.md
sdk/CHANGELOG.md
shared/CHANGELOG.md

Bump FVM-release to unblock the nv23-skeleton: https://github.com/filecoin-project/filecoin-ffi/pull/452#issuecomment-2063465057

chore: release fvm 4.2.0

---

ipld/encoding/src/bytes.rs
ipld/encoding/src/raw.rs
ipld/hamt/src/hamt.rs
ipld/hamt/src/hash_algorithm.rs
ipld/hamt/src/iter.rs
ipld/hamt/src/node.rs
ipld/kamt/src/iter.rs
rust-toolchain.toml
shared/tests/address_test.rs

- upgrade rust toolchain to 1.78.0
- fix new clippy warnings
```
warning: bound is defined in more than one place
--> ipld/hamt/src/node.rs:229:18
|
229 |     fn get_value<Q: ?Sized, S: Blockstore>(
|                  ^
...
239 |         Q: Eq + Hash,
|         ^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#multiple_bound_locations
```
```
warning: unnecessary use of `get(&h2).is_none()`
--> shared/tests/address_test.rs:584:16
|
584 |     assert!(hm.get(&h2).is_none());
|             ---^^^^^^^^^^^^^^^^^^
|             |
|             help: replace it with: `!hm.contains_key(&h2)`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_get_then_check
```

chore: upgrade rust toolchain to 1.78.0

---

.github/workflows/ci.yml
fvm/Cargo.toml
fvm/src/gas/price_list.rs
fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/syscalls/context.rs
fvm/src/syscalls/crypto.rs
fvm/src/syscalls/mod.rs
sdk/Cargo.toml
sdk/src/crypto.rs
sdk/src/sys/crypto.rs
shared/src/crypto/signature.rs
testing/calibration/shared/src/lib.rs
testing/integration/Cargo.toml
testing/integration/tests/gas_calibration_test.rs
testing/integration/tests/main.rs
testing/test_actors/actors/fil-gas-calibration-actor/src/actor.rs
testing/test_actors/actors/fil-syscall-actor/Cargo.toml
testing/test_actors/actors/fil-syscall-actor/src/actor.rs
testing/test_actors/build.rs

This PR tries to implement https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0079.md without breaking FVM backward compatibility. 
(NOTE: This PR is largely based on https://github.com/filecoin-project/ref-fvm/pull/1914)
Closes https://github.com/filecoin-project/ref-fvm/issues/2001
Changes:
- Add `verify_bls_aggregate` syscall
- Add cargo feature `verify-signature` that keeps `verify_signature` syscall for backward compatibility
- Add integration test for the `verify-signature` feature
- Update CI to build and check the `verify-signature` feature

feat: FIP-0079: syscall for aggregated bls verification

---

Cargo.lock
Cargo.toml
fvm/CHANGELOG.md
sdk/CHANGELOG.md
shared/CHANGELOG.md

Bump FVM-release to unblock the NI-PoRep and nv23-testing in Butterfly-network

chore: release fvm 4.3.0

---

Cargo.lock

I have no idea how this could have gotten out of date. But apparently...

chore: update the lockfile to the correct version of the blockstore

---

Cargo.lock
Cargo.toml
fvm/CHANGELOG.md
fvm/src/kernel/mod.rs
testing/test_actors/actors/fil-syscall-actor/Cargo.toml

A new ambassador crate was released so we can now use attributes inside
delegable traits (and some macros that were previously unexported are
now exported by default). Basically, I'm just deleting code.

feat: simplify the verify-signatures feature

---

fvm/CHANGELOG.md
fvm/Cargo.toml
fvm/src/gas/price_list.rs
fvm/src/machine/default.rs
sdk/CHANGELOG.md
shared/CHANGELOG.md

- removed the `nv23-dev` feature flag and enabled NV23 support by default.

chore: remove `nv23-dev` flag

---

Cargo.lock
Cargo.toml
fvm/CHANGELOG.md
sdk/CHANGELOG.md
shared/CHANGELOG.md

Closes #2028 
Updated `Cargo.toml` for a new release.
Dates were wrong in the `CHANGELOG.md` files for 2024 releases (lmk if I am wrong).
If you guys want to merge more PRs before the release and make it a breaking change, happy to wait for it.
cc @rjan90

chore: release 4.3.2

---

fvm/src/engine/mod.rs

This will apparently interfere with some debugging tools, but we ran into an issue where Mach ports weren't always catching illegal instruction signals form wasmtime (affecting macos only).

fix: use unix signal handlers instead of Mach ports

---

fvm/src/engine/mod.rs

This will apparently interfere with some debugging tools, but we ran into an issue where Mach ports weren't always catching illegal instruction signals form wasmtime (affecting macos only).

[v3] fix: use unix signal handlers instead of Mach ports

---

fvm/src/machine/engine.rs

This will apparently interfere with some debugging tools, but we ran into an issue where Mach ports weren't always catching illegal instruction signals form wasmtime (affecting macos only).

[v2] fix: use unix signal handlers instead of Mach ports

---

Cargo.lock
Cargo.toml
fvm/Cargo.toml
fvm/src/kernel/error.rs
shared/Cargo.toml
testing/conformance/Cargo.toml

All except cid/multihash/fvm-wasm-instrument. That last one is consensus critical and cannot be upgraded beyond 0.2.0.

[v2] chore: update deps

---

Cargo.lock
Cargo.toml
fvm/CHANGELOG.md
sdk/CHANGELOG.md
shared/CHANGELOG.md

* update wasmtime from v19 to v24
* macos: use unix signal handling instead of mach ports
* update misc dependencies

chore: release v4.4.0

---

Cargo.lock
Cargo.toml
fvm/CHANGELOG.md
fvm/Cargo.toml
sdk/CHANGELOG.md
sdk/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml
testing/calibration/shared/Cargo.toml
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
testing/test_actors/actors/fil-address-actor/Cargo.toml
testing/test_actors/actors/fil-create-actor/Cargo.toml
testing/test_actors/actors/fil-events-actor/Cargo.toml
testing/test_actors/actors/fil-exit-data-actor/Cargo.toml
testing/test_actors/actors/fil-gas-calibration-actor/Cargo.toml
testing/test_actors/actors/fil-gaslimit-actor/Cargo.toml
testing/test_actors/actors/fil-hello-world-actor/Cargo.toml
testing/test_actors/actors/fil-integer-overflow-actor/Cargo.toml
testing/test_actors/actors/fil-ipld-actor/Cargo.toml
testing/test_actors/actors/fil-malformed-syscall-actor/Cargo.toml
testing/test_actors/actors/fil-oom-actor/Cargo.toml
testing/test_actors/actors/fil-readonly-actor/Cargo.toml
testing/test_actors/actors/fil-sself-actor/Cargo.toml
testing/test_actors/actors/fil-stack-overflow-actor/Cargo.toml
testing/test_actors/actors/fil-syscall-actor/Cargo.toml
tools/fvm-bench/Cargo.toml

And switch to workspace dependencies/versions to simplify the release process.

chore: release v3.11.0

---

Cargo.lock
Cargo.toml
fvm/CHANGELOG.md
fvm/Cargo.toml
sdk/CHANGELOG.md
sdk/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml
testing/conformance/Cargo.toml

Also switch to workspace-based versioning so we can more easily release everything all at once.

chore: release v2.9.0

---

README.md

This is a result of discussion in https://github.com/filecoin-project/filecoin-ffi/issues/468

docs: document versioning scheme

---

Cargo.lock
Cargo.toml
fvm/CHANGELOG.md
sdk/CHANGELOG.md
shared/CHANGELOG.md

Release v4.4.1 which drops the feature flag for network version 24.

chore: release v4.4.1

---

Cargo.lock
Cargo.toml
fvm/CHANGELOG.md
fvm/Cargo.toml
fvm/src/gas/price_list.rs
fvm/src/machine/default.rs
sdk/CHANGELOG.md
shared/CHANGELOG.md

We do not want to pull in the new wasmtime versions for the Lotus v1.30.0 release, just to be conservative because Lotus v1.30.0 will be a mandatory network version.
I have therefore:
- Created a `release/4.3` branch which was branched off the [fvm@v4.3.2](https://github.com/filecoin-project/ref-fvm/tree/fvm%40v4.3.2) tag.
- **In this PR:** Cherry-picked https://github.com/filecoin-project/ref-fvm/pull/2051, and bumped the version to v4.3.3, added changelog entries and updated the cargo.lock.
I looked through other things that have landed in master since v4.3.2 was tagged, but I could not see anything else that was directly needed for the nv24 upgrade. But it would be good if someone else also double confirmed

chore: release v4.3.3

---

Cargo.lock
Cargo.toml
fvm/CHANGELOG.md
sdk/CHANGELOG.md
shared/CHANGELOG.md

- Update wasmtime
- Update other deps
I've gone ahead and updated the rest of the deps as well (no major releases, just semver compatible versions) because there was a slew of other wasmtime and related crates that didn't appear to be automatically pulled in otherwise.

Release 4.4.2

---

Cargo.toml
testing/integration/tests/fil_integer_overflow.rs
testing/test_actors/actors/fil-integer-overflow-actor/src/actor/mod.rs
testing/test_actors/actors/fil-oom-actor/src/lib.rs

And update the integer overflow tests to match. It also gives us better test coverage of panics/traps.

test: use the correct wasm profile

---

Cargo.lock
testing/integration/Cargo.toml
testing/integration/benches/compile.rs

Specifically, it benchmarks compiling wasm -> native via cranelift.

Add an actor compilation benchmark

---

Cargo.lock
Cargo.toml
fvm/CHANGELOG.md
sdk/CHANGELOG.md
shared/CHANGELOG.md

This release brings in wasmtime 25.0.2. We're doing this as a _patch_ release because 4.4 brought in wasmtime 24 which introduced a significant regression in wasm compile time (and there shouldn't be anything breaking in this release either).

chore: release v4.4.3

---

Cargo.lock
Cargo.toml
fvm/CHANGELOG.md
sdk/CHANGELOG.md
shared/CHANGELOG.md

This release brings in wasmtime 25.0.2. We're doing this as a patch release because 2.9 brought in wasmtime 24 which introduced a significant regression in wasm compile time (and there shouldn't be anything breaking in this release either).

chore: release v2.9.1

---

Cargo.lock
Cargo.toml
fvm/CHANGELOG.md
sdk/CHANGELOG.md
shared/CHANGELOG.md

This release brings in wasmtime 25.0.2. We're doing this as a patch release because 3.11 brought in wasmtime 24 which introduced a significant regression in wasm compile time (and there shouldn't be anything breaking in this release either).

chore: release v3.11.1

---

Cargo.lock
Cargo.toml
fvm/CHANGELOG.md
ipld/amt/CHANGELOG.md
ipld/amt/Cargo.toml
ipld/bitfield/CHANGELOG.md
ipld/bitfield/Cargo.toml
ipld/blockstore/CHANGELOG.md
ipld/blockstore/Cargo.toml
ipld/car/CHANGELOG.md
ipld/car/Cargo.toml
ipld/encoding/CHANGELOG.md
ipld/encoding/Cargo.toml
ipld/hamt/CHANGELOG.md
ipld/hamt/Cargo.toml
ipld/kamt/CHANGELOG.md
ipld/kamt/Cargo.toml
sdk/CHANGELOG.md
shared/CHANGELOG.md

And I mean, _EVERYTHING_.
- `fvm`, `fvm_shared`, `fvm_sdk`, and `fvm_integration_tests` 4.5.0
- `fvm_ipld_bitfield` 0.7.0
- `fvm_ipld_amt` 0.7.0
- `fvm_ipld_hamt` 0.10.0
- `fvm_ipld_kamt` 0.4.0
- `fvm_ipld_car` 0.8.0
- `fvm_ipld_blockstore` 0.3.0
- `fvm_ipld_encoding` 0.5.0

chore: release everything

---

Cargo.lock
Cargo.toml

We explicitly specify the features we need and don't want to depend on blake3, sha1, or strobe-rs unnecessarily.

fix: remove default multihash-codetable features

---

Cargo.lock
Cargo.toml
fvm/CHANGELOG.md
ipld/amt/CHANGELOG.md
ipld/amt/Cargo.toml
ipld/bitfield/CHANGELOG.md
ipld/bitfield/Cargo.toml
ipld/blockstore/CHANGELOG.md
ipld/blockstore/Cargo.toml
ipld/car/CHANGELOG.md
ipld/car/Cargo.toml
ipld/encoding/CHANGELOG.md
ipld/encoding/Cargo.toml
ipld/hamt/CHANGELOG.md
ipld/hamt/Cargo.toml
ipld/kamt/CHANGELOG.md
ipld/kamt/Cargo.toml
sdk/CHANGELOG.md
shared/CHANGELOG.md

- `fvm`, `fvm_shared`, `fvm_sdk`, and `fvm_integration_tests` 4.5.1
- `fvm_ipld_bitfield` 0.7.1
- `fvm_ipld_amt` 0.7.1
- `fvm_ipld_hamt` 0.10.1
- `fvm_ipld_kamt` 0.4.1
- `fvm_ipld_car` 0.8.1
- `fvm_ipld_blockstore` 0.3.1
- `fvm_ipld_encoding` 0.5.1

chore: release all crates

---

fvm/Cargo.toml
fvm/src/gas/price_list.rs
fvm/src/machine/default.rs
shared/src/version/mod.rs

feat: add nv25-skeleton

---

Cargo.lock
Cargo.toml
fvm/CHANGELOG.md
fvm/Cargo.toml
fvm/src/gas/price_list.rs
fvm/src/machine/default.rs
sdk/CHANGELOG.md
shared/CHANGELOG.md
shared/src/version/mod.rs

Closes: https://github.com/filecoin-project/ref-fvm/issues/2075
As per comment in: https://github.com/filecoin-project/ref-fvm/pull/2077#issuecomment-2467259607, we need to cut the skeleton work on release/4.4 until porting of a newer version of cid/multihash has happened elsewhere before we can bubble up releases on v4.5.x

chore: release v4.4.4

---

ipld/amt/benches/amt_benchmark.rs
ipld/amt/src/amt.rs
ipld/amt/src/iter.rs
ipld/amt/tests/amt_tests.rs
ipld/kamt/src/kamt.rs

These are useful because they handle some error cases and the ranged version is especially useful as using iter + skip etc. is actually kind of annoying. It would still be better to replace these with iterators in many cases, but replacing them _everywhere_ is annoying and not worth the effort.

feat(ipld): undeprecate `for_each` methods for hamt/kamt

---

Cargo.lock
Cargo.toml
fvm/Cargo.toml
fvm/src/blockstore/buffered.rs
fvm/src/init_actor.rs
fvm/src/kernel/default.rs
fvm/src/kernel/hash.rs
fvm/src/kernel/mod.rs
fvm/src/lib.rs
fvm/src/machine/default.rs
fvm/src/machine/manifest.rs
fvm/src/state_tree.rs
fvm/tests/default_kernel/mod.rs
fvm/tests/default_kernel/ops.rs
fvm/tests/dummy.rs
sdk/Cargo.toml
shared/Cargo.toml
shared/src/crypto/hash.rs
shared/tests/commcid_tests.rs
testing/conformance/Cargo.toml
testing/conformance/src/driver.rs
testing/conformance/src/vm.rs

- cid
- multihash
- ipld-core
This is a major breaking change and requires a bit of a refactor.

chore: update ipld crates

---

Cargo.lock

This only really matters for tests as upstream crates will check-in their own lockfiles, but it's nice to see what changed (and, e.g., verify that old cid/multihash versions have been cleared from the dependency tree).

chore: update cargo lockfile

---

ipld/kamt/src/kamt.rs

This PR introduces a new `clear` method to the `Kamt` data structure, allowing users to reset the root to an empty node and clear all entries. 
- Added `pub fn clear` to `Kamt` to reset and clear all entries.
- Updated the test suite with `test_clear` to verify:
- Entries exist before clearing.
- Entries are removed after calling `clear`.
- The `Kamt` remains functional post-clear.
This addition enhances usability by providing an efficient way to clear the `Kamt`. 
This functionality is introduced to support the implementation of Transient Storage (EIP-1153) in `builtin-actors`, enabling efficient clearing of the KAMT while adhering to Rust's RAII expectations and best practices. The previous approach attempts of using `take`/`delete` followed by `new` was unsuitable in Rust due to its …

feat: kamt: Add public fn clear to reset and clear all entries in KAMT

---

ipld/hamt/src/hamt.rs

following up on changes to the KAMT in #2092 this PR changes HAMT to support a clear() method
This PR introduces a new `clear` method to the `Hamt` data structure, allowing users to reset the root to an empty node and clear all entries. 
- Added `pub fn clear` to `Hamt` to reset and clear all entries.
- Updated the test suite with `test_clear` to verify:
- Entries exist before clearing.
- Entries are removed after calling `clear`.
- The `Hamt` remains functional post-clear.
This addition enhances usability by providing an efficient way to clear the `Hamt`.

feat: hamt: Add public fn clear to reset and clear all entries in HAMT

---

Cargo.lock
Cargo.toml
fvm/CHANGELOG.md
sdk/CHANGELOG.md
shared/CHANGELOG.md

chore: release v4.5.3

---

Cargo.lock
Cargo.toml
ipld/hamt/CHANGELOG.md
ipld/hamt/Cargo.toml
ipld/kamt/CHANGELOG.md
ipld/kamt/Cargo.toml

- fvm_ipld_hamt@v0.10.3
- fvm_ipld_kamt@v0.4.3

chore: release kamt/hamt to add a clear method

---

fvm/src/call_manager/default.rs
fvm/src/call_manager/mod.rs
fvm/src/kernel/default.rs
fvm/src/kernel/mod.rs
fvm/src/trace/mod.rs
fvm/tests/dummy.rs

move the actor logs into the trace

---

Cargo.lock
ipld/kamt/Cargo.toml
ipld/kamt/src/id.rs
ipld/kamt/tests/kamt_tests.rs

We still need to do this for the HAMT, but this is progress.

chore: remove the hash-utils dependency from the KAMT

---

shared/CHANGELOG.md
shared/src/sector/registered_proof.rs

This makes the naming consistent with [built-actors side](https://github.com/filecoin-project/builtin-actors/blob/f414380b417bcdcab859ba5efd55fc085a83358f/actors/miner/src/state.rs#L1278-L1279).

nit: fix naming

---

sdk/src/sys/rand.rs

docs: remove any mentions of randomness lookback limits

---

Cargo.lock
Cargo.toml
ipld/encoding/Cargo.toml

Adds support for default fields by being less strict up-front when decoding maps and lists and allowing the visitors to determine what/how to consume the tokens.
I had a bit of trouble using `cargo` commands to make this happen, particularly to get ipld/encoding/Cargo.toml updated, so I ended up just bumping the numbers manually and doing `cargo build` to get Cargo.lock to update. So I'd like to know what the proper way would be to do this.

chore: update ipld-core and serde_ipld_dagcbor

---

shared/src/version/mod.rs

Ref: https://github.com/filecoin-project/builtin-actors/pull/1649
Ref: https://github.com/filecoin-project/FIPs/pull/1134
Shouldn't land until the FIP is accepted and we have agreement on the approach of using the network version to signal end of grace period.

feat: add Tock / nv26 and nv27 TBD

---

Cargo.lock
testing/test_actors/actors/fil-ipld-actor/Cargo.toml
testing/test_actors/actors/fil-ipld-actor/src/actor.rs
testing/test_actors/actors/fil-sself-actor/Cargo.toml
testing/test_actors/actors/fil-sself-actor/src/actor.rs
testing/test_actors/actors/fil-syscall-actor/Cargo.toml
testing/test_actors/actors/fil-syscall-actor/src/actor.rs

Follow-up from https://github.com/filecoin-project/ref-fvm/pull/2114, I don't think any of this is used anywhere so we may as well just remove it?

chore: remove minicov

---

fvm/src/engine/mod.rs
fvm/src/machine/default.rs
fvm/src/syscalls/event.rs
fvm/src/syscalls/linker.rs
fvm/src/syscalls/send.rs
ipld/amt/src/diff.rs
ipld/car/src/util.rs
ipld/encoding/src/bytes.rs
ipld/hamt/src/iter.rs
ipld/hamt/src/node.rs
ipld/kamt/src/iter.rs
ipld/kamt/src/kamt.rs
ipld/kamt/src/node.rs
rust-toolchain.toml
shared/src/econ/mod.rs
shared/src/sys/mod.rs
shared/tests/address_test.rs
testing/conformance/src/vector.rs
testing/conformance/tests/runner.rs
testing/integration/src/tester.rs

This fixes a crash we were seeing in CI in v1.81.0.

Update to Rust 1.86.0

---

fvm/src/engine/mod.rs
testing/integration/tests/main.rs
testing/test_actors/actors/fil-oom-actor/src/lib.rs

Closes: https://github.com/filecoin-project/ref-fvm/issues/2128
Default is 4GiB, the initial size of the virtual address space. The full 32-bit address space means runtime memory bounds checking should be elided.
I think this is all that's needed, but it might be interesting to try and do some basic before & after benchmarking. I can't find an obvious way to do that though, @Stebalien suggestions?

chore: use default wasmtime memory_reservation

---

Cargo.lock
Cargo.toml
fvm/Cargo.toml
fvm/src/kernel/error.rs
ipld/car/Cargo.toml
shared/Cargo.toml
shared/src/address/errors.rs
testing/conformance/Cargo.toml
testing/integration/Cargo.toml
tools/fvm-bench/Cargo.toml

- The first patch updates non-breaking changes (mostly patch versions).
- The second patch updates major versions and addresses fallout.

chore: update dependencies

---

Cargo.lock
Cargo.toml
fvm/Cargo.toml
fvm/src/system_actor.rs
ipld/encoding/Cargo.toml
ipld/encoding/src/lib.rs
shared/Cargo.toml
shared/src/event/mod.rs
shared/src/piece/mod.rs
shared/src/receipt.rs
shared/src/sector/post.rs
testing/integration/Cargo.toml
testing/integration/tests/gaslimit_test.rs
testing/test_actors/actors/fil-custom-syscall/Cargo.toml
testing/test_actors/actors/fil-events-actor/Cargo.toml
testing/test_actors/actors/fil-gaslimit-actor/Cargo.toml
testing/test_actors/actors/fil-gaslimit-actor/src/actor.rs
testing/test_actors/actors/fil-integer-overflow-actor/Cargo.toml
testing/test_actors/actors/fil-upgrade-actor/Cargo.toml
testing/test_actors/actors/fil-upgrade-actor/src/actor.rs
testing/test_actors/actors/fil-upgrade-receive-actor/Cargo.toml
testing/test_actors/actors/fil-upgrade-receive-actor/src/actor.rs

We publically re-export this crate so upgrading it is a breaking change. Which is... annoying! But this latest version literally adds nothing so I've:
1. Moved the `serde_tuple` dependency into `fvm_ipld_encoding`.
2. Used the re-exports everywhere.
For context, releasing breaking changes for the `fvm_ipld_encoding` crate is not fun (it's used everywhere).

feat: downgrade serde_tuple and move it into the encoding crate

---

Cargo.lock
Cargo.toml
ipld/amt/CHANGELOG.md
ipld/amt/Cargo.toml
ipld/bitfield/CHANGELOG.md
ipld/bitfield/Cargo.toml
ipld/car/CHANGELOG.md
ipld/car/Cargo.toml
ipld/encoding/Cargo.toml
ipld/hamt/CHANGELOG.md
ipld/hamt/Cargo.toml
ipld/kamt/CHANGELOG.md
ipld/kamt/Cargo.toml

- release `fvm_ipld_amt` 0.7.4
- release `fvm_ipld_bitfield` 0.7.2
- release `fvm_ipld_car` 0.8.2
- release `fvm_ipld_encoding` 0.5.3
- release `fvm_ipld_hamt` 0.10.4
- release `fvm_ipld_kamt` 0.4.5

chore: release IPLD crates

---

Cargo.lock
ipld/car/Cargo.toml
ipld/car/src/block.rs
ipld/car/src/lib.rs
ipld/car/src/util.rs
ipld/car/tests/car_file_test.rs
testing/conformance/src/actors.rs
testing/conformance/src/vector.rs
testing/integration/Cargo.toml
testing/integration/src/bundle.rs

This isn't highly parallel networking code so making it async isn't worth the added complexity. The logic in this library isn't _that_ complex, but the async logic in the conformance test engine definitely is and I want to remove all async code from that library next.
TL;DR: slowly remove an unmaintained dependency (`async-std`) and make everything a little more maintainable at the same time.
Part one of #2144

Remove async from `fvm_ipld_car`

---

Cargo.lock
Cargo.toml
ipld/car/CHANGELOG.md
ipld/car/Cargo.toml

Removes async support and simplifies interfaces.

chore: release fvm_ipld_car v0.9.0

---

Cargo.lock
shared/Cargo.toml
shared/src/crypto/signature.rs

fix(fvm): accept malleable secp256k1 signatures (per EVM, etc.)

---

Cargo.lock
shared/Cargo.toml
shared/src/crypto/signature.rs

fix(fvm): accept malleable secp256k1 signatures (per EVM, etc.) (backport v2)

---

Cargo.lock
Cargo.toml
testing/conformance/src/actors.rs
testing/conformance/src/vector.rs

This removes the async dependency (from the car logic). I'll update the
conformance tests in the next patch.

chore: update fvm_ipld_car in v3

---

Cargo.lock
Cargo.toml
testing/conformance/src/actors.rs
testing/conformance/src/vector.rs

This removes the async dependency (from the car logic). I'll update the
conformance tests in the next patch.

chore: update fvm_ipld_car in v2

---

testing/conformance/src/vector.rs

I renamed the field when switching to rust 2024 but this broke deserializing test vectors (which we only use in v3/v2).

fix: correctly deserialize test vectors

---

Cargo.lock
testing/conformance/Cargo.toml
testing/conformance/benches/bench_drivers.rs
testing/conformance/src/actors.rs
testing/conformance/src/bin/perf-conformance.rs
testing/conformance/src/lib.rs
testing/conformance/src/vector.rs
testing/conformance/tests/runner.rs

Switch from async-std to tokio runtime and maintain rough test execution time while simplifying the async implementation.
This builds on some of the simplifying work that went in to https://github.com/filecoin-project/ref-fvm/pull/2173, but aborts on the use of rayon because of the mutex contention issues that involved. It doesn't make all of the async complexity go away, we use `tokio::task::spawn_blocking` to run the tasks and use `buffer_unordered` to control our concurrency, but we don't lose as much code as #2173 did (`+148 −641` vs `+166 −460` and the whole `TEST_VECTOR_PARALLELISM` thing still exists here).

chore: migrate conformance test runner to tokio 

---

deny.toml

This suppresses https://rustsec.org/advisories/RUSTSEC-2025-0046.html. See https://github.com/filecoin-project/ref-fvm/issues/2186 for full context. Without this, unrelated PRs will fail.

chore: suppress RUSTSEC-2025-0046

---

.github/workflows/ci.yml
Makefile
fvm/src/account_actor.rs
fvm/src/gas/timer.rs
fvm/src/syscalls/error.rs
ipld/amt/src/lib.rs
ipld/bitfield/src/rleplus/mod.rs
sdk/src/message.rs
sdk/src/sys/actor.rs
sdk/src/sys/mod.rs
shared/src/sys/out.rs

- added `cargo doc` checks to the CI with fail on warnings,
- fixed warnings.
Closes https://github.com/filecoin-project/ref-fvm/issues/2191

feat(ci): deny cargo doc warnings

---

ipld/amt/src/amt.rs
ipld/amt/src/lib.rs
ipld/amt/src/node.rs
ipld/amt/tests/amt_tests.rs

This exposes an alternative iteration method without caching. Without it, the memory usage for iterating over deal proposals is too high (my 64 GiB machine gets knocked out under a minute). For reference, this works fine in Go's AMT implementation.
With `for_each_cacheless`, I can iterate the proposals in ~90s (no-op iteration).
The logic is mostly taken from the `for_each_while_mut`.

feat: cacheless amt iteration

---

Cargo.lock
fvm/CHANGELOG.md
fvm/Cargo.toml
shared/CHANGELOG.md
shared/Cargo.toml

Backported https://github.com/filecoin-project/ref-fvm/pull/2200 to `v3`

chore(v3): backport `filecoin-proofs-api` to 19 update

---

Cargo.lock
fvm/CHANGELOG.md
fvm/Cargo.toml
sdk/CHANGELOG.md
shared/CHANGELOG.md
shared/Cargo.toml

Backports https://github.com/filecoin-project/ref-fvm/pull/2200 to v2.

chore(v2): backport filecoin-proofs-api to 19 update 

---

Cargo.lock
Cargo.toml
fvm/CHANGELOG.md
shared/CHANGELOG.md

Release with backported:
- https://github.com/filecoin-project/ref-fvm/pull/2206
- https://github.com/filecoin-project/ref-fvm/pull/2207

chore: release v3.13.2

---

.github/dependabot.yml

See https://github.com/filecoin-project/ref-fvm/pull/2212#issuecomment-3230997499
This might work or not, given it's a git dependency. Let's try!

chore: add `fil_builtin_actors_bundle` to dependabot

---

Cargo.lock

Executed `cargo update -p fil_builtin_actors_bundle` to resolve advisory fiasco [here](https://github.com/filecoin-project/ref-fvm/actions/runs/17267746146/job/49003901983?pr=2211):
```
warning: license expression was not specified in manifest
├ fvm-bench v0.1.0
error[unmaintained]: async-std has been discontinued
┌─ /github/workspace/Cargo.lock:24:1
│
24 │ async-std 1.13.1 registry+https://github.com/rust-lang/crates.io-index
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ unmaintained advisory detected
│
├ ID: RUSTSEC-2025-0052
├ Advisory: https://rustsec.org/advisories/RUSTSEC-2025-0052
├ The `async-std` has been discontinued.
Alternatives:
- [smol](https://crates.io/crates/smol)
├ Announcement: https://github.com/async-rs/async-std
├ Solution: No safe upgrade …
```

fix: bump `fil_builtin_actors_bundle` to latest master

---

.github/dependabot.yml

This reverts commit d42b9d30af5dbc60f5aba91081afa2784feb0abc.
Unfortunately, [it doesn't seem Dependabot can deal with git dependencies](https://github.com/filecoin-project/ref-fvm/actions/runs/17293379473/job/49085726259):
```
updater | 2025/08/28 10:41:34 INFO <job_1085959453> Checking if fil_builtin_actors_bundle b7a35b4368377f090465553d0d6fe651fefb771b needs updating
updater | 2025/08/28 10:41:34 INFO <job_1085959453> Latest version is 
updater | 2025/08/28 10:41:34 INFO <job_1085959453> Requirements to unlock update_not_possible
2025/08/28 10:41:34 INFO <job_1085959453> Requirements update strategy bump_versions
updater | 2025/08/28 10:41:34 INFO <job_1085959453> No update possible for fil_builtin_actors_bundle b7a35b4368377f090465553d0d6fe651fefb771b
```

Revert "chore: add `fil_builtin_actors_bundle` to dependabot (#2213)"

---

ipld/amt/CHANGELOG.md
ipld/amt/src/amt.rs
ipld/amt/src/node.rs
ipld/amt/tests/amt_tests.rs

Fixed the lack of error propagation in the `Amt::for_each_cacheless`. Thanks @hanabi1224 for pointing this out.

fix: propagate errors in `Amt::for_each_cacheless`

---

deny.toml
fvm/Cargo.toml
fvm/src/gas/price_list.rs
fvm/src/machine/default.rs
shared/src/version/mod.rs

feat: nv28 skeleton
